Repository desktop/desktop, pull requests merged in 2018-11, with the labels that each got.

#6050 handle really long banner messages
  app/src/ui/banners/successful-merge.tsx
  app/styles/ui/banners/_successful-merge.scss
Labels: ready-for-review

#6061 kill off unnecessary margin inside compare tab branch list
  app/styles/ui/history/_history.scss
Labels: ready-for-review

#6059 ensure status after aborting a merge reflects reality
  app/src/lib/dispatcher/dispatcher.ts
Labels: ready-for-review

#6044 styling changes for merge filter text box
  app/styles/ui/dialogs/_merge.scss
Labels: ready-for-review

#6037 refactor commit message state handling
  app/src/lib/app-state.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/git-store.ts
  app/src/lib/stores/repository-state-cache.ts
  app/src/ui/changes/changes-list.tsx
  app/src/ui/changes/commit-message.tsx
  app/src/ui/changes/sidebar.tsx
  app/test/unit/git-store-test.ts
Labels: ready-for-review

#6053 add some new Git APIs to improve our Git LFS support
  app/src/lib/git/lfs.ts
  app/test/unit/git/lfs-test.ts
Labels: ready-for-review

#6074 move status tests away from chai
  app/test/unit/git/status-test.ts
Labels: ready-for-review, tech-debt

#6072 add support for reporting a binary file is in a conflicted state
  app/src/lib/git/status.ts
  app/src/models/status.ts
  app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx
Labels: ready-for-review

#6083 Release notes for 1.5 Beta 3
  app/package.json
  changelog.json
Labels: ready-for-review

#5999 extract labels to it's own document and refresh
  .github/CONTRIBUTING.md
  docs/process/labels.md
Labels: docs, ready-for-review

#6026 remove old config after Azure Pipelines rename
  vsts.yml
Labels: infrastructure, ready-for-review

#6078 Disable Compare on GitHub menu item when no repository is selected
  app/src/lib/menu-update.ts
Labels: ready-for-review

#5984 sanitized-repository-name: escape emojis
  app/src/ui/add-repository/sanitized-repository-name.ts
  app/test/unit/sanitized-repository-name-test.ts
Labels: ready-for-review

#6079 add keyboard shortcut for reverse tab order to ignore list
  app/src/ui/diff/text-diff.tsx
Labels: ready-for-review

#6081 switch over to LinkButton which plays nice with tab order OOTB
  app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx
Labels: ready-for-review

#6080 tidy up log message to provide better context
  app/src/lib/dispatcher/dispatcher.ts
Labels: ready-for-review, tech-debt

#6097 Clear commit message draft after conflicted merge
  app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx
Labels: ready-for-review

#6063 improve conflict detection for binary files
  app/src/lib/git/binary-files.ts
  app/src/lib/git/status.ts
  app/src/models/conflicts.ts
  app/src/models/status.ts
  app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx
  app/test/fixtures/detect-conflict-in-binary-file/_git/COMMIT_EDITMSG
  app/test/fixtures/detect-conflict-in-binary-file/_git/HEAD
  app/test/fixtures/detect-conflict-in-binary-file/_git/ORIG_HEAD
  app/test/fixtures/detect-conflict-in-binary-file/_git/config
  app/test/fixtures/detect-conflict-in-binary-file/_git/description
  app/test/fixtures/detect-conflict-in-binary-file/_git/index
  app/test/fixtures/detect-conflict-in-binary-file/_git/info/exclude
  app/test/fixtures/detect-conflict-in-binary-file/_git/logs/HEAD
  app/test/fixtures/detect-conflict-in-binary-file/_git/logs/refs/heads/another-branch
  app/test/fixtures/detect-conflict-in-binary-file/_git/logs/refs/heads/make-a-change
  app/test/fixtures/detect-conflict-in-binary-file/_git/logs/refs/heads/master
  app/test/fixtures/detect-conflict-in-binary-file/_git/objects/43/ad2bfc1d942394575153fc5bde254651ec613f
  app/test/fixtures/detect-conflict-in-binary-file/_git/objects/53/94b63bf7830657a8529192db04a9913637fd37
  app/test/fixtures/detect-conflict-in-binary-file/_git/objects/58/f54b26b4d22d4d7ef3a5178bb8e54b3f20ef50
  app/test/fixtures/detect-conflict-in-binary-file/_git/objects/7d/a83e495976a27f1abc5a49f296042bade37293
  app/test/fixtures/detect-conflict-in-binary-file/_git/objects/80/7b13f4c677f3bba1a6a16cfe45a43a4324616a
  app/test/fixtures/detect-conflict-in-binary-file/_git/objects/85/349ad98020363d853e1b0579d332ebfb91fd9b
  app/test/fixtures/detect-conflict-in-binary-file/_git/objects/8d/e4e8ef73caec02726414b9d6842fb609b7c8db
  app/test/fixtures/detect-conflict-in-binary-file/_git/objects/93/7fe9edabbcc419cb852e15ab6c168dc44bb182
  app/test/fixtures/detect-conflict-in-binary-file/_git/objects/95/1d91c33efeacee3cf6ba54b57afd6a3ad4f18a
  app/test/fixtures/detect-conflict-in-binary-file/_git/objects/ad/8f0698562a3761e11c9d9a1ddb5c6addc86824
  app/test/fixtures/detect-conflict-in-binary-file/_git/objects/ce/95de4a313a334d301cbfd8eda7448c8bf9442c
  app/test/fixtures/detect-conflict-in-binary-file/_git/objects/f9/b55b3f29827034d56ee8cf275de9e22bd49a99
  app/test/fixtures/detect-conflict-in-binary-file/_git/refs/heads/another-branch
  app/test/fixtures/detect-conflict-in-binary-file/_git/refs/heads/make-a-change
  app/test/fixtures/detect-conflict-in-binary-file/_git/refs/heads/master
  app/test/fixtures/detect-conflict-in-binary-file/my-cool-image.png
  app/test/unit/git/status-test.ts
Labels: ready-for-review

#6089 return commit id from commit and merge operations
  app/src/lib/git/commit.ts
  app/src/lib/stores/app-store.ts
  app/test/unit/git/commit-test.ts
Labels: ready-for-review

#6103 change branch merge tooltip to not mention commit
  app/src/ui/branches/branches-container.tsx
Labels: ready-for-review

#6112 Spacing and timing tweaks
  app/src/ui/banners/successful-merge.tsx
  app/styles/ui/_branches.scss
  app/styles/ui/banners/_successful-merge.scss
  app/styles/ui/dialogs/_merge-conflicts.scss
Labels: ready-for-review

#6096 show merge success banner after merge conflict resolved and committed
  app/src/lib/app-state.ts
  app/src/lib/dispatcher/dispatcher.ts
  app/src/lib/stores/app-store.ts
  app/src/ui/app.tsx
  app/src/ui/banners/successful-merge.tsx
  app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx
Labels: ready-for-review

#6116 use getStatus to detect conflicted repository state
  app/src/lib/app-state.ts
  app/src/lib/dispatcher/dispatcher.ts
  app/src/lib/git/merge.ts
  app/src/lib/git/status.ts
  app/src/lib/stats/stats-store.ts
  app/src/lib/stores/app-store.ts
  app/src/ui/app.tsx
  app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx
Labels: ready-for-review

#6113 successful merge banner animation
  app/src/ui/app.tsx
  app/src/ui/banners/successful-merge.tsx
  app/styles/ui/_repository.scss
  app/styles/ui/banners/_successful-merge.scss
Labels: ready-for-review

#6109 avoid resolving conflicts using "Open in External Editor" flow if no editors found
  app/src/lib/app-state.ts
  app/src/lib/dispatcher/dispatcher.ts
  app/src/lib/editors/lookup.ts
  app/src/lib/stores/app-store.ts
  app/src/ui/app.tsx
  app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx
Labels: ready-for-review

#6122 UI changes to handle binary files when conflicted
  app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx
  app/styles/ui/dialogs/_merge-conflicts.scss
Labels: ready-for-review

#6126 changelog for 1.5.0-beta4
  app/package.json
  changelog.json
Labels: ready-for-review

#6143 hide branches list when launching merge branch dialog
  app/src/ui/branches/branches-container.tsx
Labels: ready-for-review

#6133 Detect and prompt users to use command line for text file merge conflicts without markers
  app/src/lib/git/status.ts
  app/src/models/conflicts.ts
  app/src/models/status.ts
  app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx
Labels: ready-for-review

#6136 add flag to createMergeCommit to be consistent with Git CLI
  app/src/lib/git/commit.ts
Labels: ready-for-review

#6146 Release Notes for 1.5.0 beta 5
  app/package.json
  changelog.json
Labels: ready-for-review

#6145 remove unecessary enum comments
  app/src/models/status.ts
Labels: ready-for-review, tech-debt

#6183 enable new merge conflicts dialog for everyone
  app/src/lib/feature-flag.ts
Labels: ready-for-review

#6185 Add time-sensitive label for PRs
  docs/process/labels.md
Labels: docs

#6151 remove gcov from codecov
  .codecov.yml
  package.json
Labels: infrastructure, ready-for-review

#6129 generate HTML bundle of coverage stats by default
  jest.config.js
Labels: infrastructure, ready-for-review, time-sensitive

#6119 Return the SHA in merge
  app/src/lib/git/commit.ts
  app/src/lib/git/core.ts
  app/src/lib/git/merge.ts
  app/src/lib/stores/git-store.ts
Labels: ready-for-review

#5931 Keyboard selection doesn't work properly in Clone a Repository dialog
  app/src/ui/clone-repository/clone-github-repository.tsx
Labels: ready-for-review

#6152 Bump for last node 8
  .node-version
  .nvmrc
  .tool-versions
  .travis.yml
  appveyor.yml
  azure-pipelines.yml
  docs/contributing/setup-macos.md
  docs/contributing/setup.md
Labels: infrastructure, ready-for-review

#4533 Add Dockerfile Highlights
  app/src/highlighter/index.ts
  app/src/lib/highlighter/types.ts
  app/src/lib/highlighter/worker.ts
  app/src/ui/diff/syntax-highlighting/index.ts
  docs/technical/syntax-highlighting.md
Labels: ready-for-review

#6100 extract logic from inside Commit class
  app/src/lib/web-flow-committer.ts
  app/src/models/avatar.ts
  app/src/models/commit.ts
  app/src/ui/lib/commit-attribution.tsx
  app/test/unit/git/checkout-test.ts
Labels: ready-for-review, tech-debt, time-sensitive

#6189 add a unified commit context shape to combine related data
  app/src/lib/dispatcher/dispatcher.ts
  app/src/lib/format-commit-message.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/git-store.ts
  app/src/models/commit.ts
  app/src/ui/changes/changes-list.tsx
  app/src/ui/changes/commit-message.tsx
  app/src/ui/changes/sidebar.tsx
  app/test/unit/format-commit-message.ts
Labels: ready-for-review, tech-debt

#6197 Reverse fold/unfold icons for expand button
  app/src/ui/history/commit-summary.tsx
Labels: ready-for-review

#6092 Upgrade Prettier to v1.15
  app/src/crash/index.tsx
  app/src/lib/shells/win32.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/git-store.ts
  app/src/main-process/menu/build-default-menu.ts
  app/src/ui/branches/branch-list-item.tsx
  app/src/ui/changes/changes-list.tsx
  app/src/ui/changes/commit-message.tsx
  app/src/ui/changes/no-changes.tsx
  app/src/ui/index.tsx
  app/src/ui/lib/context-menu.ts
  app/src/ui/repositories-list/repository-list-item.tsx
  app/static/error.html
  app/static/index.html
  app/test/unit/git/status-test.ts
  package.json
  script/prettier.ts
  yarn.lock
Labels: infrastructure, ready-for-review

#6149 additional status conflict testing
  app/src/models/conflicts.ts
  app/test/helpers/repositories.ts
  app/test/unit/git/diff-check-test.ts
  app/test/unit/git/status-test.ts
Labels: infrastructure, ready-for-review, tech-debt

#6030 Add support for Visual SlickEdit as an external editor
  app/src/lib/editors/darwin.ts
  app/src/lib/editors/linux.ts
  app/src/lib/editors/win32.ts
  docs/technical/editor-integration.md
Labels: integrations, ready-for-review

#6206 fix tslint for vscode
  .vscode/extensions.json
  package.json
  tsconfig.json
  yarn.lock
Labels: infrastructure, ready-for-review

#5822 "Go to Summary" Action
  app/src/lib/app-state.ts
  app/src/lib/dispatcher/dispatcher.ts
  app/src/lib/menu-update.ts
  app/src/lib/stores/app-store.ts
  app/src/main-process/menu/build-default-menu.ts
  app/src/main-process/menu/menu-event.ts
  app/src/main-process/menu/menu-ids.ts
  app/src/ui/app.tsx
  app/src/ui/changes/changes-list.tsx
  app/src/ui/changes/commit-message.tsx
  app/src/ui/changes/sidebar.tsx
  app/src/ui/repository.tsx
Labels: ready-for-review

#6190 simplify LFS check to avoid string encoding issues
  app/src/lib/git/lfs.ts
  app/test/unit/git/lfs-test.ts
Labels: ready-for-review

#6187 indicate that we expect this error to occur to avoid it polluting the dev tools
  app/src/lib/git/merge.ts
  app/src/lib/stores/git-store.ts
Labels: ready-for-review, tech-debt

#6111 upgrade most eslint dependencies to latest version
  package.json
  yarn.lock
Labels: infrastructure, ready-for-review

#6205 convert AppFileStatus into a first-class shape
  app/src/lib/get-old-path.ts
  app/src/lib/git/apply.ts
  app/src/lib/git/diff.ts
  app/src/lib/git/log.ts
  app/src/lib/git/status.ts
  app/src/lib/git/update-index.ts
  app/src/lib/patch-formatter.ts
  app/src/lib/stores/git-store.ts
  app/src/models/status.ts
  app/src/ui/app.tsx
  app/src/ui/changes/changed-file-details.tsx
  app/src/ui/changes/changed-file.tsx
  app/src/ui/changes/changes-list.tsx
  app/src/ui/changes/changes.tsx
  app/src/ui/diff/index.tsx
  app/src/ui/diff/syntax-highlighting/index.ts
  app/src/ui/diff/text-diff.tsx
  app/src/ui/history/file-list.tsx
  app/src/ui/lib/path-label.tsx
  app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx
  app/test/unit/git-store-test.ts
  app/test/unit/git/commit-test.ts
  app/test/unit/git/diff-test.ts
  app/test/unit/git/log-test.ts
  app/test/unit/git/status-test.ts
  app/test/unit/patch-formatter-test.ts
  app/test/unit/repository-state-cache-test.ts
Labels: ready-for-review, tech-debt, time-sensitive

#6150 codecov granularity
  .codecov.yml
Labels: infrastructure, ready-for-review

#6243 :fire: InAppReleaseNotes
  app/src/lib/feature-flag.ts
  app/src/ui/app.tsx
  app/src/ui/updates/update-available.tsx
Labels: ready-for-review, tech-debt

#6242 extract functions living under the models folder
  app/src/lib/status.ts
  app/src/models/status.ts
  app/src/ui/changes/changed-file-details.tsx
  app/src/ui/changes/changed-file.tsx
  app/src/ui/history/file-list.tsx
  app/src/ui/octicons/index.ts
  app/src/ui/octicons/status.ts
Labels: ready-for-review, tech-debt

#6244 Update roadmap post-release
  docs/process/roadmap.md
Labels: docs, ready-for-review

#6234 Hide overflowed content
  app/styles/ui/changes/_commit-message.scss
Labels: ready-for-review

#6181 Win32 LaunchEditor use Shell for .CMD files
  app/src/lib/editors/found-editor.ts
  app/src/lib/editors/launch.ts
  app/src/lib/editors/shared.ts
  app/src/lib/editors/win32.ts
  docs/technical/editor-integration.md
Labels: ready-for-review, windows

#6239 Focus branch selector when comparing to branch from menu
  app/src/ui/history/compare.tsx
Labels: ready-for-review

#6088 Add Branch List and Pull Request List filter text persistence
  app/src/lib/app-state.ts
  app/src/lib/dispatcher/dispatcher.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/repository-state-cache.ts
  app/src/ui/branches/branches-container.tsx
  app/src/ui/toolbar/branch-dropdown.tsx
Labels: ready-for-review

#6257 Fixed broken maintainers line in Teams doc
  docs/process/teams.md
Labels: docs, ready-for-review

#6231 Add workaround to allow toggling between diff modes
  app/styles/ui/_diff.scss
Labels: ready-for-review

#6238 Updating usage metrics to connect to GitHub usage
  app/src/lib/dispatcher/dispatcher.ts
  app/src/lib/stats/index.ts
  app/src/lib/stats/stats-store.ts
  app/src/lib/stats/usage-stats-change.ts
  app/src/lib/stores/app-store.ts
  app/src/models/popup.ts
  app/src/ui/app.tsx
  app/src/ui/preferences/advanced.tsx
  app/src/ui/preferences/preferences.tsx
  app/src/ui/usage-stats-change/index.ts
  app/src/ui/usage-stats-change/usage-stats-change.tsx
  app/src/ui/welcome/usage-opt-out.tsx
  app/styles/ui/_dialog.scss
  app/styles/ui/dialogs/_usage-reporting.scss
Labels: ready-for-review

#6069 Bump to Electron 2.0.13
  app/.npmrc
  package.json
  yarn.lock
Labels: ready-for-review

#6258 Gets rid of some console logging in one of our components
  app/src/ui/acknowledgements/acknowledgements.tsx
Labels: ready-for-review, tech-debt

#6251 :fire: Purge enableRepoInfoIndicators
  app/src/lib/feature-flag.ts
  app/src/lib/stores/app-store.ts
  app/src/ui/repositories-list/repositories-list.tsx
Labels: ready-for-review, tech-debt

#6095 first pass at a doc about upgrading dependencies
  docs/contributing/upgrading-dependencies.md
Labels: docs, ready-for-review

#6204 pull eslint scripts into package.json
  .eslintrc.yml
  docs/contributing/linting.md
  package.json
  script/eslint.ts
Labels: infrastructure, ready-for-review

#6250 :fire: Purge EnableMergeConflictDetection
  app/src/lib/feature-flag.ts
  app/src/lib/stores/app-store.ts
  app/src/ui/history/compare.tsx
  app/src/ui/merge-branch/merge.tsx
Labels: ready-for-review, tech-debt

#6252 simplify travis config to avoid unnecessary work
  .travis.yml
Labels: infrastructure, ready-for-review

#6262 Fixed react devtools warning about unique keys for new MergeConflicts…
  app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx
Labels: ready-for-review, tech-debt

#6236 Dismiss dialog at escape key hit
  app/src/ui/dialog/dialog.tsx
Labels: ready-for-review

#6104 ensure creating branch with detached HEAD does not revert to default branch
  app/src/lib/create-branch.ts
  app/src/models/branch.ts
  app/src/ui/create-branch/create-branch-dialog.tsx
  app/test/unit/create-branch-test.ts
Labels: ready-for-review

#6215 add previous value to ping payload to differentiate between scenarios
  app/src/lib/stats/stats-store.ts
Labels: ready-for-review

#6214 unify conflicted state into a more meaningful model
  app/src/lib/git/binary-files.ts
  app/src/lib/git/status.ts
  app/src/lib/patch-formatter.ts
  app/src/lib/status-parser.ts
  app/src/lib/status.ts
  app/src/models/conflicts.ts
  app/src/models/status.ts
  app/src/ui/app.tsx
  app/src/ui/changes/changed-file-details.tsx
  app/src/ui/changes/changed-file.tsx
  app/src/ui/history/file-list.tsx
  app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx
  app/src/ui/octicons/status.ts
  app/test/unit/git/commit-test.ts
  app/test/unit/git/status-test.ts
Labels: ready-for-review, tech-debt

#6220 added focus on close button to license modal
  app/src/ui/acknowledgements/acknowledgements.tsx
Labels: ready-for-review

#6279 Make list scroll to selected item on mount
  app/src/ui/lib/list/list.tsx
Labels: ready-for-review

#6255 Adding tasks to publish test results to AzurePipelines
  app/test/mochareporters.json
  azure-pipelines.yml
  jest.config.js
  package.json
Labels: infrastructure, ready-for-review

#6307 Update yarn.lock
  yarn.lock
Labels: ready-for-review, tech-debt

#6270 update embedded Git to 2.19.2
  app/package.json
  app/yarn.lock
Labels: ready-for-review

#6142 add experimental support for v2 of the Git wire protocol
  app/src/lib/feature-flag.ts
  app/src/lib/git/branch.ts
  app/src/lib/git/checkout.ts
  app/src/lib/git/clone.ts
  app/src/lib/git/core.ts
  app/src/lib/git/fetch.ts
  app/src/lib/git/pull.ts
  app/src/lib/git/push.ts
  app/src/lib/git/revert.ts
Labels: performance, ready-for-review

#6125 refactoring to extract and test more AppStore functionality
  app/src/lib/stats/index.ts
  app/src/lib/stats/stats-store.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/updates/changes-state.ts
  app/src/models/diff/diff-selection.ts
  app/test/unit/stores/updates/changes-state-helper.ts
  app/test/unit/stores/updates/update-changed-files-test.ts
  app/test/unit/stores/updates/update-conflict-state-test.ts
  docs/technical/adding-tests.md
Labels: ready-for-review, tech-debt

#6315 Update .gitignore to ignore junit.xml
  .gitignore
Labels: infrastructure, ready-for-review
