Repository desktop/desktop, pull requests merged in 2018-08, with the labels that each got.

#5300 check the on-disk state before performing Git operations
  app/src/lib/dispatcher/dispatcher.ts
  app/src/lib/stores/app-store.ts
Labels: ready-for-review

#5313 draft for next release
  app/package.json
  app/src/lib/stores/app-store.ts
  changelog.json
Labels: ready-for-review

#5317 await each refresh operation inside the loop
  app/src/lib/stores/app-store.ts
Labels: ready-for-review

#5316 invalidate the cache if a repository is now missing
  app/src/lib/stores/app-store.ts
Labels: ready-for-review

#5314 Adds repo information to error message for fetch failure
  app/src/lib/stores/helpers/background-fetcher.ts
Labels: ready-for-review

#5263 update changelog generation for production release
  script/changelog/parser.ts
  script/draft-release/run.ts
Labels: infrastructure, ready-for-review

#5251 we do not need this Appveyor workaround any more
  app/src/ui/lib/update-store.ts
Labels: infrastructure, ready-for-review

#5272 Migrate to CircleCI 2.0
  .circleci/config.yml
  app/package.json
  changelog.json
  circle.yml
  script/setup-macos-keychain
Labels: ready-for-review

#5322 tidy up custom Electron declarations
  app/src/lib/globals.d.ts
Labels: infrastructure, ready-for-review

#5319 upgrade eslint, tslint and dependencies
  package.json
  yarn.lock
Labels: infrastructure, ready-for-review

#5204 bump legal-eagle to version which supports Node 10
  package.json
  yarn.lock
Labels: infrastructure, ready-for-review

#5339 clarify setup instructions on doc
  .github/CONTRIBUTING.md
Labels: ready-for-review

#5333 update the ahead/behind info for the current branch after a fetch
  app/src/lib/stores/git-store.ts
Labels: ready-for-review

#5341 prevent user from toggling files when commit is in progress
  app/src/ui/changes/changed-file.tsx
  app/src/ui/changes/changes-list.tsx
Labels: ready-for-review

#5332 measure how long the background work takes on each run
  app/src/lib/stores/app-store.ts
Labels: ready-for-review

#5350 renamed the file to drop the preceding dashes
  .github/ISSUE_TEMPLATE/problem-to-raise.md
Labels: infrastructure, ready-for-review

#5338 Update the node version noted in setup.md
  docs/contributing/setup.md
Labels: ready-for-review

#5352 upgrade ts-node to latest version
  app/test/globals.ts
  package.json
  yarn.lock
Labels: infrastructure, ready-for-review

#5327 Adds a function to get repo name
  app/src/lib/stores/app-store.ts
  app/src/models/repository.ts
  app/src/ui/branches/branches-container.tsx
  app/test/unit/name-of-test.ts
Labels: infrastructure, ready-for-review

#5359 run all the tests
  app/test/unit/name-of-test.ts
Labels: infrastructure, ready-for-review

#5361 bump electron-builder to latest version
  package.json
  yarn.lock
Labels: infrastructure, ready-for-review

#5320 Check API for updates before fetching
  app/src/lib/api.ts
  app/src/lib/infer-last-push-for-repository.ts
  app/src/lib/stores/app-store.ts
  app/test/unit/repositories-clone-grouping-test.ts
  app/test/unit/repositories-store-test.ts
Labels: ready-for-review

#5326 cache new tip for fresh repositories
  app/src/lib/stores/git-store.ts
Labels: ready-for-review

#5182 Upgrade Prettier to 1.14 (WIP)
  .circleci/config.yml
  .eslintrc.yml
  .github/config.yml
  .github/lock.yml
  .github/no-response.yml
  .prettierrc.yml
  .travis.yml
  app/src/lib/fuzzy-find.ts
  app/src/ui/clone-repository/clone-generic-repository.tsx
  app/src/ui/create-branch/create-branch-dialog.tsx
  app/src/ui/delete-branch/delete-branch-dialog.tsx
  app/src/ui/diff/image-diffs/two-up.tsx
  app/src/ui/discard-changes/discard-changes-dialog.tsx
  app/src/ui/history/compare.tsx
  app/src/ui/history/merge-call-to-action.tsx
  app/src/ui/notification/new-commits-banner.tsx
  app/src/ui/remove-repository/confirm-remove-repository.tsx
  app/src/ui/terms-and-conditions/terms-and-conditions.tsx
  app/src/ui/updates/update-available.tsx
  appveyor.yml
  package.json
  script/electron-builder-linux.yml
  script/prettier.ts
  vsts.yml
  yarn.lock
Labels: infrastructure

#5335 upgrade CI providers to local yarn usage
  .travis.yml
  .yarnrc
  app/.yarnrc
  package.json
  script/post-install.ts
  vendor/yarn-1.9.2.js
  vsts.yml
  yarn.lock
Labels: infrastructure, ready-for-review

#5348 Fix for file menu pane cut off on Windows
  app/styles/ui/_app-menu.scss
Labels: ready-for-review

#5173 workaround for maximise issue on Windows
  app/src/main-process/app-window.ts
Labels: Windows, ready-for-review

#5363 defer initial refresh of repository indicators, enable this again for everyone
  app/src/lib/stores/app-store.ts
  app/src/ui/app.tsx
Labels: ready-for-review

#5246 swap out fatalError for logged warning when OAuth callback reused
  app/src/lib/dispatcher/dispatcher.ts
  app/src/lib/oauth.ts
Labels: infrastructure, ready-for-review

#5392 experimenting with tuning ts-node usage to speed up tests
  appveyor.yml
  script/test-appveyor.bat
  script/unit-tests.ts
Labels: infrastructure, ready-for-review

#5401 Delete 1.2 Section as it has been Released
  docs/process/roadmap.md
Labels: ready-for-review

#5407 fix CircleCI build so that it correctly reports lint errors
  .circleci/config.yml
Labels: infrastructure, ready-for-review

#5364 bump yarn again
  .yarnrc
  app/.yarnrc
  docs/contributing/working-with-packages.md
  vendor/yarn-1.9.4.js
Labels: infrastructure, ready-for-review

#5408 draft release notes for next update
  app/package.json
  changelog.json
Labels: infrastructure, ready-for-review

#5412 Update README and CoC
  CODE_OF_CONDUCT.md
  README.md
Labels: infrastructure

#5421 this link should point to Desktop, not Central
  docs/process/releasing-updates.md
Labels: infrastructure, ready-for-review

#5423 bump beta to ensure it's ahead of production
  app/package.json
  changelog.json
Labels: infrastructure, ready-for-review

#5420 Support VSCode user scope installation
  app/src/lib/editors/win32.ts
Labels: ready-for-review

#5425 clarify section about error reporting after deployment
  docs/process/releasing-updates.md
Labels: infrastructure, ready-for-review

#5488 bump beta to 1.3.5-beta0
  app/package.json
  changelog.json
Labels: infrastructure, ready-for-review

#5371 Disable delete button while deleting a branch
  app/src/lib/stores/app-store.ts
  app/src/ui/delete-branch/delete-branch-dialog.tsx
Labels: ready-for-review

#5380 Added error for publishing repo w/ non-existent org
  app/src/lib/api.ts
Labels: ready-for-review

#5471 Don't hide commit details when commit summary description is expanded.
  app/styles/ui/history/_history.scss
Labels: ready-for-review

#5485 Adds documentation for teams
  docs/process/teams.md
Labels: docs, infrastructure, ready-for-review

#5505 use the RichText component when rendering release notes
  app/src/lib/text-token-parser.ts
  app/src/ui/app.tsx
  app/src/ui/release-notes/release-notes-dialog.tsx
  app/test/unit/text-token-parser-test.ts
Labels: ready-for-review

#5427 Use jest for unit tests
  .gitignore
  app/src/lib/__mocks__/window-state.ts
  app/test/.eslintrc.yml
  app/test/__mocks__/electron.ts
  app/test/globals.ts
  app/test/setup-test-framework.ts
  app/test/unit-test-env.ts
  app/test/unit/app-store-test.ts
  app/yarn.lock
  jest.config.js
  package.json
  script/unit-tests.ts
  yarn.lock
Labels: ready-for-review

#5497 Revert workaround for tooltip issue on Windows, closes #3362
  app/src/ui/window/window-controls.tsx
Labels: ready-for-review
