Repository desktop/desktop, pull requests merged in 2018-05, with the labels that each got.

#4568 Fixed a minor typo in the testing manifest
  docs/process/testing.md
Labels: ready-for-review

#4562 Cleanup debug script
  package.json
  script/debug
Labels: infrastructure, ready-for-review

#4566 Prevent Octicon from shrinking in rename dialog
  app/styles/ui/_octicons.scss
  app/styles/ui/_ref.scss
Labels: ready-for-review

#4563 Disable textbox if there are no branches to compare
  app/src/ui/history/compare.tsx
Labels: ready-for-review

#4583 Fix background color behind octicon when textfield is disabled
  app/src/ui/lib/fancy-text-box.tsx
  app/styles/ui/_fancy-text-box.scss
Labels: ready-for-review

#4586 actually get the styling fix for the disabled compare branch selector in
  app/src/ui/lib/fancy-text-box.tsx
  app/styles/ui/_fancy-text-box.scss
Labels: ready-for-review

#4531 Wire up RBB analytics
  app/src/lib/dispatcher/dispatcher.ts
  app/src/lib/stats/stats-store.ts
  app/src/lib/stores/app-store.ts
  app/src/ui/app.tsx
  app/src/ui/history/compare.tsx
Labels: ready-for-review

#4516 asRange tidy up
  app/src/lib/comparison-cache.ts
  app/src/lib/git/rev-list.ts
  app/src/lib/stores/git-store.ts
  app/src/lib/stores/helpers/ahead-behind-updater.ts
  app/src/ui/merge-branch/merge.tsx
Labels: ready-for-review

#4517 add compare value into cache
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/helpers/ahead-behind-updater.ts
Labels: ready-for-review

#4595 Updates Desktop 1.1.2-beta5 change log
  app/package.json
  changelog.json
Labels: ready-for-review

#4618 update access key to address constraint enforced at dev time
  app/src/main-process/menu/build-default-menu.ts
Labels: ready-for-review

#4620 ensure FocusContainer also has key set
  app/src/ui/lib/list/list.tsx
Labels: ready-for-review

#4610 include the account login when emitting this message
  app/src/lib/stores/accounts-store.ts
Labels: infrastructure, ready-for-review

#4621 extract some Win32-specific code for future reuse
  app/src/lib/process/win32.ts
  app/src/main-process/squirrel-updater.ts
Labels: infrastructure, ready-for-review

#4532 Add MacVim as a supported external editor for macOS
  app/src/lib/editors/darwin.ts
  docs/technical/editor-integration.md
Labels: ready-for-review

#4632 bump typescript to latest stable release
  package.json
  yarn.lock
Labels: infrastructure, ready-for-review

#4431 upgrade fs-extra by a few major versions
  app/package.json
  app/src/lib/editors/darwin.ts
  app/src/lib/editors/launch.ts
  app/src/lib/editors/linux.ts
  app/src/lib/editors/win32.ts
  app/src/lib/file-system.ts
  app/src/lib/git/description.ts
  app/src/lib/git/index.ts
  app/src/lib/git/submodule.ts
  app/src/lib/progress/lfs.ts
  app/src/lib/shells/linux.ts
  app/src/lib/shells/shared.ts
  app/src/lib/shells/win32.ts
  app/src/lib/tailer.ts
  app/src/main-process/log.ts
  app/src/main-process/menu/build-default-menu.ts
  app/src/main-process/squirrel-updater.ts
  app/src/ui/add-repository/create-repository.tsx
  app/src/ui/add-repository/git-attributes.ts
  app/src/ui/add-repository/gitignores.ts
  app/src/ui/add-repository/licenses.ts
  app/src/ui/add-repository/write-default-readme.ts
  app/src/ui/clone-repository/clone-repository.tsx
  app/src/ui/history/file-list.tsx
  app/src/ui/publish-repository/publish.tsx
  app/test/helpers/repositories.ts
  app/test/unit/app-store-test.ts
  app/test/unit/git-store-test.ts
  app/test/unit/git/commit-test.ts
  app/test/unit/git/config-test.ts
  app/test/unit/git/core-test.ts
  app/test/unit/git/description-test.ts
  app/test/unit/git/diff-test.ts
  app/test/unit/git/for-each-ref-test.ts
  app/test/unit/git/git-attributes-test.ts
  app/test/unit/git/log-test.ts
  app/test/unit/git/reflog-test.ts
  app/test/unit/git/remote-test.ts
  app/test/unit/git/reset-test.ts
  app/test/unit/git/rev-parse-test.ts
  app/test/unit/git/status-test.ts
  app/test/unit/git/submodule-test.ts
  app/test/unit/patch-formatter-test.ts
  app/test/unit/repository-settings-store-test.ts
  app/test/unit/validated-repository-path-test.ts
  app/yarn.lock
  changelog.json
  package.json
  script/build.ts
  yarn.lock
Labels: infrastructure, ready-for-review

#4648 Fix spelling error on issue template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: infrastructure, ready-for-review

#4650 Update arm64 instructions
  docs/contributing/setup.md
Labels: infrastructure, ready-for-review

#4513 Automatically add valid and non-existing repository when executed from command line
  app/src/lib/dispatcher/dispatcher.ts
Labels: ready-for-review

#4521 cleanup unnecessary hooks in test repo
  app/test/fixtures/submodule-basic-setup/_git/modules/foo/submodule/hooks/applypatch-msg.sample
  app/test/fixtures/submodule-basic-setup/_git/modules/foo/submodule/hooks/commit-msg.sample
  app/test/fixtures/submodule-basic-setup/_git/modules/foo/submodule/hooks/post-update.sample
  app/test/fixtures/submodule-basic-setup/_git/modules/foo/submodule/hooks/pre-applypatch.sample
  app/test/fixtures/submodule-basic-setup/_git/modules/foo/submodule/hooks/pre-commit.sample
  app/test/fixtures/submodule-basic-setup/_git/modules/foo/submodule/hooks/pre-push.sample
  app/test/fixtures/submodule-basic-setup/_git/modules/foo/submodule/hooks/pre-rebase.sample
  app/test/fixtures/submodule-basic-setup/_git/modules/foo/submodule/hooks/pre-receive.sample
  app/test/fixtures/submodule-basic-setup/_git/modules/foo/submodule/hooks/prepare-commit-msg.sample
  app/test/fixtures/submodule-basic-setup/_git/modules/foo/submodule/hooks/update.sample
Labels: infrastructure, ready-for-review

#4619 Check if git is found under PATH on Linux
  app/src/lib/is-git-on-path.ts
Labels: ready-for-review

#4631 use more granular links when documenting to open a new issue
  .github/CONTRIBUTING.md
  README.md
  app/src/main-process/menu/build-default-menu.ts
  docs/known-issues.md
Labels: infrastructure, ready-for-review

#4640 keep the branch name readable in the compare tab
  app/styles/ui/history/_history.scss
Labels: ready-for-review

#4674 "Zero Is Not False" And Other Keyboard Adventures
  app/src/ui/lib/filter-list.tsx
  app/src/ui/lib/list/selection.ts
  app/test/unit/list-selection-test.ts
Labels: ready-for-review

#4692 revert tab from Changes to History
  app/src/ui/repository.tsx
Labels: ready-for-review

#4691 add target branch to merge call-to-action
  app/src/ui/history/compare.tsx
Labels: ready-for-review

#4694 redirect to commit tab when merge conflicts found
  app/src/lib/app-state.ts
  app/src/lib/dispatcher/error-handlers.ts
  app/src/ui/app.tsx
  app/src/ui/index.tsx
  app/src/ui/merge-conflicts/index.ts
  app/src/ui/merge-conflicts/merge-conflicts-warning.tsx
Labels: ready-for-review

#4693 Rename to `compare to branch` menu option to `show history`
  app/src/lib/menu-update.ts
  app/src/main-process/menu/build-default-menu.ts
  app/src/main-process/menu/menu-event.ts
  app/src/main-process/menu/menu-ids.ts
  app/src/ui/app.tsx
Labels: ready-for-review

#4704 add new beta entries for changelog
  changelog.json
Labels: ready-for-review

#4705 bring back the hover styles for the app menu
  app/styles/ui/window/_app-menu-bar.scss
Labels: Windows, ready-for-review

#4702 Adds compare to branch menu item
  app/src/lib/app-state.ts
  app/src/lib/menu-update.ts
  app/src/lib/stores/app-store.ts
  app/src/main-process/menu/build-default-menu.ts
  app/src/main-process/menu/menu-event.ts
  app/src/main-process/menu/menu-ids.ts
  app/src/ui/app.tsx
  app/src/ui/history/compare.tsx
  app/src/ui/merge-conflicts/merge-conflicts-warning.tsx
  app/src/ui/repository.tsx
  app/test/unit/app-store-test.ts
Labels: ready-for-review

#4729 move new error handler behind a feature flag
  app/src/ui/index.tsx
Labels: ready-for-review

#4714 provide this.canSelectRow here to ensure first valid branch is selected
  app/src/ui/lib/filter-list.tsx
Labels: ready-for-review

#4707 blur branch selector when search text is cleared
  app/src/ui/history/compare.tsx
  app/src/ui/lib/fancy-text-box.tsx
  app/src/ui/lib/text-box.tsx
Labels: ready-for-review

#4713 jump to compare mode from the branch selector
  app/src/ui/branches/branch-list-item.tsx
  app/src/ui/branches/branch-renderer.tsx
  app/src/ui/branches/branches-container.tsx
  app/src/ui/history/compare.tsx
  app/styles/ui/_branches.scss
Labels: ready-for-review

#4747 The only constant is change
  app/src/lib/menu-update.ts
  app/src/main-process/menu/build-default-menu.ts
  app/src/main-process/menu/menu-event.ts
  app/src/main-process/menu/menu-ids.ts
  app/src/ui/app.tsx
  app/src/ui/repository.tsx
Labels: ready-for-review

#4735 Revert "jump to compare mode from the branch selector"
  app/src/ui/branches/branch-list-item.tsx
  app/src/ui/branches/branch-renderer.tsx
  app/src/ui/branches/branches-container.tsx
  app/src/ui/history/compare.tsx
  app/styles/ui/_branches.scss
Labels: ready-for-review

#4743 ensure menu actions put compare tab in correct state
  app/src/lib/app-state.ts
  app/src/ui/app.tsx
  app/src/ui/history/compare.tsx
  app/src/ui/repository.tsx
Labels: ready-for-review

#4748 1.2.0 changelog
  app/package.json
  changelog.json
Labels: ready-for-review

#4759 Bump version for next beta
  app/package.json
  changelog.json
Labels: ready-for-review

#4601 The Great Webpack Migration
  app/webpack.common.js
  app/webpack.development.js
  app/webpack.production.js
  changelog.json
  package.json
  yarn.lock
Labels: infrastructure, ready-for-review

#4760 Document when to use beta0
  docs/process/releasing-updates.md
Labels: ready-for-review

#4771 Removes unused feature flag
  app/src/lib/feature-flag.ts
Labels: ready-for-review

#4653 Add filtering of Pull Requests by pull request number and author
  app/src/lib/fuzzy-find.ts
  app/src/ui/branches/branch-list-item.tsx
  app/src/ui/branches/branch-list.tsx
  app/src/ui/branches/branch-renderer.tsx
  app/src/ui/branches/branches-container.tsx
  app/src/ui/branches/group-branches.ts
  app/src/ui/branches/pull-request-list-item.tsx
  app/src/ui/branches/pull-request-list.tsx
  app/src/ui/branches/pull-requests-loading.tsx
  app/src/ui/clone-repository/clone-github-repository.tsx
  app/src/ui/clone-repository/group-repositories.ts
  app/src/ui/history/compare-branch-list-item.tsx
  app/src/ui/history/compare.tsx
  app/src/ui/lib/filter-list.tsx
  app/src/ui/merge-branch/merge.tsx
  app/src/ui/repositories-list/group-repositories.ts
  app/src/ui/repositories-list/repositories-list.tsx
  app/src/ui/repositories-list/repository-list-item.tsx
  app/test/unit/fuzzy-find-test.ts
  app/test/unit/repositories-list-grouping-test.ts
Labels: ready-for-review

#4542 Decreased the max line length limit
  app/src/lib/git/diff.ts
Labels: ready-for-review

#4780 SCSS Cleanup and centralization of hard coded values
  app/styles/_variables.scss
  app/styles/mixins/_textboxish.scss
  app/styles/ui/_codemirror.scss
  app/styles/ui/_dialog.scss
  app/styles/ui/_diff.scss
  app/styles/ui/_fancy-text-box.scss
  app/styles/ui/_foldout.scss
  app/styles/ui/_repository-list.scss
  app/styles/ui/changes/_commit-message.scss
  app/styles/ui/toolbar/_toolbar.scss
Labels: ready-for-review

#4798 Correct the path to app-store.ts file
  docs/contributing/styleguide.md
Labels: infrastructure, ready-for-review

#4763 VSTS tweaks
  README.md
  vsts.yml
Labels: infrastructure, ready-for-review

#4652 actually get tslint working in the CI builds
  package.json
Labels: infrastructure, ready-for-review

#4811 cut a new release
  app/package.json
  changelog.json
Labels: ready-for-review

#4791 bump embedded Git to latest version
  app/package.json
  app/src/lib/git/core.ts
  app/yarn.lock
  changelog.json
Labels: ready-for-review

#4814 promote to production
  app/package.json
  changelog.json
Labels: ready-for-review

#4810 SCSS refactors, move more constants into variables
  app/src/ui/diff/index.tsx
  app/styles/_variables.scss
  app/styles/ui/_branches.scss
  app/styles/ui/_diff.scss
  app/styles/ui/changes/_changes-view.scss
  app/styles/ui/history/_commit-summary.scss
  app/styles/ui/history/_history.scss
Labels: ready-for-review

#4805 missing chai import
  app/test/unit/app-store-test.ts
Labels: infrastructure, ready-for-review

#4795 update Prettier to 1.13.0
  app/src/lib/shells/win32.ts
  app/src/lib/stores/app-store.ts
  app/src/main-process/menu/build-default-menu.ts
  app/src/ui/branches/branch-list-item.tsx
  app/src/ui/changes/changes-list.tsx
  app/src/ui/changes/commit-message.tsx
  app/src/ui/changes/no-changes.tsx
  app/src/ui/diff/image-diffs/two-up.tsx
  app/src/ui/lib/context-menu.ts
  app/src/ui/repositories-list/repository-list-item.tsx
  app/test/unit/progress/clone-test.ts
  package.json
  script/prettier.ts
  yarn.lock
Labels: infrastructure, ready-for-review

#4751 lift up compare form state
  app/src/lib/app-state.ts
  app/src/lib/dispatcher/dispatcher.ts
  app/src/lib/stores/app-store.ts
  app/src/ui/app.tsx
  app/src/ui/history/compare.tsx
  app/src/ui/merge-conflicts/merge-conflicts-warning.tsx
  app/src/ui/repository.tsx
  app/test/unit/app-store-test.ts
Labels: ready-for-review
