Repository desktop/desktop, pull requests merged in 2018-09, with the labels that each got.

#5434 Start blocking the ability to add local bare repositories
  app/src/lib/git/rev-parse.ts
  app/src/ui/add-repository/add-existing-repository.tsx
  app/test/unit/git/rev-parse-test.ts
Labels: ready-for-review

#5520 preparing changelog for next beta
  app/package.json
  changelog.json
Labels: infrastructure, ready-for-review

#5514 polish merge status
  app/src/lib/promise.ts
  app/src/lib/stores/app-store.ts
  app/src/ui/history/merge-call-to-action-with-conflicts.tsx
  app/src/ui/history/merge-status-header.tsx
  app/src/ui/merge-branch/merge.tsx
  app/styles/_ui.scss
  app/styles/ui/_merge-status.scss
  app/styles/ui/dialogs/_merge.scss
  app/styles/ui/history/_history.scss
  app/test/unit/promise-with-timeout-test.ts
Labels: ready-for-review

#5545 mute the flaky test because everything is terrible
  app/test/unit/app-store-test.ts
Labels: infrastructure, ready-for-review

#5376 we don't need getStatus to always lock the index
  app/src/lib/feature-flag.ts
  app/src/lib/git/status.ts
Labels: ready-for-review

#5422 Clear Displayed Publish Repository Error on change of tab
  app/src/ui/publish-repository/publish.tsx
Labels: ready-for-review

#5500 Disable affected menu items when on detached HEAD
  app/src/lib/menu-update.ts
Labels: ready-for-review

#5388 bump dugite to 2.18.0 and related packaging improvements
  app/package.json
  app/src/lib/git/for-each-ref.ts
  app/src/lib/git/remote.ts
  app/test/unit/git/status-test.ts
  app/yarn.lock
Labels: infrastructure, ready-for-review

#5546 bump for next version
  app/package.json
  changelog.json
Labels: ready-for-review

#5528 fix 10k file test on appveyor
  app/test/unit/git/status-test.ts
  package.json
Labels: ready-for-review

#5375 avoid double checkout when opening a PR in Desktop
  app/src/lib/dispatcher/dispatcher.ts
Labels: ready-for-review

#5399 avoid using getDefaultRemote where possible
  app/src/lib/stores/app-store.ts
Labels: infrastructure, ready-for-review

#5551 Fix ordering of branches
  app/src/ui/merge-branch/merge.tsx
Labels: ready-for-review

#5200 validate hostname when cloning a URL
  app/src/lib/find-account.ts
  app/src/lib/remote-parsing.ts
  app/test/unit/find-account-test.ts
Labels: ready-for-review

#5362 Add document for metrics we collect
  docs/process/metrics.md
Labels: meta, ready-for-review

#5554 MergeCallToActionWithConflicts display logic refactor
  app/src/ui/history/merge-call-to-action-with-conflicts.tsx
Labels: ready-for-review

#5556 Document merge hint metrics
  docs/process/metrics.md
Labels: ready-for-review

#5552 release notes dialog spacing tweaks
  app/src/ui/release-notes/release-notes-dialog.tsx
  app/styles/ui/dialogs/_release-notes.scss
Labels: ready-for-review

#3601 in-app release notes
  app/src/lib/app-state.ts
  app/src/lib/feature-flag.ts
  app/src/lib/release-notes.ts
  app/src/lib/text-token-parser.ts
  app/src/models/release-notes.ts
  app/src/ui/app.tsx
  app/src/ui/dialog/header.tsx
  app/src/ui/lib/update-store.ts
  app/src/ui/release-notes/index.ts
  app/src/ui/release-notes/release-notes-dialog.tsx
  app/src/ui/updates/update-available.tsx
  app/static/common/release-note-header-left.svg
  app/static/common/release-note-header-right.svg
  app/styles/ui/_dialog.scss
  app/styles/ui/dialogs/_release-notes.scss
  app/test/unit/release-notes-test.ts
  app/test/unit/text-token-parser-test.ts
Labels: ready-for-review

#5563 ensure the old layout is fine for users until they see the new merge hint
  app/src/ui/history/merge-call-to-action.tsx
  app/styles/ui/history/_history.scss
Labels: ready-for-review

#5550 add analytics for how user leverages merge hint to merge
  app/src/lib/dispatcher/dispatcher.ts
  app/src/lib/stats/stats-database.ts
  app/src/lib/stats/stats-store.ts
  app/src/lib/stores/app-store.ts
  app/src/ui/app.tsx
  app/src/ui/history/merge-call-to-action-with-conflicts.tsx
  app/src/ui/history/merge-call-to-action.tsx
  app/src/ui/merge-branch/merge.tsx
Labels: infrastructure, ready-for-review

#5495 display merge conflict hint before doing the merge
  app/src/lib/app-state.ts
  app/src/lib/dispatcher/dispatcher.ts
  app/src/lib/feature-flag.ts
  app/src/lib/git/merge.ts
  app/src/lib/merge-tree-parser.ts
  app/src/lib/promise.ts
  app/src/lib/stats/stats-database.ts
  app/src/lib/stats/stats-store.ts
  app/src/lib/stores/app-store.ts
  app/src/models/merge.ts
  app/src/ui/app.tsx
  app/src/ui/history/compare.tsx
  app/src/ui/history/merge-call-to-action-with-conflicts.tsx
  app/src/ui/history/merge-call-to-action.tsx
  app/src/ui/history/merge-status-header.tsx
  app/src/ui/merge-branch/merge.tsx
  app/styles/_ui.scss
  app/styles/ui/_merge-status.scss
  app/styles/ui/dialogs/_merge.scss
  app/styles/ui/history/_history.scss
  app/test/unit/git/parse-merge-result-test.ts
  app/test/unit/promise-with-timeout-test.ts
Labels: ready-for-review

#5565 the first 1.4.0 beta
  app/package.json
  changelog.json
Labels: infrastructure, ready-for-review

#5562 check the start of the diff line for the conflict marker
  app/src/lib/merge-tree-parser.ts
  app/src/models/merge.ts
  app/test/fixtures/merge-parser/desktop/merge-parsing-merge-tree-result-into-offline-mode-y-u-no-work.txt
Labels: ready-for-review

#5478 add explicit dependencies to libcurl and libsecret when packaging for deb and RPM
  script/electron-builder-linux.yml
Labels: infrastructure, ready-for-review

#5586 stop emitting console.time entries when computing merge hint
  app/src/lib/git/merge.ts
Labels: infrastructure, ready-for-review

#5579 specify the old space limit when performing the production build
  package.json
Labels: infrastructure, ready-for-review

#5587 updating VSTS badge in README to reflect name change
  README.md
Labels: infrastructure, ready-for-review

#5581 don't show merge hint when branch can be fast-forwarded
  app/src/ui/history/merge-call-to-action-with-conflicts.tsx
Labels: ready-for-review

#5592 1.4.0-beta3 release notes draft
  app/package.json
  changelog.json
Labels: ready-for-review

#5590 style the dark theme cursor for the co-author input
  app/styles/themes/_dark.scss
Labels: ready-for-review

#5598 use the default scrolling to avoid rendering issue on Windows
  app/styles/ui/dialogs/_release-notes.scss
Labels: ready-for-review

#5599 bugfix for fetchUser not returning email addresses
  app/src/lib/api.ts
  app/src/lib/email.ts
Labels: ready-for-review

#5601 enable upcoming features for all users
  app/src/lib/feature-flag.ts
Labels: infrastructure, ready-for-review

#5607 1.4.0 release notes
  app/package.json
  changelog.json
Labels: infrastructure, ready-for-review

#5615 1.4.1-beta0
  app/package.json
  changelog.json
Labels: infrastructure, ready-for-review

#5597 Adding SSH Tests
  app/test/unit/parse-app-url-test.ts
Labels: infrastructure, ready-for-review

#5577 Remove 1.3 from Roadmap
  docs/process/roadmap.md
Labels: infrastructure, ready-for-review

#5608 Branch names no longer allow starting with a plus
  app/src/lib/sanitize-branch.ts
  app/test/unit/sanitize-test-name-test.ts
Labels: ready-for-review

#5602 use a dedicated phase for linting the source on Azure Pipelines
  vsts.yml
Labels: infrastructure, ready-for-review

#5624 Update yarn version in setup.md
  docs/contributing/setup.md
Labels: docs, infrastructure, ready-for-review

#5623 ignore envrc
  .gitignore
Labels: infrastructure, ready-for-review

#5612 improved error handling when checking the merge base of a missing reference
  app/src/lib/git/merge.ts
  app/test/unit/git/merge-test.ts
Labels: ready-for-review

#5567 upgrade to TypeScript 3.0
  app/src/lib/globals.d.ts
  package.json
  yarn.lock
Labels: infrastructure, ready-for-review

#5564 extract some low-hanging responsibilities from AppStore
  app/src/lib/dispatcher/dispatcher.ts
  app/src/lib/dispatcher/error-handlers.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/github-user-store.ts
  app/src/lib/stores/repository-state-cache.ts
  app/src/models/fetch.ts
  app/src/models/remote.ts
  app/src/ui/app.tsx
  app/src/ui/index.tsx
  app/src/ui/toolbar/push-pull-button.tsx
  app/test/unit/app-store-test.ts
  app/test/unit/app-test.tsx
  app/test/unit/octicon-test.ts
  app/test/unit/repository-state-cache-test.ts
Labels: infrastructure, ready-for-review

#5634 remove getDefaultRemote()
  app/src/lib/git/remote.ts
  app/test/unit/git/remote-test.ts
Labels: infrastructure, ready-for-review

#5660 Update template URLs in CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: docs, infrastructure, ready-for-review

#5648 remove unused component
  app/src/ui/resizable/index.ts
  app/src/ui/resizable/persisting-resizable.tsx
Labels: infrastructure, ready-for-review, tech-debt

#5618 You can now add a co-author to a repo that's added after onboarding experience
  app/src/lib/stores/app-store.ts
  app/src/ui/changes/sidebar.tsx
Labels: ready-for-review

#5646 deprecate RepositorySettingStore
  app/src/lib/dispatcher/dispatcher.ts
  app/src/lib/git/gitignore.ts
  app/src/lib/git/index.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/index.ts
  app/src/lib/stores/repository-settings-store.ts
  app/src/ui/changes/sidebar.tsx
  app/src/ui/repository-settings/repository-settings.tsx
  app/test/unit/git/gitignore-test.ts
  app/test/unit/repository-settings-store-test.ts
Labels: infrastructure, ready-for-review, tech-debt

#5636 codecov reporting
  .circleci/config.yml
  .codecov.yml
  .travis.yml
  appveyor.yml
  jest.config.js
  package.json
  yarn.lock
Labels: infrastructure, ready-for-review

#5674 Add link to usage data page
  docs/process/metrics.md
Labels: docs, ready-for-review

#5643 Add support for Typora editor
  app/src/lib/editors/darwin.ts
  app/src/lib/editors/linux.ts
  app/src/lib/editors/win32.ts
  docs/technical/editor-integration.md
Labels: ready-for-review

#5676 fix codedov threshold
  .codecov.yml
Labels: infrastructure, ready-for-review

#5666 Added support for Cygwin
  app/src/lib/shells/win32.ts
Labels: ready-for-review

#5673 Added compare-to-branch to MenuIDs
  app/src/lib/menu-update.ts
Labels: ready-for-review

#5647 Add positive response if no search results in Clone Repo filter.
  app/src/ui/clone-repository/clone-github-repository.tsx
  app/styles/ui/_filter-list.scss
Labels: ready-for-review

#5613 bump to latest 2.0.x version of Electron
  app/.npmrc
  package.json
  yarn.lock
Labels: infrastructure, ready-for-review

#5576 Never suffix `.git` to URLs cloned via an opened URL
  app/src/lib/parse-app-url.ts
  app/test/unit/parse-app-url-test.ts
Labels: ready-for-review

#5518 Verify Clone-Repository path on focus
  app/src/ui/clone-repository/clone-repository.tsx
Labels: ready-for-review

#5677 Disable commit button when commit summary is only spaces
  app/src/ui/changes/commit-message.tsx
Labels: ready-for-review

#5538 nvm and pyenv and docs
  .nvmrc
  .python-version
  .tool-versions
  .travis.yml
  docs/contributing/setup-macos.md
  docs/contributing/setup.md
  package.json
Labels: docs, infrastructure, macOS, ready-for-review

#5702 add docs about how Desktop is packaged
  docs/technical/packaging.md
Labels: docs, infrastructure, ready-for-review

#5705 .node-version to 8.11.4
  .node-version
Labels: infrastructure, ready-for-review

#5710 Include link to packaging in Readme
  docs/README.md
Labels: docs, ready-for-review

#5662 fix overflow CSS for dialog boxes with dark theme on Windows
  app/styles/ui/_acknowledgements.scss
  app/styles/ui/_terms-and-conditions.scss
  app/styles/ui/dialogs/_release-notes.scss
Labels: ready-for-review

#5711 Add to max height of .commit-summary-description-scroll-view to accom…
  app/styles/ui/history/_commit-summary.scss
Labels: ready-for-review

#5703 switch from inline comments to normal jsdoc
  app/src/models/account.ts
Labels: infrastructure, ready-for-review, tech-debt

#5595 Warn user if branch exists on remote when creating branch
  app/src/ui/create-branch/create-branch-dialog.tsx
  app/src/ui/lib/branch-name-warnings.tsx
Labels: ready-for-review

#5727 Update roadmap after 1.4 release
  docs/process/roadmap.md
Labels: ready-for-review

#5726 test manifest update for v1.4
  docs/process/testing.md
Labels: infrastructure

#5722 refresh repository after revert
  app/src/lib/stores/app-store.ts
Labels: ready-for-review

#5616 Onboarding metrics
  app/src/lib/dispatcher/dispatcher.ts
  app/src/lib/stats/stats-store.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/sign-in-store.ts
  app/src/ui/add-repository/add-existing-repository.tsx
  app/src/ui/add-repository/create-repository.tsx
  app/src/ui/app.tsx
  app/src/ui/welcome/welcome.tsx
Labels: ready-for-review

#5748 draft release 1.4.1
  app/package.json
  changelog.json
Labels: ready-for-review

#5721 respect the protocol of a detected GitHub repository
  app/src/lib/api.ts
  app/src/ui/clone-repository/clone-repository.tsx
  app/test/unit/repositories-clone-grouping-test.ts
  app/test/unit/repositories-store-test.ts
Labels: ready-for-review

#5752 refresh repository after revert again
  app/src/lib/stores/app-store.ts
Labels: ready-for-review

#5698 Refactored App-Menu constructors with parameter properties
  app/src/models/app-menu.ts
Labels: ready-for-review, tech-debt

#5730 Refactored Models/Owner constructor with parameter properties
  app/src/models/owner.ts
Labels: infrastructure, ready-for-review, tech-debt

#5682 Simplify Branch constructor with parameter properties
  app/src/models/branch.ts
Labels: ready-for-review, tech-debt

#5737 Define GitHub Desktop product vision
  docs/process/what-is-desktop.md
Labels: docs

#5747 disable Lock integration
  .github/lock.yml
Labels: infrastructure, ready-for-review

#5723 retire the EmojiStore component in favour of plain function
  app/src/lib/read-emoji.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/emoji-store.ts
  app/src/lib/stores/index.ts
  app/src/ui/index.tsx
  app/test/unit/app-store-test.ts
  app/test/unit/app-test.tsx
Labels: infrastructure, ready-for-review, tech-debt

#5697 Refactored Status constructors with parameter properties
  app/src/models/status.ts
Labels: ready-for-review

#5760 Fix Overflow value of T&C and License Notices dialogs
  app/styles/ui/_acknowledgements.scss
  app/styles/ui/_terms-and-conditions.scss
Labels: ready-for-review

#5732 Refactored models/pull-request constructors with parameter properties
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/helpers/pull-request-updater.ts
  app/src/models/pull-request.ts
  app/src/ui/branches/pull-request-list.tsx
  app/src/ui/delete-branch/delete-pull-request-dialog.tsx
  app/src/ui/toolbar/branch-dropdown.tsx
Labels: infrastructure, ready-for-review, tech-debt

#5753 Linux Shells: add Terminator, MATE Terminal, Terminology
  app/src/lib/shells/linux.ts
  docs/technical/shell-integration.md
Labels: ready-for-review

#5750 Refactored Models/Repository constructors with parameter properties
  app/src/models/repository.ts
Labels: infrastructure, ready-for-review, tech-debt

#5751 Refactored Models/Submodule constructors with parameter properties
  app/src/models/submodule.ts
Labels: infrastructure, ready-for-review, tech-debt

#5693 Cleanup Azure Pipelines configuration
  vsts.yml
Labels: infrastructure, ready-for-review

#5720 push isDivergingBranchBannerVisible down into repository state
  app/src/lib/app-state.ts
  app/src/lib/dispatcher/dispatcher.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/repository-state-cache.ts
  app/src/ui/app.tsx
  app/src/ui/history/compare.tsx
  app/src/ui/repository.tsx
Labels: infrastructure, ready-for-review

#5765 Refactored Models/Git-Author constructors with parameter properties
  app/src/models/git-author.ts
Labels: ready-for-review, tech-debt
