Repository desktop/desktop, pull requests merged in 2018-10, with the labels that each got.

#5626 tslint deprecate warning
  app/src/ui/resizable/resizable.tsx
  app/webpack.common.ts
  tslint.json
Labels: infrastructure, ready-for-review

#5775 Added dynamic checking for error
  app/src/lib/stores/sign-in-store.ts
Labels: ready-for-review

#5794 Refactored models/cloning-repository constructors with parameter properties
  app/src/models/cloning-repository.ts
Labels: ready-for-review

#5783 Clicking History tab should default to commit history list
  app/src/ui/repository.tsx
Labels: ready-for-review

#5683 show resolved conflicts as resolved
  app/src/lib/git/diff-check.ts
  app/src/lib/git/status.ts
  app/src/lib/helpers/regex.ts
  app/src/lib/patch-formatter.ts
  app/src/lib/status-parser.ts
  app/src/models/status.ts
  app/styles/mixins/_octicon-status.scss
  app/test/helpers/repositories.ts
  app/test/unit/git/commit-test.ts
  app/test/unit/git/diff-check-test.ts
  app/test/unit/git/status-test.ts
  app/test/unit/helpers/regex-test.ts
Labels: ready-for-review

#5801 Refactored models/diff/image constructors with parameter prop
  app/src/models/diff/image.ts
Labels: ready-for-review

#5806 Refactored models/diff/diff-line constructors with parameter properties
  app/src/models/diff/diff-line.ts
Labels: ready-for-review

#5804 Add documentation for some properties
  app/src/lib/git/status.ts
Labels: ready-for-review

#5744 Update Discard-Changes-Dialog text when discarding all changes
  app/src/lib/app-state.ts
  app/src/lib/platform-case.ts
  app/src/ui/app.tsx
  app/src/ui/changes/changes-list.tsx
  app/src/ui/changes/sidebar.tsx
  app/src/ui/discard-changes/discard-changes-dialog.tsx
  app/test/unit/platform-case-test.ts
Labels: ready-for-review

#5807 Add repository path to "Remove repository" dialog (#5805)
  app/src/ui/remove-repository/confirm-remove-repository.tsx
Labels: ready-for-review

#5778 Refactored models/commit-identity constructor with parameter properties
  app/src/models/commit-identity.ts
Labels: ready-for-review

#5808 add number of conflict markers to status
  app/src/lib/git/diff-check.ts
  app/src/lib/git/status.ts
  app/src/lib/helpers/regex.ts
  app/src/models/status.ts
  app/test/unit/git/diff-check-test.ts
  app/test/unit/helpers/regex-test.ts
Labels: ready-for-review

#5852 fix changelog for 1.4.2
  changelog.json
Labels: infrastructure, ready-for-review, tech-debt

#5848 Add Remove Repo Accelerator
  app/src/main-process/menu/build-default-menu.ts
Labels: ready-for-review

#5859 fix emoji autocompleter updating
  app/src/ui/changes/sidebar.tsx
Labels: ready-for-review

#5815 Refactored models/diff/diff-selection constructors with parameter properties
  app/src/models/diff/diff-selection.ts
Labels: ready-for-review

#5814 Refactored models/diff/raw-diff constructors with parameter properties
  app/src/models/diff/raw-diff.ts
Labels: ready-for-review

#5844 Added support for python3 in cli #5843
  app/static/darwin/github.sh
Labels: ready-for-review

#5830 #5018 Added shortcut key to delete branches
  app/src/main-process/menu/build-default-menu.ts
Labels: ready-for-review

#5875 avoid unnecessarily reloading history
  app/src/lib/app-state.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/repository-state-cache.ts
Labels: ready-for-review

#5887 1.4.3-beta1
  app/package.json
  changelog.json
Labels: ready-for-review

#5769 upgrade to typescript 3.1
  app/src/ui/app.tsx
  app/src/ui/autocompletion/autocompleting-text-input.tsx
  app/src/ui/lib/author-input.tsx
  package.json
  yarn.lock
Labels: infrastructure, ready-for-review

#5729 add merge aborting functionality
  app/src/lib/git/merge.ts
  app/test/unit/git/merge-test.ts
Labels: ready-for-review

#5879 Documents new merge success metrics
  docs/process/metrics.md
Labels: ready-for-review

#5909 Removed invalid -P argument from a “mocha” call
  package.json
Labels: infrastructure, ready-for-review

#5901 Moves Conflict state into Changes state
  app/src/lib/app-state.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/repository-state-cache.ts
Labels: ready-for-review

#5810 Add metrics for completing/aborting a merge after conflicts
  app/src/lib/app-state.ts
  app/src/lib/dispatcher/dispatcher.ts
  app/src/lib/dispatcher/error-handlers.ts
  app/src/lib/stats/stats-database.ts
  app/src/lib/stats/stats-store.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/repository-state-cache.ts
  docs/process/metrics.md
Labels: ready-for-review

#5916 release 1.4.3-beta2
  app/package.json
  changelog.json
Labels: ready-for-review

#5920 Add Copy File Path button to the context menu of file list
  app/src/ui/changes/changes-list.tsx
  app/src/ui/history/file-list.tsx
  app/src/ui/lib/context-menu.ts
Labels: ready-for-review

#5907 add tests for symbolicRef and fix regression
  app/src/lib/git/refs.ts
  app/test/unit/git/ref-test.ts
Labels: ready-for-review

#5926 allow Buttons to take a tooltip
  app/src/ui/lib/button.tsx
Labels: ready-for-review

#5878 Add new repo button in repository dropdown
  app/src/ui/repositories-list/repositories-list.tsx
  app/styles/ui/_branches.scss
  app/styles/ui/_filter-list.scss
  app/styles/ui/_repository-list.scss
Labels: ready-for-review

#5924 Release 1.4.3
  app/package.json
  changelog.json
Labels: ready-for-review

#5910 add createMergeCommit and refactor out commit error handling logic
  app/src/lib/git/commit.ts
  app/test/unit/git/commit-test.ts
Labels: ready-for-review

#5900 A New Morning, Updating Yarn
  .yarnrc
  app/.yarnrc
  app/yarn.lock
  vendor/yarn-1.9.4.js
  yarn.lock
Labels: infrastructure, ready-for-review

#5207 handle folder dropped onto tray icon in macOS
  app/src/main-process/main.ts
  script/build.ts
  script/info.plist
Labels: macOS, ready-for-review

#5938 focus coverage rules only on app code
  .codecov.yml
Labels: infrastructure, ready-for-review

#5952 run status without optional locks for all users
  app/src/lib/feature-flag.ts
Labels: infrastructure, ready-for-review

#5940 codified section about where to start a release from
  docs/process/releasing-updates.md
Labels: infrastructure, ready-for-review

#5973 Repository name is now sanitized on publish
  app/src/ui/publish-repository/publish-repository.tsx
Labels: ready-for-review

#5983 a quick guide to adding unit tests
  docs/technical/adding-tests.md
Labels: infrastructure, ready-for-review

#5951 add some packaging improvements for Linux
  docs/contributing/linux-testing-and-you.md
  package.json
  script/electron-builder-linux.yml
  script/linux-after-install.sh
  script/linux-after-remove.sh
  yarn.lock
Labels: infrastructure, ready-for-review

#5955 allow DialogHeader to take a custom title element
  app/src/ui/dialog/header.tsx
Labels: ready-for-review

#5918 better ways to compare URLs
  app/src/lib/dispatcher/dispatcher.ts
  app/src/lib/repository-matching.ts
  app/src/lib/stores/helpers/infer-comparison-branch.ts
  app/test/unit/infer-comparison-branch-test.ts
  app/test/unit/repository-matching-test.ts
Labels: ready-for-review

#5645 documenting an aspirational structure of the app directory
  docs/technical/future-repository-structure.md
Labels: docs, infrastructure, ready-for-review

#5986 simple pr template
  .github/pull_request_template.md
Labels: infrastructure, ready-for-review

#5995 cleanup metadata support to help with providing support for merge conflicts
  app/src/lib/app-state.ts
  app/src/lib/dispatcher/error-handlers.ts
  app/src/lib/error-with-metadata.ts
  app/src/lib/git-error-context.ts
  app/src/lib/stores/app-store.ts
  app/src/ui/abort-merge/abort-merge-warning.tsx
  app/src/ui/app.tsx
  app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx
  docs/technical/error-reporting.md
Labels: ready-for-review

#5948 use remote displayed in the push/pull button when performing the push
  app/src/lib/stores/app-store.ts
Labels: ready-for-review

#5964 Add keyboard shortcut for rename branch menu action
  app/src/main-process/menu/build-default-menu.ts
Labels: ready-for-review

#5947 remove newlines to make hash values easier to read
  app/src/models/github-repository.ts
  app/src/models/repository.ts
Labels: ready-for-review, tech-debt

#5899 refreshed screenshots and instructions for timeline doc
  .github/ISSUE_TEMPLATE/bug_report.md
  docs/contributing/timeline-profile.md
Labels: docs, ready-for-review

#5882 simplify Compare tab state
  app/src/lib/app-state.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/git-store.ts
  app/src/lib/stores/repository-state-cache.ts
  app/src/ui/app.tsx
  app/src/ui/history/compare.tsx
  app/src/ui/history/merge-call-to-action-with-conflicts.tsx
  app/src/ui/history/merge-call-to-action.tsx
  app/src/ui/notification/new-commits-banner.tsx
  app/test/unit/repository-state-cache-test.ts
Labels: ready-for-review, tech-debt

#5877 add commit selection API to RepositoryStateCache and tidy up
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/repository-state-cache.ts
Labels: ready-for-review, tech-debt

#5950 remove duplicate implementation comparing GitHubRepository and remote
  app/src/lib/stores/helpers/find-upstream-remote.ts
  app/test/unit/repository-matching-test.ts
Labels: ready-for-review, tech-debt

#5949 tidy up around how GitStore stores remotes
  app/src/lib/git/remote.ts
  app/src/lib/infer-last-push-for-repository.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/git-store.ts
  app/test/unit/git/remote-test.ts
Labels: ready-for-review, tech-debt

#5707 extract some models from inside app-state.ts
  app/src/lib/app-state.ts
  app/src/lib/dispatcher/dispatcher.ts
  app/src/lib/dispatcher/error-handlers.ts
  app/src/lib/error-with-metadata.ts
  app/src/lib/git/authentication.ts
  app/src/lib/git/branch.ts
  app/src/lib/git/checkout.ts
  app/src/lib/git/clone.ts
  app/src/lib/git/fetch.ts
  app/src/lib/git/pull.ts
  app/src/lib/git/push.ts
  app/src/lib/git/revert.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/cloning-repositories-store.ts
  app/src/lib/stores/git-store.ts
  app/src/models/clone-options.ts
  app/src/models/commit-message.ts
  app/src/models/diff/image-diff.ts
  app/src/models/diff/index.ts
  app/src/models/git-account.ts
  app/src/models/popup.ts
  app/src/models/progress.ts
  app/src/models/retry-actions.ts
  app/src/ui/add-repository/add-existing-repository.tsx
  app/src/ui/add-repository/create-repository.tsx
  app/src/ui/app-error.tsx
  app/src/ui/app.tsx
  app/src/ui/branches/branches-container.tsx
  app/src/ui/changes/changes-list.tsx
  app/src/ui/changes/changes.tsx
  app/src/ui/changes/commit-message.tsx
  app/src/ui/changes/sidebar.tsx
  app/src/ui/cloning-repository.tsx
  app/src/ui/diff/image-diffs/modified-image-diff.tsx
  app/src/ui/diff/index.tsx
  app/src/ui/generic-git-auth/generic-git-auth.tsx
  app/src/ui/history/selected-commit.tsx
  app/src/ui/notification/new-commits-banner.tsx
  app/src/ui/repositories-list/repositories-list.tsx
  app/src/ui/repository-settings/repository-settings.tsx
  app/src/ui/repository.tsx
  app/src/ui/toolbar/push-pull-button.tsx
  app/src/ui/toolbar/revert-progress.tsx
  app/src/ui/updates/update-available.tsx
Labels: ready-for-review, tech-debt

#5994 help improve our release notes by writing them earlier
  .github/pull_request_template.md
Labels: docs, ready-for-review

#6004 don't call getSha in local build
  script/build.ts
Labels: infrastructure, ready-for-review

#6005 revert this tracing as it affects local production builds
  script/build.ts
Labels: infrastructure, ready-for-review

#5996 Release notes for 1.50 Beta 1
  app/package.json
  changelog.json
Labels: docs, ready-for-review

#5917 Show actual branch name in "Update From Default Branch" menu item
  app/src/lib/stores/app-store.ts
  app/src/lib/truncate-with-ellipsis.ts
  app/src/main-process/main.ts
  app/src/main-process/menu/build-default-menu.ts
  app/src/ui/main-process-proxy.ts
  app/test/unit/truncate-with-ellipsis-test.ts
Labels: ready-for-review

#5979 add a localStorage abstraction to tidy up our parsing work
  app/src/lib/local-storage.ts
  app/src/lib/stats/stats-store.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/welcome.ts
  app/src/ui/lib/features.ts
  app/src/ui/lib/update-store.ts
  app/test/setup-test-framework.ts
  app/test/unit/local-storage-test.ts
  package.json
  yarn.lock
Labels: ready-for-review, tech-debt

#5941 expand on how we plan and co-ordinate releases
  docs/process/release-planning.md
Labels: docs, ready-for-review

#6012 use a while loop in regex helpers
  app/src/lib/git/diff-check.ts
  app/src/lib/helpers/regex.ts
  app/test/unit/helpers/regex-test.ts
Labels: ready-for-review

#6028 Don't accept null for currentBranch in in Merge Dialog props
  app/src/ui/app.tsx
  app/src/ui/merge-branch/merge.tsx
Labels: ready-for-review

#6011 successful merge banner
  app/src/lib/app-state.ts
  app/src/lib/dispatcher/dispatcher.ts
  app/src/lib/git/merge.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/git-store.ts
  app/src/ui/app.tsx
  app/src/ui/banners/index.ts
  app/src/ui/banners/successful-merge.tsx
  app/styles/_ui.scss
  app/styles/ui/_banners.scss
  app/styles/ui/banners/_successful-merge.scss
Labels: ready-for-review

#5809 Conflicted merge resolution flow
  app/src/lib/dispatcher/dispatcher.ts
  app/src/lib/dispatcher/error-handlers.ts
  app/src/lib/error-with-metadata.ts
  app/src/lib/feature-flag.ts
  app/src/lib/git-error-context.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/git-store.ts
  app/src/models/popup.ts
  app/src/models/status.ts
  app/src/ui/abort-merge/abort-merge-warning.tsx
  app/src/ui/abort-merge/index.ts
  app/src/ui/app.tsx
  app/src/ui/merge-conflicts/index.ts
  app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx
  app/src/ui/merge-conflicts/merge-conflicts-warning.tsx
  app/styles/ui/_dialog.scss
  app/styles/ui/dialogs/_abort-merge.scss
  app/styles/ui/dialogs/_merge-conflicts.scss
  docs/technical/error-reporting.md
Labels: ready-for-review

#6027 Update title of merge dialog to match label in top-level menu
  app/src/ui/app.tsx
  app/src/ui/merge-branch/merge.tsx
  app/styles/ui/dialogs/_merge.scss
Labels: ready-for-review

#5977 Add a merge button to the branch selector
  app/src/ui/branches/branches-container.tsx
  app/styles/ui/_filter-list.scss
Labels: ready-for-review

#6018 Improve single file commit summary to match GitHub.com
  app/src/ui/changes/changes-list.tsx
Labels: ready-for-review

#6040 Release notes for 1.5 Beta 2
  app/package.json
  changelog.json
Labels: ready-for-review

#6034 add support for debugging jest tests in vscode
  .vscode/launch.json
Labels: infrastructure, ready-for-review

#6046 just some regrets about regexes
  app/src/lib/helpers/regex.ts
  app/test/unit/helpers/regex-test.ts
Labels: infrastructure, ready-for-review
