Repository desktop/desktop, pull requests merged in 2018-12, with the labels that each got.

#6316 Condense Banners into Banner Component
  app/src/ui/app.tsx
  app/src/ui/banners/banner.tsx
  app/src/ui/banners/index.ts
  app/src/ui/banners/successful-merge.tsx
  app/src/ui/banners/update-available.tsx
  app/src/ui/updates/index.ts
  app/styles/_ui.scss
  app/styles/ui/_banners.scss
  app/styles/ui/_update-notification.scss
  app/styles/ui/banners/_successful-merge.scss
  app/styles/ui/banners/_update-available.scss
Labels: ready-for-review, tech-debt

#6305 Fixed recent branch renaming
  app/src/lib/git/reflog.ts
  app/test/unit/git/reflog-test.ts
Labels: ready-for-review

#6249 remove merge conflict dialog feature flag
  app/src/lib/feature-flag.ts
  app/src/lib/stores/app-store.ts
  app/src/ui/app.tsx
  app/src/ui/merge-conflicts/index.ts
  app/src/ui/merge-conflicts/merge-conflicts-warning.tsx
Labels: ready-for-review, tech-debt

#6310 Hover states on list items and tabs
  app/src/ui/lib/list/list-row.tsx
  app/src/ui/lib/list/list.tsx
  app/styles/_variables.scss
  app/styles/themes/_dark.scss
  app/styles/ui/_list.scss
  app/styles/ui/_tab-bar.scss
Labels: ready-for-review

#5895 Allow cloning repositories to empty folders
  app/src/ui/clone-repository/clone-repository.tsx
Labels: ready-for-review

#6308 Add metrics for capturing unattributed commits
  app/src/lib/stats/stats-database.ts
  app/src/lib/stats/stats-store.ts
  app/src/lib/stores/app-store.ts
  docs/process/metrics.md
Labels: ready-for-review

#6337 1.5.1-beta1
  app/package.json
  changelog.json
Labels: ready-for-review

#6343 consolidate file counting logic in merge conflicts dialog
  app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx
Labels: ready-for-review, time-sensitive

#6358 Update labels to add "support" and description for "enhancement"
  docs/process/labels.md
Labels: ready-for-review

#6357 Fix for "directory not empty" error when no repository selected
  app/src/ui/clone-repository/clone-repository.tsx
Labels: ready-for-review

#6356 Fix odd filtering behavior after switching tabs in the clone dialog
  app/src/ui/clone-repository/clone-repository.tsx
Labels: ready-for-review

#6278 Add a store for cloneable repositories
  app/package.json
  app/src/lib/app-state.ts
  app/src/lib/dispatcher/dispatcher.ts
  app/src/lib/stores/api-repositories-store.ts
  app/src/lib/stores/app-store.ts
  app/src/ui/app.tsx
  app/src/ui/clone-repository/clone-generic-repository.tsx
  app/src/ui/clone-repository/clone-github-repository.tsx
  app/src/ui/clone-repository/clone-repository.tsx
  app/src/ui/index.tsx
  app/styles/ui/_add-repository.scss
  app/test/unit/app-store-test.ts
  app/test/unit/app-test.tsx
  app/yarn.lock
  package.json
  yarn.lock
Labels: ready-for-review

#6013 Add check for attempts to commit >100 MB files without Git LFS
  app/src/lib/feature-flag.ts
  app/src/lib/large-files.ts
  app/src/models/popup.ts
  app/src/ui/app.tsx
  app/src/ui/changes/oversized-files-warning.tsx
  app/src/ui/changes/sidebar.tsx
  app/styles/ui/_changes.scss
  app/styles/ui/changes/_oversized-files-warning.scss
Labels: ready-for-review

#6399 Merge conflicts dialog visual updates
  app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx
  app/styles/ui/dialogs/_merge-conflicts.scss
Labels: ready-for-review

#6336 helper method for checking for conflicted files in a working directory status
  app/src/lib/status.ts
Labels: ready-for-review

#6402 Previous opt in value
  app/src/lib/stats/stats-store.ts
Labels: ready-for-review

#6338 Display warning if existing readme file will be overwritten
  app/src/lib/feature-flag.ts
  app/src/ui/add-repository/create-repository.tsx
Labels: ready-for-review

#6409 1.5.1-beta4
  app/package.json
  changelog.json
Labels: ready-for-review

#6382 Dismissable merge conflict dialog and associated banner
  app/src/lib/app-state.ts
  app/src/lib/dispatcher/dispatcher.ts
  app/src/lib/stores/app-store.ts
  app/src/ui/app.tsx
  app/src/ui/banners/banner.tsx
  app/src/ui/banners/index.ts
  app/src/ui/banners/merge-conflicts-banner.tsx
  app/src/ui/dialog/dialog.tsx
  app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx
  app/styles/ui/_banners.scss
  app/styles/ui/banners/_merge-conflicts.scss
Labels: ready-for-review

#6417 Commit conflicted files warning
  app/src/lib/dispatcher/dispatcher.ts
  app/src/models/popup.ts
  app/src/ui/app.tsx
  app/src/ui/changes/sidebar.tsx
  app/src/ui/merge-conflicts/commit-conflicts-warning.tsx
  app/src/ui/merge-conflicts/index.ts
Labels: ready-for-review

#6416 Adds metrics to track selected terminal emulator and text editor
  app/src/lib/stats/stats-store.ts
  docs/process/metrics.md
Labels: ready-for-review

#6412 fix feature flag for readme overwrite warning
  app/src/lib/feature-flag.ts
Labels: ready-for-review

#6426 Merge conflicts flow metrics
  app/src/lib/dispatcher/dispatcher.ts
  app/src/lib/stats/stats-database.ts
  app/src/lib/stats/stats-store.ts
  app/src/ui/banners/merge-conflicts-banner.tsx
  app/src/ui/changes/sidebar.tsx
  app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx
  docs/process/metrics.md
Labels: ready-for-review

#6269 update other setup guides to match macOS format
  docs/contributing/building-arm64.md
  docs/contributing/setup-linux.md
  docs/contributing/setup-macos.md
  docs/contributing/setup-windows.md
  docs/contributing/setup.md
Labels: docs, ready-for-review

#6427 1.5.1-beta5
  app/package.json
  changelog.json
Labels: ready-for-review

#6435 Update merge conflicts metrics justification
  docs/process/metrics.md
Labels: docs, ready-for-review

#6404 Reorder the repository list's Add button options
  app/src/ui/repositories-list/repositories-list.tsx
Labels: ready-for-review

#6428 clear merge conflicts banner after there are no more conflicted files
  app/src/ui/changes/sidebar.tsx
Labels: ready-for-review

#6446 Fix displayed color for conflict status
  app/src/lib/status.ts
  app/src/ui/changes/changed-file-details.tsx
  app/src/ui/changes/changed-file.tsx
  app/src/ui/history/file-list.tsx
Labels: ready-for-review

#6449 hotfix for checkmark color issue
  app/src/lib/status.ts
  app/src/ui/changes/changed-file-details.tsx
  app/src/ui/changes/changed-file.tsx
  app/src/ui/history/file-list.tsx
Labels: ready-for-review, time-sensitive

#6452 Don't show "Still Conflicted Warning" when all conflicts are resolved
  app/src/ui/changes/sidebar.tsx
Labels: ready-for-review, time-sensitive

#6436 Cloneable filter list
  app/src/ui/clone-repository/clone-github-repository.tsx
  app/src/ui/clone-repository/cloneable-repository-filter-list.tsx
  app/src/ui/lib/filter-list.tsx
  app/src/ui/lib/list/list.tsx
  app/styles/_ui.scss
  app/styles/ui/_add-repository.scss
  app/styles/ui/_cloneable-repository-filter-list.scss
Labels: ready-for-review

#6455 Backport work from PR #6452
  app/src/ui/changes/sidebar.tsx
Labels: ready-for-review

#6272 Add integration for JetBrains Webstorm
  app/src/lib/editors/win32.ts
  docs/technical/editor-integration.md
Labels: integrations, ready-for-review

#6477 Cloneable filter list tidy up
  app/src/ui/clone-repository/cloneable-repository-filter-list.tsx
Labels: ready-for-review

#6476 Repository list memoization
  app/src/ui/repositories-list/group-repositories.ts
  app/src/ui/repositories-list/repositories-list.tsx
Labels: ready-for-review

#6471 Add VB to syntax highlighting docs
  docs/technical/syntax-highlighting.md
Labels: docs, ready-for-review

#6470 Wireup VB in syntax highlighting
  app/src/highlighter/index.ts
Labels: ready-for-review

#6503 Rename master branch in CI configs
  .travis.yml
  appveyor.yml
Labels: ready-for-review

#6499 Rename master to development in docs
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/config.yml
  README.md
  docs/contributing/linux-testing-and-you.md
  docs/contributing/styleguide.md
  docs/process/notes-for-contributors.md
  docs/process/pull-request-triage.md
  docs/process/quality-process.md
  docs/process/release-planning.md
  docs/process/releasing-updates.md
  docs/technical/adding-tests.md
  docs/technical/editor-integration.md
  docs/technical/placeholders.md
  docs/technical/shell-integration.md
  docs/technical/syntax-highlighting.md
Labels: docs, ready-for-review

#6500 upgrade to Typescript 3.2
  app/src/lib/stores/app-store.ts
  app/src/ui/clone-repository/clone-repository.tsx
  app/test/unit/repository-state-cache-test.ts
  package.json
  yarn.lock
Labels: ready-for-review, tech-debt

#6480 add untracked app file status
  app/src/lib/git/diff.ts
  app/src/lib/git/log.ts
  app/src/lib/git/status.ts
  app/src/lib/patch-formatter.ts
  app/src/lib/status.ts
  app/src/models/status.ts
  app/src/ui/changes/changes-list.tsx
  app/src/ui/diff/index.tsx
  app/src/ui/diff/syntax-highlighting/index.ts
  app/src/ui/octicons/status.ts
  app/test/unit/git/commit-test.ts
Labels: ready-for-review
