Repository desktop/desktop, pull requests merged in 2019-01, with the labels that each got.

#6419 Add a dev-only menu item to show the release notes popup
  app/src/main-process/menu/build-default-menu.ts
  app/src/main-process/menu/menu-event.ts
  app/src/ui/app.tsx
Labels: ready-for-review

#6539 ensure we await the value read from global config
  app/src/lib/git/core.ts
Labels: ready-for-review

#6532 restore eslint ignore file and ignore generated coverage folders
  .eslintignore
Labels: infrastructure, ready-for-review

#6475 Empty repository list view
  app/src/ui/app.tsx
  app/src/ui/repositories-list/repositories-list.tsx
  app/styles/ui/_repository-list.scss
Labels: ready-for-review

#6542 change feature flag for large file size warning to enable for everyone
  app/src/lib/feature-flag.ts
Labels: ready-for-review

#6543 enable git protocol v2 for beta users
  app/src/lib/feature-flag.ts
Labels: ready-for-review

#6520 Fix image overlapping menu
  app/styles/ui/_diff.scss
Labels: ready-for-review

#6541 ignore handled Enter event in FocusContainer keydown event handler
  app/src/ui/lib/list/list.tsx
Labels: ready-for-review, windows

#6525 CommitMessages - Better Handle Nulls
  app/src/lib/app-state.ts
  app/src/lib/dispatcher/dispatcher.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/git-store.ts
  app/src/lib/stores/repository-state-cache.ts
  app/src/models/commit-message.ts
  app/src/ui/changes/changes-list.tsx
  app/src/ui/changes/oversized-files-warning.tsx
  app/src/ui/merge-conflicts/commit-conflicts-warning.tsx
  app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx
  app/test/unit/stores/updates/changes-state-helper.ts
Labels: ready-for-review, tech-debt

#6505 ignore any xml file generated to be read by junit
  .gitignore
Labels: infrastructure, ready-for-review

#6464 don't include untracked files in merge commit
  app/src/lib/dispatcher/dispatcher.ts
  app/src/lib/stores/app-store.ts
  app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx
  app/test/helpers/repositories.ts
  app/test/unit/app-store-test.ts
  app/test/unit/git/commit-test.ts
  app/test/unit/git/status-test.ts
Labels: ready-for-review

#6554 1.6.0-beta1
  app/package.json
  changelog.json
Labels: ready-for-review

#6557 detect no-op merges and don't show merge success banner
  app/src/lib/git/merge.ts
  app/test/unit/git/merge-test.ts
Labels: ready-for-review

#6228 auto recover missing repository
  app/src/lib/dispatcher/dispatcher.ts
  app/src/lib/stores/app-store.ts
  app/src/ui/index.tsx
  app/src/ui/missing-repository.tsx
  app/styles/ui/_missing-repository-view.scss
Labels: ready-for-review

#6568 fix all the places where the blank slate overflows
  app/styles/ui/_blank-slate.scss
  app/styles/ui/_repository-list.scss
Labels: ready-for-review

#6445 Onboarding improvements: No local changes blank slate
  app/src/lib/feature-flag.ts
  app/src/lib/menu-item.ts
  app/src/ui/app-menu/menu-list-item.tsx
  app/src/ui/app.tsx
  app/src/ui/changes/blankslate-action.tsx
  app/src/ui/changes/menu-backed-blankslate-action.tsx
  app/src/ui/changes/no-changes.tsx
  app/src/ui/main-process-proxy.ts
  app/src/ui/repository.tsx
  app/static/common/paper-stack.svg
  app/styles/_globals.scss
  app/styles/_variables.scss
  app/styles/themes/_dark.scss
  app/styles/ui/_changes.scss
  app/styles/ui/_no-branches.scss
  app/styles/ui/changes/_blankslate-action.scss
  app/styles/ui/changes/_no-changes.scss
  app/styles/ui/window/_toast-notification.scss
Labels: ready-for-review

#6504 tweak and organize PR template details
  .github/pull_request_template.md
Labels: docs, ready-for-review

#6594 1.6.0-beta2 release
  app/package.json
  changelog.json
Labels: ready-for-review

#6597 extract functions to format and remove &'s from menu labels
  app/src/ui/changes/no-changes.tsx
Labels: ready-for-review

#6612 Update VSTS guide to Azure DevOps
  docs/integrations/azure-devops.md
  docs/integrations/vsts.md
Labels: docs, ready-for-review

#6621 A repository doesn't need to have a remote to be pushed
  app/src/lib/menu-update.ts
Labels: ready-for-review, time-sensitive

#6623 Prepositions are lowercase when using title case
  app/src/main-process/menu/build-default-menu.ts
Labels: ready-for-review

#6620 Blankslate action transitions
  app/package.json
  app/src/ui/changes/no-changes.tsx
  app/src/ui/repository.tsx
  app/styles/ui/changes/_no-changes.scss
  app/yarn.lock
  package.json
  yarn.lock
Labels: ready-for-review, time-sensitive

#6619 enable new blank slate for all users
  app/src/lib/feature-flag.ts
Labels: ready-for-review

#6629 Pull action grammar
  app/src/ui/changes/no-changes.tsx
Labels: ready-for-review

#6606 manualConflictResolution and stageManualConflictResolution
  app/src/lib/git/commit.ts
  app/src/lib/stores/app-store.ts
  app/src/models/manual-conflict-resolution.ts
  app/test/unit/git/commit-test.ts
Labels: ready-for-review

#6631 reshow overflow to fix #6459
  app/styles/ui/changes/_commit-message.scss
Labels: ready-for-review

#6634 1.6.0-beta3 release notes
  app/package.json
  changelog.json
Labels: ready-for-review

#6641 Move Create PR action behind beta feature flag
  app/src/lib/feature-flag.ts
  app/src/ui/changes/no-changes.tsx
Labels: ready-for-review

#6517 port script tests from mocha to jest
  .vscode/launch.json
  app/jest.config.js
  azure-pipelines.yml
  package.json
  script/.eslintrc.yml
  script/changelog/test/parser-test.ts
  script/jest.config.js
Labels: infrastructure, ready-for-review

#6516 update octicons package to v8.x
  app/src/ui/octicons/octicons.generated.ts
  package.json
  script/generate-octicons.ts
  yarn.lock
Labels: ready-for-review, tech-debt

#6626 add manual resolutions to appState
  app/src/lib/app-state.ts
  app/src/lib/dispatcher/dispatcher.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/updates/changes-state.ts
  app/test/unit/stores/updates/update-conflict-state-test.ts
Labels: ready-for-review

#6640 extract updateLicenseDump and promisify it
  script/build.ts
  script/licenses/license-overrides.ts
  script/licenses/update-license-dump.ts
Labels: infrastructure, ready-for-review, tech-debt

#6643 Menu state race condition
  app/src/main-process/main.ts
  app/src/main-process/menu/find-menu-item.ts
  app/src/main-process/menu/get-all-menu-items.ts
  app/src/main-process/menu/index.ts
Labels: ready-for-review

#6518 port integration tests to jest
  .vscode/launch.json
  app/jest.integration.config.js
  app/jest.unit.config.js
  app/test/integration/launch-test.ts
  app/test/mochareporters.json
  package.json
  yarn.lock
Labels: infrastructure, ready-for-review

#6481 Remember Scroll Positions in History and Changes Lists
  app/src/ui/changes/changes-list.tsx
  app/src/ui/changes/sidebar.tsx
  app/src/ui/history/commit-list.tsx
  app/src/ui/history/compare.tsx
  app/src/ui/lib/list/list.tsx
  app/src/ui/repository.tsx
Labels: ready-for-review

#6463 check for invalid rows and emit a warning into devtools
  app/src/ui/lib/list/list.tsx
Labels: ready-for-review

#6440 replace runas with fs-admin to handle installing installing CLI
  app/package.json
  app/src/ui/lib/install-cli.ts
  app/typings/fs-admin/index.d.ts
  app/webpack.common.ts
  app/yarn.lock
  package.json
  yarn.lock
Labels: macOS, ready-for-review, tech-debt

#6630 Clean up no changes blankslate feature flag
  app/src/lib/feature-flag.ts
  app/src/ui/changes/no-changes.tsx
  app/static/common/empty-no-commit.svg
  app/styles/ui/changes/_no-changes.scss
Labels: ready-for-review, tech-debt

#6681 Add Support for Short SHAs
  app/src/lib/git/for-each-ref.ts
  app/src/lib/git/log.ts
  app/src/models/commit.ts
  app/src/ui/history/commit-summary.tsx
  app/src/ui/lib/configure-git-user.tsx
  app/test/unit/create-branch-test.ts
  app/test/unit/git/branch-test.ts
  app/test/unit/git/checkout-test.ts
  app/test/unit/git/commit-test.ts
  app/test/unit/git/for-each-ref-test.ts
  app/test/unit/git/log-test.ts
  app/test/unit/group-branches-test.ts
  app/test/unit/infer-comparison-branch-test.ts
Labels: ready-for-review

#6678 upgrade prettier to latest version
  package.json
  yarn.lock
Labels: infrastructure, ready-for-review

#6660 Only render NoChanges when there are.. no changes
  app/src/ui/repository.tsx
Labels: ready-for-review

#6688 Remove the chai and mocha packages
  app/test/globals.ts
  docs/technical/adding-tests.md
  package.json
  yarn.lock
Labels: ready-for-review, tech-debt

#6696 Desktop 1.6.2-beta0
  app/package.json
  changelog.json
Labels: ready-for-review

#6687 disable the app menu bar when there are no tracked repositories
  app/src/ui/app.tsx
Labels: ready-for-review

#6519 Give arrow shown in the path for renamed/copied files some margins
  app/src/ui/lib/path-label.tsx
  app/styles/_ui.scss
  app/styles/ui/_file-list.scss
  app/styles/ui/_path-label.scss
  app/styles/ui/changes/_changes-view.scss
Labels: ready-for-review

#6443 Add link to all release notes in the release notes dialog
  app/src/ui/about/about.tsx
  app/src/ui/banners/update-available.tsx
  app/src/ui/lib/releases.ts
  app/src/ui/release-notes/release-notes-dialog.tsx
  app/styles/ui/dialogs/_release-notes.scss
Labels: ready-for-review

#6051 Add automatic switching between Dark Mode and Light
  app/src/lib/app-state.ts
  app/src/lib/dispatcher/dispatcher.ts
  app/src/lib/get-os.ts
  app/src/lib/stores/app-store.ts
  app/src/ui/app.tsx
  app/src/ui/lib/application-theme.ts
  app/src/ui/lib/dark-theme.ts
  app/src/ui/lib/theme-change-monitor.ts
  app/src/ui/preferences/appearance.tsx
  app/src/ui/preferences/preferences.tsx
  app/test/__mocks__/electron.ts
Labels: integrations, macOS, ready-for-review

#6697 add get binary files git function
  app/src/lib/git/diff.ts
  app/src/lib/helpers/regex.ts
  app/test/unit/git/diff-test.ts
Labels: ready-for-review

#6656 embed the SHA in the About view in development mode
  app/src/ui/about/about.tsx
  app/src/ui/app.tsx
Labels: ready-for-review, tech-debt

#6679 File Manager More Consistently
  app/src/main-process/menu/build-default-menu.ts
  app/src/ui/changes/no-changes.tsx
  app/src/ui/repositories-list/repository-list-item.tsx
Labels: ready-for-review

#6703 Wireup Lua and Fortran Syntax highlighting
  app/src/highlighter/index.ts
  docs/technical/syntax-highlighting.md
Labels: ready-for-review

#6704 Replaced "Ignore File" with clearer verbiage
  app/src/ui/changes/changes-list.tsx
Labels: ready-for-review

#6695 move Dispatcher module into UI folder
  app/src/ui/abort-merge/abort-merge-warning.tsx
  app/src/ui/add-repository/add-existing-repository.tsx
  app/src/ui/add-repository/create-repository.tsx
  app/src/ui/app-menu/app-menu-bar-button.tsx
  app/src/ui/app-menu/app-menu-bar.tsx
  app/src/ui/app-menu/app-menu.tsx
  app/src/ui/app.tsx
  app/src/ui/autocompletion/issues-autocompletion-provider.tsx
  app/src/ui/banners/merge-conflicts-banner.tsx
  app/src/ui/banners/update-available.tsx
  app/src/ui/branches/branches-container.tsx
  app/src/ui/branches/push-branch-commits.tsx
  app/src/ui/changes/changes-list.tsx
  app/src/ui/changes/changes.tsx
  app/src/ui/changes/commit-message.tsx
  app/src/ui/changes/oversized-files-warning.tsx
  app/src/ui/changes/sidebar.tsx
  app/src/ui/clone-repository/clone-repository.tsx
  app/src/ui/create-branch/create-branch-dialog.tsx
  app/src/ui/delete-branch/delete-branch-dialog.tsx
  app/src/ui/delete-branch/delete-pull-request-dialog.tsx
  app/src/ui/diff/binary-file.tsx
  app/src/ui/diff/index.tsx
  app/src/ui/discard-changes/discard-changes-dialog.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/dispatcher/error-handlers.ts
  app/src/ui/dispatcher/index.ts
  app/src/ui/history/compare.tsx
  app/src/ui/history/merge-call-to-action-with-conflicts.tsx
  app/src/ui/history/merge-call-to-action.tsx
  app/src/ui/history/selected-commit.tsx
  app/src/ui/index.tsx
  app/src/ui/lib/open-file.ts
  app/src/ui/lib/sign-in.tsx
  app/src/ui/merge-branch/merge.tsx
  app/src/ui/merge-conflicts/commit-conflicts-warning.tsx
  app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx
  app/src/ui/missing-repository.tsx
  app/src/ui/notification/new-commits-banner.tsx
  app/src/ui/preferences/preferences.tsx
  app/src/ui/publish-repository/publish.tsx
  app/src/ui/rename-branch/rename-branch-dialog.tsx
  app/src/ui/repositories-list/repositories-list.tsx
  app/src/ui/repository-settings/repository-settings.tsx
  app/src/ui/repository.tsx
  app/src/ui/sign-in/sign-in.tsx
  app/src/ui/toolbar/branch-dropdown.tsx
  app/src/ui/toolbar/push-pull-button.tsx
  app/src/ui/welcome/sign-in-dot-com.tsx
  app/src/ui/welcome/sign-in-enterprise.tsx
  app/src/ui/welcome/usage-opt-out.tsx
  app/src/ui/welcome/welcome.tsx
  app/test/helpers/in-memory-dispatcher.ts
  app/test/unit/app-test.tsx
Labels: ready-for-review, tech-debt

#6611 Change merge hint and merge button order
  app/src/ui/history/merge-call-to-action-with-conflicts.tsx
  app/src/ui/history/merge-call-to-action.tsx
  app/styles/ui/_merge-status.scss
Labels: ready-for-review

#6699 fix manual conflict detection
  app/src/lib/git/diff.ts
  app/src/lib/git/status.ts
  app/src/lib/status.ts
  app/src/models/status.ts
  app/test/unit/git/diff-test.ts
  app/test/unit/git/status-test.ts
Labels: ready-for-review

#6141 prevent concurrent fetches between user and status indicator checks
  app/src/lib/app-state.ts
  app/src/lib/stores/app-store.ts
  app/src/ui/toolbar/push-pull-button.tsx
Labels: ready-for-review

#6715 1.6.2 beta 1
  app/package.json
  changelog.json
Labels: ready-for-review

#6720 Remove enableStatusWithoutOptionalLocks Flag
  app/src/lib/feature-flag.ts
  app/src/lib/git/status.ts
Labels: ready-for-review, tech-debt

#6684 port linting to use renamed TS parser
  .eslintrc.yml
  app/src/main-process/menu/build-default-menu.ts
  eslint-rules/insecure-random.js
  package.json
Labels: infrastructure, ready-for-review
