Repository desktop/desktop, pull requests merged in 2019-07, with the labels that each got.

#7859 enable branch pruning for production
  app/src/lib/feature-flag.ts
Labels: epic:branch-pruner, ready-for-review

#7894 draft release notes for 2.1.0
  app/package.json
  changelog.json
Labels: ready-for-review

#7893 2.1.0 release
  app/package.json
  app/src/lib/feature-flag.ts
  changelog.json
Labels: ready-for-review

#7900 Bump .node-version to latest LTS release
  .node-version
Labels: infrastructure, ready-for-review

#7883 set initial state before potential state update
  app/src/ui/rebase/choose-branch.tsx
Labels: ready-for-review, tech-debt

#7899 Trigger text diff search plugin even when CodeMirror doesn't have focus
  app/src/main-process/menu/build-default-menu.ts
  app/src/main-process/menu/menu-event.ts
  app/src/ui/app.tsx
  app/src/ui/diff/text-diff.tsx
Labels: ready-for-review

#7878 handle "bad revision" error when starting a rebase
  app/src/lib/git/rebase.ts
  app/src/lib/git/rev-list.ts
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/rebase/choose-branch.tsx
Labels: ready-for-review

#7886 update registry-js to version that is compatible with Electron 5
  app/package.json
  app/yarn.lock
Labels: tech-debt, windows

#7921 Hover Shows on list item
  app/src/ui/repositories-list/repository-list-item.tsx
Labels: ready-for-review

#7922 Enable WSL for Beta
  app/src/lib/feature-flag.ts
Labels: ready-for-review

#7806 upgrade typescript-eslint packages to latest versions
  package.json
  yarn.lock
Labels: infrastructure, ready-for-review

#7850 make eslint check inside VSCode in real-time
  .vscode/settings.json
Labels: infrastructure, ready-for-review

#7851 Fix devtools warning commitconflicts
  app/src/ui/merge-conflicts/commit-conflicts-warning.tsx
  app/styles/ui/_dialog.scss
  app/styles/ui/dialogs/_commit-conflicts-warning.scss
Labels: ready-for-review

#7799 Upgrade to Electron Five (5)
  app/.npmrc
  app/src/lib/globals.d.ts
  app/src/lib/menu-item.ts
  app/src/lib/shell.ts
  app/src/lib/stores/app-store.ts
  app/src/main-process/app-window.ts
  app/src/main-process/crash-window.ts
  app/src/main-process/menu/build-default-menu.ts
  app/src/models/app-menu.ts
  app/src/ui/add-repository/add-existing-repository.tsx
  app/src/ui/add-repository/create-repository.tsx
  app/src/ui/diff/image-diffs/modified-image-diff.tsx
  app/src/ui/history/commit-summary.tsx
  app/src/ui/lib/list/list.tsx
  package.json
  yarn.lock
Labels: electron, ready-for-review

#7962 release 2.1.1-beta1
  app/package.json
  changelog.json
Labels: ready-for-review

#7970 don't force stashed changes button to be 100% tall
  app/styles/ui/changes/_changes-list.scss
Labels: ready-for-review

#7969 fix overflowing diffs in electron five (5)
  app/styles/ui/_commit-details.scss
  app/styles/ui/_repository.scss
  app/styles/ui/_stash-diff-viewer.scss
  app/styles/ui/changes/_changes-view.scss
  app/styles/ui/history/_history.scss
Labels: ready-for-review

#7979 2.1.1-beta2 release
  app/package.json
  changelog.json
Labels: ready-for-review

#7568 organize and update community section of README
  README.md
Labels: docs, ready-for-review

#7943 Add Kitty support for macOS (second take)
  app/src/lib/shells/darwin.ts
  docs/technical/shell-integration.md
Labels: integrations, ready-for-review

#8009 Fix word overflow in external editor error popup
  app/styles/ui/_preferences.scss
Labels: ready-for-review

#7818 cleanup enableGitProtocolVersionTwo flag
  app/src/lib/feature-flag.ts
  app/src/lib/git/core.ts
Labels: ready-for-review, tech-debt

#7817 cleanup pull with rebase flag
  app/src/lib/feature-flag.ts
  app/src/lib/git/pull.ts
  app/src/lib/git/rebase.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/git-store.ts
  app/src/ui/changes/changes-list.tsx
  app/src/ui/changes/sidebar.tsx
  app/src/ui/index.tsx
  app/src/ui/toolbar/branch-dropdown.tsx
  app/src/ui/toolbar/push-pull-button.tsx
Labels: ready-for-review, tech-debt

#7666 override port for development build using environment variable
  app/webpack.development.ts
Labels: infrastructure, ready-for-review

#7928 Add syntax highlighting support for 20 more languages
  app/src/highlighter/index.ts
  docs/technical/syntax-highlighting.md
Labels: ready-for-review

#7989 add new types for Git work trees
  app/src/models/repository.ts
Labels: ready-for-review

#8018 swap request bot label to new one
  .github/config.yml
Labels: infrastructure, ready-for-review

#8011 add atom nightly and beta support again
  app/src/lib/editors/win32.ts
  docs/technical/editor-integration.md
Labels: ready-for-review

#8007 re-word local changes text
  app/src/ui/changes/no-changes.tsx
Labels: ready-for-review

#7198 add general versioning guidelines for dependencies
  docs/contributing/upgrading-dependencies.md
Labels: docs, ready-for-review, tech-debt

#7840 fix: prevent doing some actions when committing on action
  app/src/ui/changes/changes-list.tsx
  app/src/ui/changes/changes.tsx
  app/src/ui/changes/sidebar.tsx
  app/src/ui/changes/undo-commit.tsx
  app/src/ui/repository.tsx
Labels: ready-for-review

#8046 2.1.1-beta3 release
  app/package.json
  changelog.json
Labels: ready-for-review

#8006 Git WorkTree APIs
  app/src/lib/git/index.ts
  app/src/lib/git/worktree.ts
  app/test/setup-test-framework.ts
  app/test/unit/git/worktree-test.ts
  package.json
  yarn.lock
Labels: ready-for-review

#8026 git patch APIs
  app/src/lib/git/apply.ts
  app/src/lib/git/format-patch.ts
  app/src/lib/git/index.ts
  app/test/helpers/repositories.ts
  app/test/unit/git/apply-test.ts
  app/test/unit/git/format-patch-test.ts
Labels: ready-for-review

#8021 update keychain known issue to indicate this is relevant to later macOS versions
  docs/known-issues.md
Labels: docs, ready-for-review
