Repository desktop/desktop, pull requests merged in 2019-11, with the labels that each got.

#8556 remove travis config
  .travis.yml
Labels: infrastructure

#8642 Grammar cracker
  app/src/ui/diff/index.tsx
  app/test/fixtures/merge-parser/desktop/merge-diff-too-large-into-offline-mode-y-u-no-work.txt
Labels: ready-for-review

#8634 Remove Azure Pipelines CI
  README.md
  app/test/unit/git/worktree-test.ts
  azure-pipelines.yml
Labels: infrastructure

#8635 Store user's repo permissions
  app/src/lib/api.ts
  app/src/lib/databases/repositories-database.ts
  app/src/lib/stores/repositories-store.ts
  app/src/models/github-repository.ts
  app/src/ui/octicons/repository.ts
  app/src/ui/release-notes/release-notes-dialog.tsx
  app/test/helpers/repository-builder-branch-pruner.ts
  app/test/unit/infer-comparison-branch-test.ts
  app/test/unit/octicon-test.ts
  app/test/unit/repositories-clone-grouping-test.ts
  app/test/unit/repositories-database-test.ts
  app/test/unit/repositories-store-test.ts
  app/test/unit/repository-matching-test.ts
  app/test/unit/repository-state-cache-test.ts
  app/test/unit/text-token-parser-test.ts
Labels: epic:fork

#8668 Warn user if they're committing to a repo they don't have write permission for
  app/src/models/github-repository.ts
  app/src/ui/changes/changes-list.tsx
  app/src/ui/changes/commit-message.tsx
  app/src/ui/changes/permissions-commit-warning.tsx
  app/src/ui/changes/protected-branch-warning.tsx
  app/styles/ui/_changes.scss
  app/styles/ui/changes/_permissions-commit-warning.scss
Labels: epic:fork

#8693 changed wording to match git autocrlf behavior
  app/src/ui/changes/changed-file-details.tsx
Labels: ready-for-review
