Repository desktop/desktop, pull requests merged in 2019-09, with the labels that each got.

#8150 Ignore global gitconfig for unit tests
  .gitignore
  app/test/unit-test-env.ts
Labels: ready-for-review

#8163 VSCodium support
  app/src/lib/editors/darwin.ts
  app/src/lib/editors/linux.ts
  app/src/lib/editors/win32.ts
Labels: integrations, ready-for-review

#8199 remove codecov statuses config
  .codecov.yml
Labels: infrastructure, ready-for-review

#8173 Parse Issues in Comma List
  app/src/lib/text-token-parser.ts
  app/test/unit/text-token-parser-test.ts
Labels: ready-for-review

#8211 Shared feature flag and stubs for onboarding tutorial
  app/src/lib/feature-flag.ts
  app/src/models/repository.ts
Labels: ready-for-review

#8092 Added CodeRunner to the External Editor list
  app/src/lib/editors/darwin.ts
Labels: integrations, ready-for-review

#8222 Rename pull-request-triage.md to pull-requests.md
  .github/CONTRIBUTING.md
  docs/README.md
  docs/process/pull-requests.md
Labels: docs, ready-for-review

#8209 Show menu bar in the no-repositories blank slate on Windows
  app/src/lib/app-state.ts
  app/src/lib/stores/app-store.ts
  app/src/ui/app.tsx
Labels: ready-for-review

#8224 Omit `app/test/fixtures` results from VS Code project search
  .vscode/settings.json
Labels: ready-for-review

#8220 use openExternal async
  app/src/main-process/main.ts
Labels: ready-for-review

#8219 Add instructions on doing a focused test run
  docs/contributing/setup.md
Labels: docs, ready-for-review

#8244 [Onboarding] Tutorial entry point
  app/src/lib/databases/repositories-database.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/repositories-store.ts
  app/src/models/popup.ts
  app/src/models/repository.ts
  app/src/ui/app.tsx
  app/src/ui/blank-slate/blank-slate.tsx
  app/src/ui/blank-slate/create-tutorial-repository-dialog.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/styles/ui/_dialog.scss
  app/styles/ui/dialogs/_create-tutorial-repository.scss
Labels: epic:onboarding, ready-for-review

#8225 [Onboarding] Style tutorial panel 👩🏽‍🎨👩🏼‍🎨👩🏻‍🎨
  app/src/ui/tutorial-panel/tutorial-panel.tsx
  app/static/common/required-status-check.svg
  app/styles/_variables.scss
  app/styles/themes/_dark.scss
  app/styles/ui/_tutorial.scss
Labels: epic:onboarding, ready-for-review

#8118 Check the commit message dialog scroll state also on input events
  app/src/ui/changes/commit-message.tsx
Labels: ready-for-review

#8242 [Onboarding tutorial] Evaluate step completion
  app/src/lib/app-state.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/helpers/tutorial-assessor.ts
  app/src/models/tutorial-step.ts
  app/src/ui/app.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/repository.tsx
  app/src/ui/tutorial-panel/tutorial-panel.tsx
  app/styles/ui/_tutorial.scss
Labels: epic:onboarding, ready-for-review

#8299 [Tutorial] Enable tutorial for beta
  app/src/lib/feature-flag.ts
Labels: epic:onboarding, ready-for-review

#8295 [Onboarding Tutorial] platform-specific keyboard shortcuts
  app/src/ui/tutorial-panel/tutorial-panel.tsx
Labels: epic:onboarding, ready-for-review

#8294 Revise tutorial copy
  app/src/ui/tutorial-panel/tutorial-panel.tsx
Labels: epic:onboarding, ready-for-review

#8298 [Tutorial] Update resolved editor at launch
  app/src/lib/stores/app-store.ts
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx
  app/src/ui/rebase/show-conflicted-files-dialog.tsx
Labels: epic:onboarding, ready-for-review

#8309 Merge tutorial epic branch back into development
  app/src/lib/app-state.ts
  app/src/lib/feature-flag.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/helpers/tutorial-assessor.ts
  app/src/models/tutorial-step.ts
  app/src/ui/app.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx
  app/src/ui/rebase/show-conflicted-files-dialog.tsx
  app/src/ui/repository.tsx
  app/src/ui/tutorial-panel/index.ts
  app/src/ui/tutorial-panel/tutorial-panel.tsx
  app/static/common/required-status-check.svg
  app/styles/_ui.scss
  app/styles/_variables.scss
  app/styles/themes/_dark.scss
  app/styles/ui/_tutorial.scss
  appveyor.yml
Labels: epic:onboarding, ready-for-review

#8311 Prevent triggering multiple tutorial creation flows in parallel
  app/src/ui/app.tsx
  app/src/ui/blank-slate/create-tutorial-repository-dialog.tsx
Labels: epic:onboarding, ready-for-review

#8312 Release 2.2.0-beta1
  app/package.json
  changelog.json
Labels: ready-for-review

#8321 Properly split highlighting modes on Windows
  app/webpack.common.ts
Labels: ready-for-review

#8330 [Onboarding tutorial] Display "Open editor" button after editor has been installed
  app/src/ui/app.tsx
  app/src/ui/repository.tsx
  app/src/ui/tutorial-panel/tutorial-panel.tsx
Labels: epic:onboarding, ready-for-review

#8332 Don't wait until we see the PR in the API to mark the PR step as complete
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/helpers/tutorial-assessor.ts
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/tutorial-panel/tutorial-panel.tsx
Labels: epic:onboarding, ready-for-review

#8334 Make app's version string selectable text instead of a special link
  app/src/ui/about/about.tsx
  app/styles/_globals.scss
Labels: ready-for-review

#8327 Support enforced web flow authentication on Dotcom
  app/src/lib/api.ts
  app/src/lib/stores/sign-in-store.ts
  app/src/ui/lib/authentication-form.tsx
  app/src/ui/lib/sign-in.tsx
  app/src/ui/sign-in/sign-in.tsx
Labels: ready-for-review, time-sensitive

#8310 Surface errors from branch creation to user
  app/src/lib/git/branch.ts
Labels: ready-for-review

#8335 Pre-fill user name and email in configure Git step in Welcome Wizard (again)
  app/src/lib/email.ts
  app/src/ui/lib/configure-git-user.tsx
  app/src/ui/preferences/accounts.tsx
  app/src/ui/preferences/preferences.tsx
  app/test/unit/email-test.ts
Labels: epic:onboarding, ready-for-review

#8331 [Onboarding tutorial] Implement functionality for exiting and resuming tutorial
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/helpers/tutorial-assessor.ts
  app/src/models/popup.ts
  app/src/models/tutorial-step.ts
  app/src/ui/app.tsx
  app/src/ui/blank-slate/blank-slate.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/repository.tsx
  app/src/ui/tutorial/confirm-exit-tutorial.tsx
  app/src/ui/tutorial/index.ts
  app/src/ui/tutorial/tutorial-panel.tsx
  app/styles/ui/onboarding-tutorial/_right-panel.scss
Labels: epic:onboarding, ready-for-review, time-sensitive

#8085 Carry over untracked files during branch creation that results in a conflict
  app/src/lib/git/stash.ts
  app/src/lib/status.ts
  app/src/lib/stores/app-store.ts
  app/test/unit/git/stash-test.ts
Labels: epic:stashing, ready-for-review

#8320 [Onboarding tutorial] Add "Welcome" and "You're done!" panes
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/helpers/tutorial-assessor.ts
  app/src/models/popup.ts
  app/src/models/tutorial-step.ts
  app/src/ui/app.tsx
  app/src/ui/blank-slate/blank-slate.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/repository.tsx
  app/src/ui/tutorial-panel/index.ts
  app/src/ui/tutorial/confirm-exit-tutorial.tsx
  app/src/ui/tutorial/done.tsx
  app/src/ui/tutorial/index.ts
  app/src/ui/tutorial/tutorial-panel.tsx
  app/src/ui/tutorial/welcome.tsx
  app/static/common/admin-mentoring.svg
  app/static/common/code.svg
  app/static/common/explore.svg
  app/static/common/file-directory.svg
  app/static/common/github-for-business.svg
  app/static/common/github-for-teams.svg
  app/static/common/organized-by-project-status.svg
  app/static/common/repo-template.svg
  app/styles/_ui.scss
  app/styles/ui/changes/_blankslate-action.scss
  app/styles/ui/changes/_no-changes.scss
  app/styles/ui/onboarding-tutorial/_right-panel.scss
  app/styles/ui/onboarding-tutorial/_welcome.scss
Labels: epic:onboarding, ready-for-review, time-sensitive

#8348 2.2.0-beta2 release
  app/package.json
  changelog.json
Labels: ready-for-review

#8340 Request additional workflow scope on GitHub.com
  app/src/lib/api.ts
Labels: ready-for-review

#8359 Completed editor step description
  app/src/ui/tutorial/tutorial-panel.tsx
Labels: epic:onboarding, ready-for-review

#8361 Tweak responsive styles for welcome pane
  app/styles/ui/onboarding-tutorial/_welcome.scss
Labels: epic:onboarding, ready-for-review

#8358 Don't say that the repository already exists unless we're sure about it
  app/src/lib/http.ts
  app/src/ui/blank-slate/create-tutorial-repository-dialog.tsx
Labels: ready-for-review

#8364 [Onboarding tutorial] Retain commit summary placeholder in tutorial repo
  app/src/ui/changes/changes-list.tsx
  app/src/ui/changes/commit-message.tsx
Labels: epic:onboarding, ready-for-review

#8290 Fix file path truncation in merge conflicts dialog
  app/src/ui/dialog/dialog.tsx
  app/src/ui/lib/conflicts/unmerged-file.tsx
  app/src/ui/lib/path-text.tsx
Labels: ready-for-review

#8375 Resume tutorial if new repo has been added
  app/src/lib/stores/helpers/tutorial-assessor.ts
Labels: epic:onboarding, ready-for-review

#8365 Feature/tutorial welcome revisions
  app/src/ui/tutorial/done.tsx
  app/static/common/file-directory.svg
  app/static/common/repo-template.svg
  app/styles/_variables.scss
  app/styles/themes/_dark.scss
  app/styles/ui/changes/_blankslate-action.scss
Labels: epic:onboarding, ready-for-review

#8370 [onboarding] metrics revision + addition
  app/src/lib/stats/stats-database.ts
  app/src/lib/stats/stats-store.ts
  app/src/lib/stores/app-store.ts
Labels: epic:onboarding, ready-for-review
