Repository desktop/desktop, pull requests merged in 2019-04, with the labels that each got.

#7151 chore: backport fixes from rebase dialog to merge dialog
  app/src/ui/merge-branch/merge.tsx
  app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx
  app/styles/ui/dialogs/_merge-conflicts.scss
  app/styles/ui/dialogs/_merge.scss
Labels: ready-for-review

#7117 move rebase flow to a multi-dialog flow
  app/src/lib/git/rebase.ts
  app/src/lib/rebase.ts
  app/src/lib/stores/app-store.ts
  app/src/models/popup.ts
  app/src/models/progress.ts
  app/src/models/rebase-flow-state.ts
  app/src/models/rebase.ts
  app/src/ui/app.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/dispatcher/error-handlers.ts
  app/src/ui/rebase/choose-branch.tsx
  app/src/ui/rebase/confirm-abort-dialog.tsx
  app/src/ui/rebase/confirm-force-push.tsx
  app/src/ui/rebase/index.ts
  app/src/ui/rebase/progress-dialog.tsx
  app/src/ui/rebase/rebase-flow.tsx
  app/src/ui/rebase/show-conflicted-files-dialog.tsx
  app/styles/_variables.scss
  app/styles/ui/_dialog.scss
  app/styles/ui/dialogs/rebase-progress.scss
  app/test/unit/format-test.ts
Labels: ready-for-review

#7175 plumbing to get rebase progress and setup for use in the app
  app/src/lib/git/merge.ts
  app/src/lib/git/rebase.ts
  app/src/lib/git/rev-list.ts
  app/src/lib/merge-tree-parser.ts
  app/src/lib/stores/app-store.ts
  app/src/models/commit.ts
  app/src/models/computed-action.ts
  app/src/models/merge.ts
  app/src/models/rebase.ts
  app/src/ui/history/merge-call-to-action-with-conflicts.tsx
  app/src/ui/history/merge-status-header.tsx
  app/src/ui/merge-branch/merge.tsx
  app/src/ui/rebase/progress-dialog.tsx
  app/src/ui/rebase/rebase-flow.tsx
  app/test/helpers/repository-builder-long-rebase-test.ts
  app/test/helpers/repository-builder-rebase-test.ts
  app/test/unit/git/parse-merge-result-test.ts
  app/test/unit/git/rebase/progress-test.ts
  docs/technical/rebase-flow.md
Labels: ready-for-review

#7174 Fix tooltips for octicons
  app/src/ui/octicons/octicon.tsx
Labels: ready-for-review

#7196 refresh repository state after rebase completed
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/rebase/rebase-flow.tsx
Labels: ready-for-review

#7192 add escape hatch notes at start of rebase attempt
  app/src/ui/dispatcher/dispatcher.ts
Labels: ready-for-review

#7197 enable rule to warn about Buffer constructor usage
  .eslintrc.yml
  app/src/ui/diff/syntax-highlighting/index.ts
Labels: ready-for-review, tech-debt

#7204 azure pipelines builds all PRs and only development branch
  azure-pipelines.yml
Labels: infrastructure, ready-for-review

#7199 bail out of rendering a remote action in the NoChanges view after a rebase
  app/src/ui/changes/no-changes.tsx
Labels: ready-for-review

#7182 Add all foundation stash functions needed to support stashing in the app
  app/src/lib/git/stash.ts
  app/test/unit/git/stash-test.ts
Labels: ready-for-review

#7167 preview the number of commits that will be rebased
  app/src/lib/git/rebase.ts
  app/src/lib/rebase.ts
  app/src/lib/stores/app-store.ts
  app/src/models/progress.ts
  app/src/models/rebase-flow-state.ts
  app/src/models/rebase.ts
  app/src/ui/app.tsx
  app/src/ui/banners/rebase-conflicts-banner.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/history/merge-call-to-action-with-conflicts.tsx
  app/src/ui/history/merge-status-header.tsx
  app/src/ui/lib/action-status-icon.tsx
  app/src/ui/merge-branch/merge.tsx
  app/src/ui/rebase/choose-branch.tsx
  app/src/ui/rebase/progress-dialog.tsx
  app/src/ui/rebase/rebase-flow.tsx
  app/styles/_ui.scss
  app/styles/_variables.scss
  app/styles/themes/_dark.scss
  app/styles/ui/rebase-status.scss
Labels: ready-for-review

#7200 shorten recent repos list to three
  app/src/lib/stores/app-store.ts
Labels: ready-for-review

#7212 Fix issue where next steps would display horizontal scroll bar while loading
  app/styles/ui/changes/_no-changes.scss
Labels: ready-for-review

#7203 lift state out of rebase flow components to live in repository state
  app/src/lib/app-state.ts
  app/src/lib/git/rebase.ts
  app/src/lib/git/status.ts
  app/src/lib/rebase.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/repository-state-cache.ts
  app/src/lib/stores/updates/changes-state.ts
  app/src/models/popup.ts
  app/src/models/rebase-flow-step.ts
  app/src/models/rebase.ts
  app/src/ui/app.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/dispatcher/error-handlers.ts
  app/src/ui/rebase/choose-branch.tsx
  app/src/ui/rebase/confirm-abort-dialog.tsx
  app/src/ui/rebase/progress-dialog.tsx
  app/src/ui/rebase/rebase-flow.tsx
  app/src/ui/rebase/show-conflicted-files-dialog.tsx
  app/test/helpers/changes-state-helper.ts
  app/test/unit/git/rebase/detect-conflict-test.ts
  app/test/unit/git/rebase/progress-test.ts
  app/test/unit/stores/updates/update-conflict-state-test.ts
Labels: ready-for-review, tech-debt

#7209 ensure conflicts popup and banner are cleaned up if conflicts no longer exist
  app/src/lib/stores/app-store.ts
  app/src/ui/dispatcher/dispatcher.ts
Labels: ready-for-review

#7191 make new rebase flow available for beta users
  app/src/lib/feature-flag.ts
Labels: ready-for-review

#7236 Add Resx Highlighter Support
  app/src/highlighter/index.ts
Labels: ready-for-review

#7253 [Stashing] Update desktop stash marker
  app/src/lib/git/stash.ts
  app/src/lib/stores/app-store.ts
  app/test/unit/git/stash-test.ts
Labels: ready-for-review

#7219 [Stashing] Adds workflow that allows users to take changes with them to new branch
  app/src/lib/git/stash.ts
  app/src/lib/stores/app-store.ts
  app/src/models/uncommitted-changes-strategy.ts
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/stash-and-switch-branch-dialog.tsx
  app/test/unit/git/stash-test.ts
Labels: ready-for-review

#6944 add correct name and role
  app/src/ui/dialog/header.tsx
Labels: ready-for-review

#6663 Initiate cloning by hitting enter on a clonable repository list selection
  app/src/ui/blank-slate/blank-slate.tsx
  app/src/ui/clone-repository/clone-github-repository.tsx
  app/src/ui/clone-repository/clone-repository.tsx
Labels: accessibility, ready-for-review

#6300 disable revert commit if comparing a branch's 'behind' commits
  app/src/ui/history/commit-list-item.tsx
  app/src/ui/history/commit-list.tsx
  app/src/ui/history/compare.tsx
Labels: ready-for-review

#7258 Only render pr bubble if there are PRs
  app/src/ui/branches/branches-container.tsx
Labels: ready-for-review

#7162 Ensure that the filter text box yields space for the Add button
  app/styles/ui/_filter-list.scss
  app/styles/ui/_repository-list.scss
Labels: ready-for-review

#7230 [Stashing] Notify user that an existing stash will be overwritten
  app/src/lib/stores/app-store.ts
  app/src/models/popup.ts
  app/src/ui/app.tsx
  app/src/ui/stash-changes/overwrite-stashed-changes-dialog.tsx
  app/src/ui/stash-changes/stash-and-switch-branch-dialog.tsx
  app/styles/ui/_dialog.scss
  app/styles/ui/dialogs/_stash-changes.scss
Labels: ready-for-review

#7213 [Stashing] Stash Diff Viewer
  app/src/lib/app-state.ts
  app/src/lib/git/stash.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/git-store.ts
  app/src/lib/stores/repository-state-cache.ts
  app/src/models/stash-entry.ts
  app/src/ui/app.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/repository.tsx
  app/src/ui/stashing/index.ts
  app/src/ui/stashing/stash-diff-viewer.tsx
  app/styles/_ui.scss
  app/styles/ui/_stash-diff-viewer.scss
  app/test/helpers/changes-state-helper.ts
  app/test/unit/git/stash-test.ts
Labels: ready-for-review, time-sensitive

#7242 warn before rebase if operation requires a force push
  app/src/lib/git/rebase.ts
  app/src/lib/stores/app-store.ts
  app/src/models/rebase-flow-step.ts
  app/src/ui/app.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/rebase/choose-branch.tsx
  app/src/ui/rebase/rebase-flow.tsx
  app/src/ui/rebase/warn-force-push-dialog.tsx
  app/test/helpers/git.ts
  app/test/helpers/tip.ts
  app/test/unit/git/pull/ahead-and-behind-test.ts
  app/test/unit/git/pull/only-ahead-test.ts
  app/test/unit/git/pull/only-behind-test.ts
  app/test/unit/git/rebase/detect-conflict-test.ts
  app/test/unit/git/rebase/progress-test.ts
  app/test/unit/git/stash-test.ts
Labels: ready-for-review

#7267 [Stashing] Only load stash files when necessary
  app/src/lib/stores/git-store.ts
Labels: ready-for-review

#7210 [Stashing] Adds ability to stash changes
  app/src/lib/app-state.ts
  app/src/lib/feature-flag.ts
  app/src/lib/git/stash.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/git-store.ts
  app/src/lib/stores/repository-state-cache.ts
  app/src/models/popup.ts
  app/src/models/stash-entry.ts
  app/src/models/uncommitted-changes-strategy.ts
  app/src/ui/app.tsx
  app/src/ui/changes/changes-list.tsx
  app/src/ui/changes/sidebar.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/lib/list/list-row.tsx
  app/src/ui/repository.tsx
  app/src/ui/stash-changes/overwrite-stashed-changes-dialog.tsx
  app/src/ui/stash-changes/stash-and-switch-branch-dialog.tsx
  app/src/ui/stashing/index.ts
  app/src/ui/stashing/stash-diff-viewer.tsx
  app/styles/_ui.scss
  app/styles/ui/_dialog.scss
  app/styles/ui/_stash-diff-viewer.scss
  app/styles/ui/changes/_changes-list.scss
  app/styles/ui/dialogs/_stash-changes.scss
  app/test/helpers/changes-state-helper.ts
  app/test/unit/git/stash-test.ts
Labels: ready-for-review, time-sensitive

#7300 [stashing] Get changed files for stash
  app/src/lib/git/log.ts
  app/src/lib/git/stash.ts
  app/src/lib/stores/git-store.ts
Labels: ready-for-review, time-sensitive

#7295 [Stashing] Prompt to stash when creating new branch
  app/src/lib/git/branch.ts
  app/src/lib/stores/app-store.ts
  app/src/ui/create-branch/create-branch-dialog.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/test/unit/git/branch-test.ts
  app/test/unit/git/checkout-test.ts
  app/test/unit/git/reflog-test.ts
Labels: ready-for-review, time-sensitive

#7305 make FileList support generic FileChange in props
  app/src/ui/history/file-list.tsx
  app/src/ui/history/selected-commit.tsx
  app/src/ui/stashing/stash-diff-viewer.tsx
Labels: ready-for-review, tech-debt

#7259 Optional page size and continue predicate for API fetchAll method
  app/src/lib/api.ts
Labels: ready-for-review

#7302 conflicts - add space between button label and octicon
  app/styles/ui/dialogs/_merge-conflicts.scss
Labels: ready-for-review, tech-debt

#7307 disable context menu when viewing files in diff
  app/src/ui/history/file-list.tsx
  app/src/ui/history/selected-commit.tsx
  app/src/ui/repository.tsx
  app/src/ui/stashing/stash-diff-viewer.tsx
Labels: ready-for-review

#7315 [Stashing] Changed the button title from Clear to Discard
  app/src/ui/stashing/stash-diff-viewer.tsx
Labels: ready-for-review

#7313 [Stashing] A select selection
  app/src/lib/app-state.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/git-store.ts
  app/src/lib/stores/repository-state-cache.ts
  app/src/lib/stores/updates/changes-state.ts
  app/src/ui/app.tsx
  app/src/ui/changes/changes-list.tsx
  app/src/ui/changes/sidebar.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/repository.tsx
  app/src/ui/stashing/stash-diff-viewer.tsx
  app/test/helpers/changes-state-helper.ts
  app/test/unit/stores/updates/update-changed-files-test.ts
Labels: ready-for-review, time-sensitive

#7326 [Stashing] Don't delete existing stash when taking changes to new branch
  app/src/lib/stores/app-store.ts
  app/src/ui/dispatcher/dispatcher.ts
Labels: ready-for-review, time-sensitive

#7316 show untracked files in stash
  app/src/lib/git/stash.ts
Labels: ready-for-review, time-sensitive

#7325 [stashing] enable stashing for beta
  app/src/lib/feature-flag.ts
Labels: ready-for-review, time-sensitive

#7301 [Stashing] Address button order of stash diff viewer for Windows
  app/src/ui/stashing/stash-diff-viewer.tsx
Labels: ready-for-review

#7277 add "keyboard shortcuts" menu item to Help menu
  app/src/main-process/menu/build-default-menu.ts
Labels: ready-for-review

#7331 1.7.0-beta3 release
  app/package.json
  changelog.json
Labels: ready-for-review

#7335 Dismiss popup when new branch creation is completed
  app/src/lib/stores/app-store.ts
Labels: ready-for-review, time-sensitive

#7243 show "force push" label after rebase which requires it
  app/src/lib/rebase.ts
  app/src/lib/stores/app-store.ts
  app/src/main-process/menu/build-default-menu.ts
  app/src/main-process/menu/menu-event.ts
  app/src/ui/app.tsx
  app/src/ui/changes/no-changes.tsx
  app/src/ui/toolbar/push-pull-button.tsx
Labels: ready-for-review, time-sensitive

#7261 ensure manual resolution choices are in sync with rebase flow
  app/src/lib/stores/app-store.ts
Labels: ready-for-review, time-sensitive

#7336 1.7.0-beta4
  app/package.json
  changelog.json
Labels: ready-for-review, time-sensitive

#7265 Handle text diff component unmount in the middle of syntax highlighting
  app/src/ui/diff/text-diff.tsx
Labels: ready-for-review

#7345 Update setup docs
  docs/contributing/setup-linux.md
  docs/contributing/setup-macos.md
  docs/contributing/setup-windows.md
  docs/contributing/setup.md
Labels: docs, ready-for-review

#7330 refactor tests to ensure assertions are always run
  app/test/unit/stores/updates/update-changed-files-test.ts
Labels: ready-for-review, tech-debt

#7338 cleanup rebase if unable to start the operation
  app/src/ui/dispatcher/dispatcher.ts
Labels: ready-for-review

#7343 check if the target branch has already been rebased
  app/src/lib/stores/app-store.ts
Labels: ready-for-review

#7379 [stashing] small wording tweak
  app/src/ui/stash-changes/stash-and-switch-branch-dialog.tsx
Labels: ready-for-review

#7346 keep the branch name in memory while the rebase is in progress
  app/src/lib/stores/app-store.ts
  app/src/ui/changes/continue-rebase.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/rebase/rebase-flow.tsx
Labels: ready-for-review

#7381 update node and python versions in versioning config
  .nvmrc
  .tool-versions
Labels: infrastructure, ready-for-review

#7364 Update confirm dialog when overwriting a previous stash
  app/src/ui/stash-changes/overwrite-stashed-changes-dialog.tsx
Labels: ready-for-review

#7380 refactor status to detect conflicts from stash
  app/src/lib/git/status.ts
Labels: ready-for-review

#7387 [stashing] alphabetical sort for diff stash viewer
  app/src/lib/git/stash.ts
Labels: epic:stashing, ready-for-review

#7382 Add "View stash entry" action to suggested next steps
  app/src/lib/menu-update.ts
  app/src/lib/stores/app-store.ts
  app/src/main-process/menu/build-default-menu.ts
  app/src/main-process/menu/menu-event.ts
  app/src/main-process/menu/menu-ids.ts
  app/src/ui/app.tsx
  app/src/ui/changes/no-changes.tsx
  app/src/ui/dispatcher/dispatcher.ts
Labels: epic:stashing, ready-for-review, time-sensitive

#7393 Update verbiage for leaving changes on current branch vs bringing them to new branch
  app/src/ui/stash-changes/stash-and-switch-branch-dialog.tsx
  app/styles/ui/_vertical-segmented-control.scss
Labels: epic:stashing, ready-for-review

#7391 rebase flow - update copy when choosing branch
  app/src/ui/rebase/choose-branch.tsx
Labels: epic:rebase, ready-for-review

#7363 [Stashing] Adds a bit of explanatory text for restore button
  app/src/ui/repository.tsx
  app/src/ui/stashing/stash-diff-viewer.tsx
  app/styles/ui/_stash-diff-viewer.scss
Labels: epic:stashing, ready-for-review, time-sensitive

#7351 handle warnings if stash creation encounters permission issue
  app/src/lib/git/stash.ts
Labels: epic:stashing, ready-for-review

#7362 [Stashing] Confirm before discarding stash
  app/src/models/popup.ts
  app/src/ui/app.tsx
  app/src/ui/stashing/confirm-discard-stash.tsx
  app/src/ui/stashing/stash-diff-viewer.tsx
Labels: epic:stashing, ready-for-review

#7392 fix stash diff viewer button order (for mac)
  app/src/ui/stashing/stash-diff-viewer.tsx
Labels: epic:stashing, ready-for-review

#7377 lock file state when in rebase conflicts
  app/src/ui/changes/changed-file.tsx
  app/src/ui/changes/changes-list.tsx
  app/src/ui/changes/continue-rebase.tsx
  app/styles/ui/changes/_continue-rebase.scss
Labels: epic:rebase, ready-for-review

#7398 1.7.0 beta5 Release
  app/package.json
  changelog.json
Labels: ready-for-review

#7399 set an upper bound on our supported Node for now
  package.json
Labels: infrastructure, ready-for-review, tech-debt

#7378 experiment with using labels to track epics
  docs/process/labels.md
Labels: docs, ready-for-review

#7352 make stderr and stdout more explicit
  app/src/lib/git/core.ts
Labels: ready-for-review, tech-debt

#7410 Prevent re-render while in the middle of stashing and checking out
  app/src/ui/stash-changes/stash-and-switch-branch-dialog.tsx
Labels: epic:stashing, ready-for-review

#7406 Fix: Cannot use `esc` key to close Repository list and Branch list
  app/src/ui/toolbar/dropdown.tsx
Labels: ready-for-review

#7428 actually disable restore stash button when changes present
  app/src/ui/stashing/stash-diff-viewer.tsx
Labels: epic:stashing, ready-for-review

#7427 get last stored value for stash pane width at launch
  app/src/lib/stores/app-store.ts
Labels: ready-for-review

#7407 smoother transitions when previewing rebase
  app/src/lib/app-state.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/repository-state-cache.ts
  app/src/ui/app.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/rebase/choose-branch.tsx
  app/src/ui/rebase/rebase-flow.tsx
Labels: epic:rebase, ready-for-review

#7355 bump typescript to latest
  app/src/lib/stores/app-store.ts
  app/src/ui/clone-repository/clone-repository.tsx
  package.json
  yarn.lock
Labels: ready-for-review, tech-debt

#7263 [Stashing] Replace ListRow component
  app/src/ui/changes/changes-list.tsx
  app/src/ui/lib/list/list-row.tsx
  app/styles/_mixins.scss
  app/styles/mixins/_list-item.scss
  app/styles/ui/_list.scss
  app/styles/ui/changes/_changes-list.scss
Labels: epic:stashing, ready-for-review, tech-debt
