Repository desktop/desktop, pull requests merged in 2019-06, with the labels that each got.

#7649 update auth messaging
  app/src/lib/git/core.ts
Labels: ready-for-review

#7659 extract internal type from getStashes API
  app/src/lib/git/stash.ts
Labels: ready-for-review, tech-debt

#7663 Remove url and replaces with text links
  docs/process/testing.md
Labels: docs, ready-for-review

#7670 Upgrade node-sass to 4.12.0
  package.json
  yarn.lock
Labels: infrastructure, ready-for-review

#7656 release notes for the next big release
  changelog.json
Labels: ready-for-review

#7688 [Hotfix] Pull request update crash for non-db GitHubRepositories
  app/src/lib/stores/pull-request-store.ts
  changelog.json
Labels: ready-for-review

#7693 Additional debug data in crash reports
  app/src/main-process/main.ts
  app/src/ui/index.tsx
  changelog.json
Labels: ready-for-review

#7699 Fix account identity mismatch
  app/src/lib/stores/accounts-store.ts
  app/src/lib/stores/api-repositories-store.ts
  app/src/lib/stores/app-store.ts
  app/src/ui/app.tsx
  app/src/ui/blank-slate/blank-slate.tsx
  changelog.json
Labels: ready-for-review

#7707 2.0.4-beta0
  app/package.json
  changelog.json
Labels: ready-for-review

#7709 merge the release branch back into trunk
  app/package.json
  app/src/lib/feature-flag.ts
  app/src/lib/stores/accounts-store.ts
  app/src/lib/stores/api-repositories-store.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/pull-request-store.ts
  app/src/main-process/main.ts
  app/src/ui/app.tsx
  app/src/ui/blank-slate/blank-slate.tsx
  app/src/ui/index.tsx
  changelog.json
Labels: ready-for-review

#7650 Discard all shortcut
  app/src/main-process/menu/build-default-menu.ts
  app/src/ui/repositories-list/repository-list-item.tsx
Labels: ready-for-review

#7629 improve the dev-time experience of testing branch pruning
  app/src/lib/git/reflog.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/helpers/branch-pruner.ts
  app/src/main-process/menu/build-default-menu.ts
  app/src/main-process/menu/menu-event.ts
  app/src/ui/app.tsx
  app/test/unit/git/reflog-test.ts
Labels: infrastructure, ready-for-review

#7504 add timing API to understand how long important actions take
  app/src/ui/branches/branches-container.tsx
  app/src/ui/changes/commit-message.tsx
  app/src/ui/create-branch/create-branch-dialog.tsx
  app/src/ui/lib/timing.ts
  app/src/ui/stash-changes/stash-and-switch-branch-dialog.tsx
Labels: infrastructure, ready-for-review

#7662 Add description to Arguments in writeDefaultReadme
  app/src/ui/add-repository/create-repository.tsx
  app/src/ui/add-repository/write-default-readme.ts
  app/test/unit/write-default-readme-test.ts
Labels: ready-for-review

#7681 update some eslint dependencies
  .eslintrc.yml
  package.json
  yarn.lock
Labels: infrastructure, ready-for-review, tech-debt

#7727 Update roadmap post 2.0 ship
  docs/process/roadmap.md
Labels: docs, ready-for-review

#7767 Fix select all keyboard shortcut in lists on Windows
  app/src/ui/lib/list/list.tsx
Labels: ready-for-review

#7754 refresh should handle when the branch API is unavailable
  app/src/lib/api.ts
Labels: ready-for-review

#7771 stop caching eslint cache for now on Appveyor
  appveyor.yml
Labels: infrastructure, ready-for-review

#7683 Disable 'Discard' and 'Restore' buttons while performing action
  app/src/ui/stashing/stash-diff-header.tsx
  app/src/ui/stashing/stash-diff-viewer.tsx
Labels: ready-for-review

#7766 Add back "Discard all changes" context menu
  app/src/ui/changes/changes-list.tsx
Labels: ready-for-review

#7770 2.0.4 release
  .travis.yml
  app/package.json
  changelog.json
Labels: ready-for-review

#7596 add section about the installer log locations
  docs/installation.md
Labels: docs, ready-for-review

#7757 Dont change message while restoring
  app/src/ui/stashing/stash-diff-header.tsx
Labels: ready-for-review

#7708 ensure the current window is provided when launching showOpenDialog
  app/src/ui/add-repository/add-existing-repository.tsx
  app/src/ui/add-repository/create-repository.tsx
  app/src/ui/clone-repository/clone-repository.tsx
  app/src/ui/dispatcher/dispatcher.ts
Labels: ready-for-review

#6929 decouple component from using AppStore as a prop
  app/src/lib/app-state.ts
  app/src/lib/stores/app-store.ts
  app/src/ui/app.tsx
  app/src/ui/welcome/welcome.tsx
Labels: ready-for-review, tech-debt

#7461 update suggested VS Code extensions
  .vscode/extensions.json
Labels: infrastructure, ready-for-review, tech-debt

#7793 add rebaseCurrentBranchMenuCount metric to list
  docs/process/metrics.md
Labels: docs, ready-for-review

#7782 restore caches for CI providers
  .travis.yml
  appveyor.yml
Labels: infrastructure, ready-for-review

#7756 Add notes on checking haystack for final beta
  docs/process/releasing-updates.md
Labels: docs, ready-for-review

#7794 drop unnecessary async modifiers from public API for StatsStore
  app/src/lib/stats/stats-store.ts
Labels: ready-for-review, tech-debt

#7784 Add key property for all dialogs to ensure transitions
  app/src/ui/app.tsx
Labels: ready-for-review, tech-debt

#7786 upgrade fs-admin to 3.0.1
  app/package.json
  app/yarn.lock
Labels: dependencies, electron, infrastructure, ready-for-review

#7804 update vscode settings to integrate with eslint
  .vscode/settings.json
Labels: infrastructure, ready-for-review

#7803 add measure for rebase completion without conflicts
  app/src/lib/stats/stats-database.ts
  app/src/lib/stats/stats-store.ts
  app/src/lib/stores/updates/changes-state.ts
  app/src/ui/dispatcher/dispatcher.ts
  app/test/unit/stores/updates/update-conflict-state-test.ts
  docs/process/metrics.md
Labels: docs, ready-for-review

#7729 Update references to "Enterprise" to "Enterprise Server"
  app/src/lib/api.ts
  app/src/lib/email.ts
  app/src/lib/enterprise.ts
  app/src/lib/find-account.ts
  app/src/lib/gravatar.ts
  app/src/lib/http.ts
  app/src/lib/stats/stats-database.ts
  app/src/lib/stats/stats-store.ts
  app/src/lib/stores/sign-in-store.ts
  app/src/lib/web-flow-committer.ts
  app/src/models/account.ts
  app/src/models/author.ts
  app/src/ui/blank-slate/blank-slate.tsx
  app/src/ui/clone-repository/clone-repository.tsx
  app/src/ui/lib/authentication-form.tsx
  app/src/ui/lib/enterprise-server-entry.tsx
  app/src/ui/lib/enterprise-validate-url.ts
  app/src/ui/preferences/accounts.tsx
  app/src/ui/publish-repository/publish.tsx
  app/src/ui/sign-in/sign-in.tsx
  app/src/ui/terms-and-conditions/terms-and-conditions.tsx
  app/src/ui/untrusted-certificate/untrusted-certificate.tsx
  app/src/ui/usage-stats-change/usage-stats-change.tsx
  app/src/ui/welcome/sign-in-enterprise.tsx
  app/src/ui/welcome/start.tsx
  app/test/unit/find-account-test.ts
  docs/process/metrics.md
Labels: ready-for-review

#7838 update last prune timestamp every time we look for branches to prune
  app/src/lib/stores/helpers/branch-pruner.ts
Labels: epic:branch-pruner, ready-for-review

#7836 use xcode 9.4.1 image and avoid nvm for circleci
  .circleci/config.yml
Labels: infrastructure, ready-for-review

#7846 add loadBranches tests
  app/test/helpers/repository-scaffolding.ts
  app/test/unit/git-store-test.ts
Labels: ready-for-review

#7825 new feature flag for protected branches UI work
  app/src/lib/feature-flag.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/repositories-store.ts
Labels: ready-for-review, tech-debt

#7845 updated tab header to "Enterprise Server" label
  app/src/ui/blank-slate/blank-slate.tsx
Labels: ready-for-review

#7835 increase clone repo width
  app/styles/ui/_add-repository.scss
Labels: ready-for-review

#7826 first pass at UI for warning about protected branches
  app/src/lib/app-state.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/repositories-store.ts
  app/src/lib/stores/repository-state-cache.ts
  app/src/models/popup.ts
  app/src/ui/app.tsx
  app/src/ui/branches/branches-container.tsx
  app/src/ui/changes/changes-list.tsx
  app/src/ui/changes/commit-message.tsx
  app/src/ui/changes/protected-branch-warning.tsx
  app/src/ui/changes/sidebar.tsx
  app/src/ui/create-branch/create-branch-dialog.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/toolbar/branch-dropdown.tsx
  app/styles/ui/_changes.scss
  app/styles/ui/changes/_protected-branch.scss
  app/test/helpers/changes-state-helper.ts
  app/test/unit/branch-pruner-test.ts
  app/test/unit/repositories-store-test.ts
Labels: ready-for-review

#7765 pass the current state when emitting show event from BrowserWindow
  app/src/lib/stores/app-store.ts
  app/src/lib/window-state.ts
  app/src/ui/window/window-controls.tsx
Labels: ready-for-review

#7839 use remotes info in branch pruning
  app/src/lib/git/branch.ts
  app/src/lib/stores/helpers/branch-pruner.ts
  app/test/helpers/repository-builder-branch-pruner.ts
  app/test/unit/branch-pruner-test.ts
Labels: epic:branch-pruner, ready-for-review

#7821 Add support for WSL shell in Windows
  app/src/lib/feature-flag.ts
  app/src/lib/shells/win32.ts
Labels: ready-for-review

#7809 Fix history compare branch selection
  app/src/ui/branches/branch-list.tsx
  app/src/ui/history/compare.tsx
  app/src/ui/lib/filter-list.tsx
Labels: ready-for-review

#7869 2.1.0-beta1 release
  app/package.json
  changelog.json
Labels: ready-for-review

#7507 upgrade infrastructure to node 10
  .circleci/config.yml
  .travis.yml
  appveyor.yml
  azure-pipelines.yml
  changelog.json
  package.json
  yarn.lock
Labels: infrastructure, ready-for-review

#7877 2.1.0-beta2 release
  app/package.json
  app/src/lib/feature-flag.ts
  changelog.json
Labels: ready-for-review

#7880 template updates for `bug report` and `problems to raise`
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/problem-to-raise.md
Labels: meta, ready-for-review

#7865 Out of order state update in create repository dialog
  app/src/ui/add-repository/create-repository.tsx
Labels: ready-for-review

#7866 Text search in diffs
  app/src/ui/diff/code-mirror-host.tsx
  app/src/ui/diff/text-diff.tsx
  app/styles/_vendor.scss
  app/styles/ui/_codemirror.scss
  app/styles/ui/_diff.scss
Labels: ready-for-review

#7890 Revert "enable branch protection warning on beta"
  app/src/lib/feature-flag.ts
Labels: ready-for-review

#7892 2.1.0-beta3
  app/package.json
  changelog.json
Labels: ready-for-review
