Repository desktop/desktop, pull requests merged in 2019-12, with the labels that each got.

#8255 Adding Xcode as external editor
  app/src/lib/editors/darwin.ts
Labels: integrations, macOS, ready-for-review

#8678 Improve verbiage for deleting branch with PR
  app/src/ui/delete-branch/delete-pull-request-dialog.tsx
Labels: ready-for-review

#8636 Update Code Mirror and CodeMirror Types
  app/package.json
  app/styles/ui/_diff.scss
  app/yarn.lock
  package.json
  yarn.lock
Labels: ready-for-review

#8818 Extract pull request matching helpers
  app/src/lib/helpers/pull-request-matching.ts
  app/src/lib/stores/app-store.ts
Labels: epic:fork, tech-debt
