Repository desktop/desktop, pull requests merged in 2019-03, with the labels that each got.

#6968 [rebase] bail out of querying config when feature is not enabled
  app/src/lib/stores/git-store.ts
Labels: ready-for-review

#6953 Authentication Form Validation - Checks Both Username and Password
  app/src/ui/generic-git-auth/generic-git-auth.tsx
Labels: ready-for-review

#6971 enable pull with rebase for production
  app/src/lib/feature-flag.ts
Labels: ready-for-review

#6984 provide a better description when rebase in progress
  app/src/ui/app.tsx
  app/src/ui/toolbar/push-pull-button.tsx
Labels: ready-for-review

#6992 disable push menu item when on detached HEAD
  app/src/lib/menu-update.ts
Labels: ready-for-review

#6993 fix: correct path to coverage report file
  package.json
Labels: infrastructure, ready-for-review

#7005 disable create branch menu item when dealing with rebase conflicts
  app/src/lib/menu-update.ts
Labels: ready-for-review

#7009 1.6.3-beta4 release!
  app/package.json
  changelog.json
Labels: ready-for-review

#6902 Keytar 4.4.1 Upgrade
  app/package.json
  app/yarn.lock
Labels: ready-for-review

#4147 Ensure files marked for deletion in index are actually deleted
  app/src/lib/git/update-index.ts
  app/test/unit/git/commit-test.ts
Labels: ready-for-review

#6925 chore: Update electron-packager to latest version
  package.json
  yarn.lock
Labels: ready-for-review, tech-debt

#7010 1.6.3 release branch
  app/package.json
  app/src/lib/feature-flag.ts
  app/src/ui/index.tsx
  changelog.json
Labels: ready-for-review

#6988 clarify type signature for findDefaultRemote
  app/src/lib/stores/helpers/find-default-remote.ts
  app/test/unit/git/remote-test.ts
Labels: ready-for-review, tech-debt

#6948 Add stash entry type
  app/src/lib/git/stash.ts
Labels: ready-for-review

#7037 Minor type fix
  app/src/lib/git/core.ts
Labels: ready-for-review

#6922 chore: Upgrade moment to 2.24.0
  app/package.json
  app/yarn.lock
Labels: ready-for-review, tech-debt

#6961 [rebase] menu item and dialog to start rebase operation
  app/package.json
  app/src/lib/feature-flag.ts
  app/src/lib/git/core.ts
  app/src/lib/git/rebase.ts
  app/src/lib/menu-update.ts
  app/src/lib/stats/stats-database.ts
  app/src/lib/stats/stats-store.ts
  app/src/lib/stores/app-store.ts
  app/src/main-process/menu/build-default-menu.ts
  app/src/main-process/menu/menu-event.ts
  app/src/main-process/menu/menu-ids.ts
  app/src/models/popup.ts
  app/src/ui/app.tsx
  app/src/ui/banners/successful-rebase.tsx
  app/src/ui/dialog/dialog.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/rebase/rebase-branch-dialog.tsx
  app/src/ui/rebase/rebase-conflicts-dialog.tsx
  app/styles/ui/_dialog.scss
  app/styles/ui/dialogs/_rebase-conflicts.scss
  app/styles/ui/dialogs/_rebase.scss
  app/test/unit/git/rebase/detect-conflict-test.ts
  app/yarn.lock
Labels: ready-for-review

#6918 Upgrade Codemirror
  app/package.json
  app/yarn.lock
Labels: ready-for-review, tech-debt

#7062 Prevent feedback loop toggling repository missing flag
  app/src/lib/stores/app-store.ts
Labels: ready-for-review

#7027 Explicit refresh of PR list and avoid skeleton loading screen when we have PRs to show
  app/src/ui/branches/branches-container.tsx
  app/src/ui/branches/pull-request-list.tsx
  app/src/ui/branches/pull-requests-loading.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/styles/ui/_branches.scss
Labels: ready-for-review

#6986 ensure push goes to the right remote
  app/src/lib/stores/app-store.ts
  app/src/ui/app.tsx
Labels: ready-for-review

#6950 encode file path to each emoji when reading from cache
  app/src/lib/read-emoji.ts
Labels: ready-for-review

#6945 make loadAndCacheUser more resilient to bad input
  app/src/lib/api.ts
  app/src/lib/gravatar.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/github-user-store.ts
  app/src/models/publish-settings.ts
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/publish-repository/publish-repository.tsx
  app/test/unit/branch-pruner-test.ts
  app/test/unit/repositories-clone-grouping-test.ts
  app/test/unit/repositories-store-test.ts
Labels: ready-for-review

#7030 use shared components for merge and rebase conflicts
  app/src/ui/lib/conflicts/index.ts
  app/src/ui/lib/conflicts/render-functions.tsx
  app/src/ui/lib/conflicts/unmerged-file.tsx
  app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx
  app/src/ui/rebase/conflict-files-list.tsx
  app/src/ui/rebase/rebase-conflicts-dialog.tsx
  app/styles/ui/_dialog.scss
  app/styles/ui/dialogs/_merge-conflicts.scss
Labels: ready-for-review, tech-debt

#7063 1.6.4 hotfix release
  app/.npmrc
  app/package.json
  app/src/lib/feature-flag.ts
  app/src/ui/dispatcher/error-handlers.ts
  app/src/ui/index.tsx
  changelog.json
  package.json
  yarn.lock
Labels: ready-for-review

#7008 add more tests to clarify rebase behaviour
  app/src/lib/git/rebase.ts
  app/src/lib/stores/app-store.ts
  app/test/helpers/repository-builder-rebase-test.ts
  app/test/unit/git/rebase/detect-conflict-test.ts
Labels: ready-for-review

#7073 Enterprise users should be able to publish to an organization
  app/src/models/publish-settings.ts
  app/src/ui/publish-repository/publish-repository.tsx
  app/src/ui/publish-repository/publish.tsx
Labels: ready-for-review

#7086 bugfix: always pass in the configured org
  app/src/ui/publish-repository/publish.tsx
Labels: ready-for-review

#6972 review unit tests and make config setup more explicit
  app/test/helpers/local-config.ts
  app/test/unit/git/diff-test.ts
  app/test/unit/git/gitignore-test.ts
  app/test/unit/git/log-test.ts
  app/test/unit/git/pull/ahead-and-behind-test.ts
  app/test/unit/git/pull/only-ahead-test.ts
  app/test/unit/git/pull/only-behind-test.ts
  app/test/unit/git/status-test.ts
Labels: ready-for-review, tech-debt

#7090 FRR and issue triage updates
  docs/process/first-responder.md
  docs/process/issue-triage.md
Labels: docs, ready-for-review

#7095 use headerTitle in dialog title now it supports JSX
  app/src/ui/rebase/rebase-conflicts-dialog.tsx
Labels: ready-for-review, tech-debt

#7096 Don't crash when failing to create log file
  app/src/main-process/log.ts
Labels: ready-for-review

#7029 feat: Add visual feedback on Remove and Discard changes dialogs
  app/src/ui/discard-changes/discard-changes-dialog.tsx
  app/src/ui/remove-repository/confirm-remove-repository.tsx
Labels: ready-for-review

#6981 [rebase] enable `--force-with-lease` after rebasing
  app/src/lib/app-state.ts
  app/src/lib/git/push.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/repository-state-cache.ts
  app/src/models/popup.ts
  app/src/ui/app.tsx
  app/src/ui/changes/continue-rebase.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/preferences/advanced.tsx
  app/src/ui/preferences/preferences.tsx
  app/src/ui/rebase/confirm-force-push.tsx
  app/src/ui/rebase/rebase-branch-dialog.tsx
  app/src/ui/rebase/rebase-conflicts-dialog.tsx
  app/src/ui/toolbar/push-pull-button.tsx
Labels: ready-for-review

#6969 Copy commit message props to state using componentWillReceiveProps
  app/src/ui/changes/commit-message.tsx
Labels: ready-for-review

#6771 finish migration to using @typescript-eslint packages
  .eslintrc.yml
  app/src/highlighter/globals.d.ts
  app/src/lib/globals.d.ts
  app/src/lib/parse-app-url.ts
  app/src/lib/stores/helpers/ahead-behind-updater.ts
  app/src/ui/lib/author-input.tsx
  package.json
  script/globals.d.ts
  yarn.lock
Labels: infrastructure, ready-for-review

#7094 Add notes about ask-pass errors to known-issues.md
  docs/known-issues.md
Labels: docs, ready-for-review

#7087 propagate progress when performing a rebase
  app/src/lib/git/rebase.ts
  app/src/lib/progress/git.ts
  app/src/lib/stores/app-store.ts
  app/src/models/progress.ts
  app/src/models/rebase.ts
  app/src/ui/changes/continue-rebase.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/rebase/rebase-conflicts-dialog.tsx
Labels: ready-for-review

#7032 Add function that emulates `git stash list`
  app/src/lib/git/stash.ts
  app/test/unit/git/stash-test.ts
Labels: ready-for-review

#7082 1.6.5 hotfix
  app/package.json
  app/src/ui/publish-repository/publish.tsx
  changelog.json
Labels: ready-for-review

#7097 tell tslint inside VSCode to ignore definition files when linting
  .vscode/settings.json
Labels: infrastructure, ready-for-review

#7126 Fix mistaken classification of all crashes as being related to launch
  app/src/main-process/main.ts
Labels: ready-for-review

#7147 Add GitLab and Bitbucket authentication docs
  docs/integrations/bitbucket.md
  docs/integrations/gitlab.md
Labels: docs

#7146 upgrade dugite to 1.87
  app/package.json
  app/yarn.lock
Labels: ready-for-review

#7119 Enable darwinDarkModeSupport when packaging for macOS
  script/build.ts
Labels: infrastructure, ready-for-review

#7129 some cleanup extracted from the rebase flow changes
  app/src/lib/app-state.ts
  app/src/lib/git/rebase.ts
  app/src/lib/promise.ts
  app/src/lib/stores/app-store.ts
  app/src/models/banner.ts
  app/src/ui/app.tsx
  app/src/ui/banners/rebase-conflicts-banner.tsx
  app/src/ui/banners/render-banner.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/rebase/rebase-conflicts-dialog.tsx
Labels: ready-for-review, tech-debt

#7121 Check OS Dark Mode On Start Up
  app/src/lib/stores/app-store.ts
Labels: ready-for-review

#7042 test and refactor current push/pull button behaviour
  app/src/ui/toolbar/push-pull-button.tsx
Labels: ready-for-review, tech-debt

#7018 only trigger conflicts flow for the selected repository
  app/src/lib/stores/app-store.ts
  app/src/ui/dispatcher/dispatcher.ts
Labels: ready-for-review

#7165 Fix broken build on development
  app/src/ui/dispatcher/dispatcher.ts
Labels: ready-for-review

#7152 Tweaks to onboarding language
  app/src/ui/blank-slate/blank-slate.tsx
  app/src/ui/changes/no-changes.tsx
Labels: ready-for-review

#7131 Cancel active selection before swapping document
  app/src/ui/diff/code-mirror-host.tsx
Labels: ready-for-review

#7135 tidy up merge status model and introduce rebase status model
  app/src/lib/app-state.ts
  app/src/lib/git/merge.ts
  app/src/lib/merge-tree-parser.ts
  app/src/lib/stores/app-store.ts
  app/src/models/action.ts
  app/src/models/merge.ts
  app/src/models/rebase.ts
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/history/merge-call-to-action-with-conflicts.tsx
  app/src/ui/history/merge-status-header.tsx
  app/src/ui/merge-branch/merge.tsx
  app/test/unit/git/parse-merge-result-test.ts
Labels: ready-for-review, tech-debt

#7153 Upgrade FS-Admin
  app/package.json
  app/yarn.lock
Labels: ready-for-review, tech-debt

#7130 Add Recent Group to Repo List
  app/src/lib/app-state.ts
  app/src/lib/stores/app-store.ts
  app/src/ui/app.tsx
  app/src/ui/repositories-list/group-repositories.ts
  app/src/ui/repositories-list/repositories-list.tsx
Labels: ready-for-review

#7149 at build time, ensure licenses include trailing newline
  script/build.ts
Labels: infrastructure, ready-for-review

#7171 1.7.0-beta1
  app/package.json
  changelog.json
Labels: ready-for-review

#7169 Catch exceptions thrown by parsedResponse
  app/src/lib/api.ts
Labels: ready-for-review

#6932 ensure unit test files match the expected pattern
  app/test/helpers/changes-state-helper.ts
  app/test/unit/format-commit-message-test.ts
  app/test/unit/stores/updates/update-changed-files-test.ts
  app/test/unit/stores/updates/update-conflict-state-test.ts
Labels: infrastructure, ready-for-review, tech-debt

#7154 metrics for force push
  app/src/lib/stats/stats-database.ts
  app/src/lib/stats/stats-store.ts
  app/src/lib/stores/app-store.ts
  app/src/ui/dispatcher/dispatcher.ts
  docs/process/metrics.md
Labels: ready-for-review

#7163 Detach commit statuses from pull requests
  app/package.json
  app/src/lib/api.ts
  app/src/lib/databases/pull-request-database.ts
  app/src/lib/stores/accounts-store.ts
  app/src/lib/stores/api-repositories-store.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/commit-status-store.ts
  app/src/lib/stores/helpers/pull-request-updater.ts
  app/src/lib/stores/pull-request-store.ts
  app/src/models/pull-request.ts
  app/src/ui/branches/branches-container.tsx
  app/src/ui/branches/ci-status.tsx
  app/src/ui/branches/no-pull-requests.tsx
  app/src/ui/branches/pull-request-badge.tsx
  app/src/ui/branches/pull-request-list-item.tsx
  app/src/ui/branches/pull-request-list.tsx
  app/src/ui/branches/pull-request-status.ts
  app/src/ui/branches/pull-requests-loading.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/index.tsx
  app/src/ui/toolbar/branch-dropdown.tsx
  app/styles/ui/_branches.scss
  app/test/unit/app-test.tsx
  app/test/unit/infer-comparison-branch-test.ts
  app/test/unit/pull-request-database-test.ts
  app/test/unit/pull-request-status-test.ts
  app/test/unit/repository-state-cache-test.ts
  app/yarn.lock
Labels: ready-for-review
