Repository desktop/desktop, pull requests merged in 2019-10, with the labels that each got.

#8363 [Stashing] Use 'update-index' to stage untracked files
  app/src/lib/git/stash.ts
Labels: epic:stashing, ready-for-review

#8360 [Onboarding tutorial] Add metrics
  app/src/lib/stats/stats-database.ts
  app/src/lib/stats/stats-store.ts
  app/src/lib/stores/app-store.ts
  app/src/ui/app.tsx
  app/src/ui/blank-slate/create-tutorial-repository-dialog.tsx
  app/src/ui/dispatcher/dispatcher.ts
Labels: epic:onboarding, ready-for-review

#8374 Onboarding copy updates
  app/src/ui/blank-slate/create-tutorial-repository-dialog.tsx
  app/src/ui/tutorial/tutorial-panel.tsx
Labels: epic:onboarding, ready-for-review

#8246 Log `shell.openExternal` errors
  app/src/main-process/menu/build-default-menu.ts
  app/src/main-process/shell.ts
Labels: ready-for-review

#8380 Resolve the current editor after loading the selected editor
  app/src/lib/stores/app-store.ts
Labels: ready-for-review

#8381 turn on onboarding tutorial for all
  app/src/lib/feature-flag.ts
Labels: epic:onboarding, ready-for-review

#8382 add icon to pr button
  app/src/ui/tutorial/tutorial-panel.tsx
  app/styles/ui/onboarding-tutorial/_right-panel.scss
Labels: epic:onboarding, ready-for-review

#8336 new octicons package
  app/src/ui/octicons/octicons.generated.ts
  package.json
  script/generate-octicons.ts
  yarn.lock
Labels: ready-for-review, tech-debt

#8384 2.2.0 Release
  app/package.json
  changelog.json
Labels: ready-for-review

#8390 Release/2.2.1 beta0
  app/package.json
  changelog.json
Labels: ready-for-review

#8395 Fix [object Object] pre-filled url text in the clone dialogue when opened from BlankSlateView
  app/src/ui/blank-slate/blank-slate.tsx
Labels: ready-for-review

#8391 Shorten PR Template
  .github/pull_request_template.md
Labels: meta, ready-for-review

#8357 Nudge users unable to push a workflow file to re-authenticate
  app/src/lib/stores/accounts-store.ts
  app/src/lib/stores/app-store.ts
  app/src/models/account.ts
  app/src/models/popup.ts
  app/src/ui/app.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/dispatcher/error-handlers.ts
  app/src/ui/index.tsx
  app/src/ui/workflow-push-rejected/workflow-push-rejected.tsx
Labels: ready-for-review

#8402 Shorten Issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/problem-to-raise.md
Labels: meta, ready-for-review

#8410 Don't cut off link external octicon in "Open Pull Request" button
  app/styles/ui/onboarding-tutorial/_right-panel.scss
Labels: ready-for-review

#8405 Don't terminate the app immediately when the main window is closed
  app/src/main-process/main.ts
Labels: ready-for-review

#8424 Fix exectuable path for launching vscodium on macos
  app/src/lib/editors/darwin.ts
Labels: integrations, ready-for-review

#8446 2.2.2-beta1 release
  app/package.json
  changelog.json
Labels: ready-for-review

#8445 Reverse columns on "Let's get started" screen
  app/src/ui/clone-repository/cloneable-repository-filter-list.tsx
  app/src/ui/lib/filter-list.tsx
  app/src/ui/no-repositories/no-repositories-view.tsx
  app/styles/ui/_no-repositories.scss
Labels: ready-for-review

#8157 Add documentation for authenticating GHE from dev build
  docs/contributing/github-enterprise-auth-from-dev-build.md
  docs/contributing/setup.md
Labels: ready-for-review

#8388 Ensure editor from local storage is actually installed
  app/src/lib/stores/app-store.ts
Labels: ready-for-review

#8387 Keep `resolvedExternalEditor` and `selectedExternalEditor` in sync
  app/src/lib/app-state.ts
  app/src/lib/editors/lookup.ts
  app/src/lib/stores/app-store.ts
  app/src/ui/app.tsx
  app/src/ui/preferences/advanced.tsx
  app/src/ui/preferences/preferences.tsx
Labels: ready-for-review

#8485 Onboarding Tutorial Nudge Arrows
  app/src/ui/app.tsx
  app/src/ui/changes/changes-list.tsx
  app/src/ui/changes/commit-message.tsx
  app/src/ui/changes/sidebar.tsx
  app/src/ui/repository.tsx
  app/src/ui/toolbar/branch-dropdown.tsx
  app/src/ui/toolbar/dropdown.tsx
  app/src/ui/toolbar/push-pull-button.tsx
  app/styles/_ui.scss
  app/styles/_variables.scss
  app/styles/ui/onboarding-tutorial/_nudge-arrow.scss
Labels: epic:onboarding, ready-for-review, time-sensitive

#8491 Onboarding sizing tweaks
  app/styles/ui/_no-repositories.scss
  app/styles/ui/onboarding-tutorial/_welcome.scss
Labels: epic:onboarding

#8493 Adjust onboarding tutorial nudge timing
  app/styles/ui/onboarding-tutorial/_nudge-arrow.scss
Labels: epic:onboarding
