Repository desktop/desktop, pull requests merged in 2019-02, with the labels that each got.

#6756 Fix the Azure build
  azure-pipelines.yml
Labels: infrastructure, ready-for-review

#6730 Wire up Syntax Highlighting for Crystal and Julia
  app/src/highlighter/index.ts
  docs/technical/syntax-highlighting.md
Labels: ready-for-review

#6758 Use standard link styling on conflicts dialog
  app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx
  app/styles/ui/dialogs/_merge-conflicts.scss
Labels: ready-for-review

#6742 fail the CI build if modified files exist after installing packages
  .circleci/config.yml
  .travis.yml
  appveyor.yml
  azure-pipelines.yml
  package.json
  yarn.lock
Labels: infrastructure, ready-for-review, time-sensitive

#6770 Update roadmap
  docs/process/roadmap.md
Labels: docs, ready-for-review

#6775 ensure list elements in MergeConflicts dialog are keyed
  app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx
Labels: ready-for-review

#6764 fix pointy corners with border-radius
  app/styles/ui/changes/_commit-message.scss
Labels: ready-for-review

#6790 enable builds targeting this branch to investigate Travis failures
  .travis.yml
  appveyor.yml
Labels: infrastructure, time-sensitive

#6614 tidy up check for missing repository to be more readable
  app/src/lib/stores/app-store.ts
Labels: ready-for-review, tech-debt

#6721 add Git tests for our current pull behaviour
  app/test/helpers/repositories.ts
  app/test/helpers/repository-builder-pull-test.ts
  app/test/helpers/repository-scaffolding.ts
  app/test/helpers/temp.ts
  app/test/helpers/tip.ts
  app/test/unit/git/config-test.ts
  app/test/unit/git/pull/ahead-and-behind-test.ts
  app/test/unit/git/pull/only-ahead-test.ts
  app/test/unit/git/pull/only-behind-test.ts
  app/test/unit/git/rev-parse-test.ts
  app/test/unit/validated-repository-path-test.ts
  docs/technical/crafting-git-tests.md
Labels: infrastructure, ready-for-review, time-sensitive

#6777 add manual conflict resolution options in merge conflicts modal!!
  app/src/lib/status.ts
  app/src/lib/stores/app-store.ts
  app/src/models/status.ts
  app/src/ui/app.tsx
  app/src/ui/changes/sidebar.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx
  app/src/ui/merge-conflicts/unmerged-file.tsx
  app/styles/ui/dialogs/_merge-conflicts.scss
  app/test/unit/app-store-test.ts
Labels: ready-for-review

#6799 downgrade spectron to known good version for Electron 2.x
  appveyor.yml
  package.json
  yarn.lock
Labels: infrastructure, ready-for-review

#6812 cleanup build config changes after investigating integration test failures
  .travis.yml
  appveyor.yml
Labels: infrastructure, ready-for-review, tech-debt

#6824 mark repository found only if its a git repo
  app/src/lib/stores/app-store.ts
Labels: ready-for-review, time-sensitive

#6821 improve language clarity in manual merge conflict resolution UI
  app/src/lib/status.ts
  app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx
  app/src/ui/merge-conflicts/unmerged-file.tsx
Labels: ready-for-review, time-sensitive

#6826 unrelated changes in merge conflict commit
  app/src/lib/git/commit.ts
  app/src/lib/stores/app-store.ts
  app/test/helpers/repositories.ts
  app/test/unit/app-store-test.ts
Labels: ready-for-review

#6832 final beta for 1.6.2
  app/package.json
  changelog.json
Labels: ready-for-review

#6840 1.6.2 release
  app/package.json
  changelog.json
Labels: ready-for-review

#6717 Remove enableFileSizeWarningCheck Feature Flag
  app/src/lib/feature-flag.ts
  app/src/ui/changes/sidebar.tsx
Labels: ready-for-review, tech-debt

#6784 Enable Git v2 protocol for production build
  app/src/lib/feature-flag.ts
Labels: ready-for-review

#6241 pull prettier into yarn scripts
  .prettierignore
  package.json
  script/prettier.ts
Labels: infrastructure, ready-for-review

#6792 Fix hitbox for RMB in 'Changes' Panel
  app/styles/ui/_file-list.scss
Labels: ready-for-review

#6807 Enable branch pruning for beta channel
  app/src/lib/feature-flag.ts
Labels: ready-for-review

#6802 Stops node_modules from being cached during CI builds
  .circleci/config.yml
  .travis.yml
  appveyor.yml
Labels: infrastructure, ready-for-review

#6837 [rebase] extract functions so they can be shared
  app/src/lib/status.ts
  app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx
Labels: ready-for-review, tech-debt

#6830 [rebase] add Git internals to support rebase flow
  app/src/lib/feature-flag.ts
  app/src/lib/git/commit.ts
  app/src/lib/git/index.ts
  app/src/lib/git/pull.ts
  app/src/lib/git/rebase.ts
  app/src/lib/git/stage.ts
  app/src/lib/git/status.ts
  app/test/helpers/repository-builder-rebase-test.ts
  app/test/helpers/repository-scaffolding.ts
  app/test/unit/git/pull/ahead-and-behind-test.ts
  app/test/unit/git/rebase/detect-conflict-test.ts
  app/test/unit/stores/updates/changes-state-helper.ts
Labels: ready-for-review

#6713 Upgrade to Electron 3
  app/.npmrc
  app/src/main-process/main.ts
  package.json
  yarn.lock
Labels: ready-for-review, time-sensitive

#6815 publish test/coverage results even if the tests report errors
  .circleci/config.yml
  .travis.yml
  appveyor.yml
  azure-pipelines.yml
Labels: infrastructure, ready-for-review

#6664 Add git function to get branch checkouts from reflog
  app/src/lib/git/reflog.ts
  app/src/lib/stores/helpers/branch-pruner.ts
  app/test/unit/git/reflog-test.ts
Labels: ready-for-review

#6854 1.6.3 beta 1
  app/package.json
  changelog.json
Labels: ready-for-review

#6647 add regression test for node-sass migration
  script/build.ts
  script/validate-sass/validate-all.ts
  script/validate-sass/validate-file.ts
Labels: infrastructure, ready-for-review, tech-debt

#6878 remove old folder path from codecov config
  .codecov.yml
Labels: infrastructure, ready-for-review

#6839 [rebase] add state changes to support detecting rebase conflicts
  app/src/lib/app-state.ts
  app/src/lib/git/rebase.ts
  app/src/lib/git/status.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/updates/changes-state.ts
  app/src/models/rebase.ts
  app/src/models/tip.ts
  app/test/unit/git/rebase/detect-conflict-test.ts
  app/test/unit/stores/updates/changes-state-helper.ts
  app/test/unit/stores/updates/update-conflict-state-test.ts
Labels: ready-for-review

#6873 rewrote workaround to use a newer Git config value
  docs/known-issues.md
Labels: docs, ready-for-review

#6707 Text diff rendering improvements
  app/src/ui/diff/code-mirror-host.tsx
  app/src/ui/diff/diff-explorer.ts
  app/src/ui/diff/diff-line-gutter.tsx
  app/src/ui/diff/edge-detection.ts
  app/src/ui/diff/index.tsx
  app/src/ui/diff/selection/drag-drop-selection-strategy.ts
  app/src/ui/diff/selection/range-selection-strategy.ts
  app/src/ui/diff/selection/selection-strategy.ts
  app/src/ui/diff/selection/selection.ts
  app/src/ui/diff/text-diff.tsx
  app/styles/ui/_diff.scss
Labels: ready-for-review

#6884 unify banner state in application to pay down some tech debt
  app/src/lib/app-state.ts
  app/src/lib/stores/app-store.ts
  app/src/models/banner.ts
  app/src/ui/app.tsx
  app/src/ui/banners/index.ts
  app/src/ui/banners/render-banner.tsx
  app/src/ui/changes/sidebar.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/merge-conflicts/commit-conflicts-warning.tsx
  app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx
Labels: ready-for-review, tech-debt

#6863 Filter out currently checkout branch from being pruned
  app/src/lib/git/branch.ts
  app/src/lib/git/refs.ts
  app/src/lib/stores/helpers/branch-pruner.ts
Labels: ready-for-review

#6911 1.6.3-beta2
  app/package.json
  changelog.json
Labels: ready-for-review

#6910 Reinstate missing illustration and fix blankslate illustration to work in the dark theme
  app/static/common/empty-no-commit.svg
  app/static/common/paper-stack.svg
  app/styles/ui/changes/_no-changes.scss
Labels: ready-for-review

#6755 show an actionable dialog when files would be overwritten
  app/package.json
  app/src/lib/git/core.ts
  app/src/lib/stores/app-store.ts
  app/src/models/popup.ts
  app/src/models/retry-actions.ts
  app/src/ui/app.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/dispatcher/error-handlers.ts
  app/src/ui/index.tsx
  app/src/ui/local-changes-overwritten/index.ts
  app/src/ui/local-changes-overwritten/local-changes-overwritten-warning.tsx
  app/yarn.lock
Labels: ready-for-review

#6897 favour object spread where changes state is read inside Sidebar
  app/src/ui/changes/sidebar.tsx
Labels: ready-for-review, tech-debt

#6610 a better "push needs pull" dialog to avoid race condition
  app/src/models/popup.ts
  app/src/ui/app.tsx
  app/src/ui/dispatcher/error-handlers.ts
  app/src/ui/push-needs-pull/index.ts
  app/src/ui/push-needs-pull/push-needs-pull-warning.tsx
  app/styles/ui/_dialog.scss
  app/styles/ui/dialogs/_push-needs-pull.scss
Labels: ready-for-review

#6917 Show ? in Dark Mode Blank State
  app/static/common/empty-no-commit.svg
Labels: ready-for-review

#6848 Allow octicon to take and render alt text
  app/src/ui/octicons/octicon.tsx
Labels: accessibility, ready-for-review

#6776 Split repository publication settings into two types
  app/src/models/publish-settings.ts
  app/src/ui/publish-repository/publish-repository.tsx
  app/src/ui/publish-repository/publish.tsx
Labels: ready-for-review

#6905 Fixed left-padding for :emoji:/@user/#issue autocomplete forms.
  app/styles/ui/_autocompletion.scss
Labels: ready-for-review

#6698 [rebase] detect and show a dialog containing what needs to be done
  app/src/lib/app-state.ts
  app/src/lib/git/rebase.ts
  app/src/lib/stats/stats-database.ts
  app/src/lib/stats/stats-store.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/updates/changes-state.ts
  app/src/lib/tip.ts
  app/src/models/banner.ts
  app/src/models/popup.ts
  app/src/models/rebase.ts
  app/src/ui/app.tsx
  app/src/ui/banners/rebase-conflicts-banner.tsx
  app/src/ui/banners/render-banner.tsx
  app/src/ui/banners/successful-rebase.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/dispatcher/error-handlers.ts
  app/src/ui/index.tsx
  app/src/ui/rebase/conflict-files-list.tsx
  app/src/ui/rebase/index.ts
  app/src/ui/rebase/rebase-conflicts-dialog.tsx
  app/styles/ui/_banners.scss
  app/styles/ui/_dialog.scss
  app/styles/ui/banners/_rebase-conflicts.scss
  app/styles/ui/banners/_successful-rebase.scss
  app/styles/ui/dialogs/_rebase.scss
  app/test/unit/git/rebase/detect-conflict-test.ts
  app/test/unit/stores/updates/update-conflict-state-test.ts
Labels: ready-for-review

#6934 enable new rebase features for beta channel
  app/src/lib/feature-flag.ts
Labels: ready-for-review

#6923 group and filter repositories by owner
  app/src/lib/feature-flag.ts
  app/src/ui/repositories-list/group-repositories.ts
  app/src/ui/repositories-list/repositories-list.tsx
  app/test/unit/repositories-list-grouping-test.ts
Labels: ready-for-review

#6914 propagate information to rebase conflicts dialog when pull fails
  app/src/lib/error-with-metadata.ts
  app/src/lib/git-error-context.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/git-store.ts
  app/src/ui/dispatcher/error-handlers.ts
Labels: ready-for-review

#6951 the last set of rebase metrics for this release
  app/src/lib/app-state.ts
  app/src/lib/stats/stats-database.ts
  app/src/lib/stats/stats-store.ts
  app/src/lib/stores/updates/changes-state.ts
  app/test/unit/stores/updates/update-conflict-state-test.ts
Labels: ready-for-review

#6937 teach branch switcher about rebase conflicts
  app/src/ui/toolbar/branch-dropdown.tsx
Labels: ready-for-review

#6907 show a "continue rebase" button when conflicts are outstanding
  app/src/ui/changes/changes-list.tsx
  app/src/ui/changes/continue-rebase.tsx
  app/src/ui/changes/sidebar.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/rebase/rebase-conflicts-dialog.tsx
  app/styles/ui/_changes.scss
  app/styles/ui/changes/_continue-rebase.scss
Labels: ready-for-review

#6893 display "pull with rebase" if user has set this in config
  app/src/lib/app-state.ts
  app/src/lib/stats/stats-database.ts
  app/src/lib/stats/stats-store.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/git-store.ts
  app/src/ui/app.tsx
  app/src/ui/toolbar/push-pull-button.tsx
Labels: ready-for-review

#6958 add docs for new rebase metrics
  docs/process/metrics.md
Labels: docs, ready-for-review

#6661 upgrade node-sass, address SASS breaking changes
  app/styles/_variables.scss
  app/styles/themes/_dark.scss
  app/styles/ui/changes/_commit-message.scss
  package.json
  yarn.lock
Labels: infrastructure, ready-for-review

#6947 update TextDiff update logic
  app/src/ui/diff/code-mirror-host.tsx
  app/src/ui/diff/text-diff.tsx
Labels: ready-for-review

#6967 1.6.3-beta3
  app/package.json
  changelog.json
Labels: ready-for-review

#6966 upgrade css loader dependency to latest
  package.json
  yarn.lock
Labels: infrastructure, ready-for-review

#6979 Update roadmap
  docs/process/roadmap.md
Labels: docs
