Repository desktop/desktop, pull requests merged in 2019-05, with the labels that each got.

#7432 Manually drop successful stash pop with conflicts
  app/src/lib/git/stash.ts
  app/test/unit/git/stash-test.ts
Labels: ready-for-review

#7443 remove remaining LocalChangesOverwritten dialog code
  app/src/models/popup.ts
  app/src/ui/app.tsx
  app/src/ui/local-changes-overwritten/index.ts
  app/src/ui/local-changes-overwritten/local-changes-overwritten-warning.tsx
Labels: ready-for-review, tech-debt

#7415 Improve "Discard all changes" UX
  app/src/lib/menu-update.ts
  app/src/main-process/menu/build-default-menu.ts
  app/src/main-process/menu/menu-event.ts
  app/src/main-process/menu/menu-ids.ts
  app/src/ui/app.tsx
  app/src/ui/changes/changes-list.tsx
  app/src/ui/changes/sidebar.tsx
Labels: ready-for-review

#7444 Center no content text in stash diff viewer
  app/src/ui/history/selected-commit.tsx
  app/src/ui/stashing/stash-diff-viewer.tsx
  app/styles/_ui.scss
  app/styles/ui/_commit-details.scss
  app/styles/ui/_stash-diff-viewer.scss
  app/styles/ui/history/_history.scss
Labels: ready-for-review

#7453 1.7.0-beta6
  app/package.json
  changelog.json
Labels: ready-for-review

#7456 Adjust the changelog indentation for 1.7.0 beta 2
  changelog.json
Labels: docs, ready-for-review

#7401 wrapping up docs about rebase flow
  docs/technical/rebase-flow.md
Labels: docs, ready-for-review

#7435 cleanup duplicate typings that now ship in fs-admin
  app/typings/fs-admin/index.d.ts
Labels: ready-for-review, tech-debt

#7448 updating the test cases
  docs/process/testing.md
Labels: docs, ready-for-review

#7429 unified and simplified API for updating menu labels based on app state
  app/src/lib/menu-update.ts
  app/src/lib/stores/app-store.ts
  app/src/main-process/main.ts
  app/src/main-process/menu/build-default-menu.ts
  app/src/main-process/menu/index.ts
  app/src/models/menu-ids.ts
  app/src/models/menu-labels.ts
  app/src/ui/changes/menu-backed-blankslate-action.tsx
  app/src/ui/changes/no-changes.tsx
  app/src/ui/main-process-proxy.ts
Labels: ready-for-review

#7459 use prettier to format JSON files
  .prettierignore
  .vscode/launch.json
  changelog.json
  package.json
  script/tsconfig.json
  tsconfig.json
Labels: ready-for-review, tech-debt

#7472 Improve error message when publishing repo to an organization
  app/src/lib/api.ts
Labels: ready-for-review

#7479 Upgrade from Xcode 9.3.0 to 9.3.1 on CircleCI
  .circleci/config.yml
Labels: infrastructure, ready-for-review

#7441 "view stash" button a11y and styling
  app/src/ui/changes/changes-list.tsx
  app/styles/ui/changes/_changes-list.scss
Labels: accessibility, epic:stashing, ready-for-review

#7484 tests need to use the databass
  app/test/unit/app-store-test.ts
Labels: infrastructure, ready-for-review

#7482 also build PRs targeting release branch pattern
  .travis.yml
  appveyor.yml
  azure-pipelines.yml
  docs/process/releasing-updates.md
Labels: infrastructure, ready-for-review

#7489 cherry pick enabling all ci services for release branches into 1.6.6
  .travis.yml
  appveyor.yml
  azure-pipelines.yml
Labels: infrastructure, ready-for-review

#7488 Adds some cache to improve baseline metrics performance
  app/src/lib/stores/repositories-store.ts
Labels: performance, ready-for-review

#7491 appveyor and travis only take regex for branch filters
  .travis.yml
  appveyor.yml
Labels: infrastructure, ready-for-review

#7481 Upgrade from Xcode 9.3.0 to 9.3.1 on CircleCI
  .circleci/config.yml
Labels: infrastructure, ready-for-review

#7485 1.6.6 bugfix backports
  app/src/main-process/log.ts
  app/src/ui/changes/commit-message.tsx
  app/src/ui/diff/code-mirror-host.tsx
Labels: ready-for-review

#7471 update repository state selectively during stashing
  app/src/lib/stores/app-store.ts
Labels: epic:stashing, performance, ready-for-review

#7476 use the index state to detect whether there are conflicted files present
  app/src/lib/git/rebase.ts
  app/src/lib/git/stash.ts
  app/src/lib/git/status.ts
  app/test/unit/git/status-test.ts
Labels: epic:stashing, performance, ready-for-review

#7470 Reimplement baseline stashing metrics on top of last prod release
  app/package.json
  app/src/lib/databases/repositories-database.ts
  app/src/lib/git/core.ts
  app/src/lib/git/stash.ts
  app/src/lib/stats/stats-database.ts
  app/src/lib/stats/stats-store.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/repositories-store.ts
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/dispatcher/error-handlers.ts
  app/src/ui/index.tsx
  app/test/unit/app-store-test.ts
  app/yarn.lock
Labels: epic:stashing, ready-for-review

#7496 release notes for 1.6.6 test release
  app/package.json
  changelog.json
Labels: ready-for-review

#7497 1.7.0-beta7 release
  app/package.json
  changelog.json
Labels: ready-for-review

#7486 Don't persist branch and PR filters
  app/src/lib/app-state.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/repository-state-cache.ts
  app/src/ui/branches/branches-container.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/toolbar/branch-dropdown.tsx
Labels: ready-for-review

#7477 tweak the output when in development mode for helpful performance context
  app/src/lib/stores/app-store.ts
  app/src/ui/lib/git-perf.ts
Labels: performance, ready-for-review, tech-debt

#7475 avoid invoking status when updating indicator for current repository
  app/src/lib/stores/app-store.ts
  app/src/ui/app.tsx
Labels: performance, ready-for-review

#7525 Add docs for baseline stashing metrics
  docs/process/metrics.md
Labels: docs, ready-for-review

#7512 Shift + alt in summary moves input-focus
  app/src/ui/app.tsx
Labels: ready-for-review

#7508 Added Accelerator and Access key for Exit
  app/src/main-process/menu/build-default-menu.ts
Labels: ready-for-review

#7532 Ensure `updateStashEntryCountMetric` is updated during a long session of Desktop
  app/src/lib/stores/app-store.ts
Labels: performance, ready-for-review

#7534 lowercase pronoun
  app/src/ui/history/commit-list-item.tsx
Labels: ready-for-review

#7506 Absolute url mangling
  app/src/lib/http.ts
  app/test/unit/http-test.ts
Labels: ready-for-review

#7452 Added error message when `github open [url]`
  app/src/cli/commands/open.ts
Labels: ready-for-review

#7501 Differential loading of PRs and PR database improvements
  app/package.json
  app/src/lib/api.ts
  app/src/lib/databases/pull-request-database.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/git-store.ts
  app/src/lib/stores/helpers/pull-request-updater.ts
  app/src/lib/stores/pull-request-store.ts
  app/src/models/pull-request.ts
  app/src/models/remote.ts
  app/src/models/tip.ts
  app/test/unit/api-test.ts
  app/test/unit/infer-comparison-branch-test.ts
  app/test/unit/repository-state-cache-test.ts
  app/yarn.lock
Labels: ready-for-review

#7530 Apply first-click dismissal prevention on macOS as well
  app/src/ui/dialog/dialog.tsx
Labels: ready-for-review

#7551 1.7.0-beta8
  app/package.json
  changelog.json
Labels: ready-for-review

#7559 run azure for all prs
  azure-pipelines.yml
Labels: infrastructure, ready-for-review

#7561 better setup to land these cursed tests
  app/test/unit/app-store-test.ts
Labels: infrastructure, ready-for-review

#7562 disable flaky tests in 1.6.6 release branch
  app/test/unit/app-store-test.ts
Labels: infrastructure, ready-for-review

#7537 Release 1.6.6
  app/src/lib/databases/repositories-database.ts
  app/src/lib/git/core.ts
  app/src/lib/git/stash.ts
  app/src/lib/stats/stats-database.ts
  app/src/lib/stats/stats-store.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/repositories-store.ts
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/dispatcher/error-handlers.ts
  app/src/ui/index.tsx
  app/test/unit/app-store-test.ts
  changelog.json
  docs/process/metrics.md
Labels: ready-for-review

#7494 enable new rebase flow for all users
  app/src/lib/feature-flag.ts
Labels: epic:rebase, ready-for-review

#7539 add warning when renaming a branch with a stash
  app/src/ui/app.tsx
  app/src/ui/lib/branch-name-warnings.tsx
  app/src/ui/rename-branch/rename-branch-dialog.tsx
Labels: epic:stashing, ready-for-review

#7541 Address Case of the Missing Monitor
  app/package.json
  app/src/main-process/app-window.ts
  app/yarn.lock
Labels: ready-for-review

#7557 Only pass what's actually needed for a commit message
  app/src/ui/changes/commit-message.tsx
Labels: ready-for-review

#7586 wrapping up the current rebase epic
  docs/process/labels.md
Labels: docs, ready-for-review

#7529 retrieve and cache protected branch information per-repository
  app/src/lib/api.ts
  app/src/lib/databases/repositories-database.ts
  app/src/lib/feature-flag.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/repositories-store.ts
  app/test/unit/branch-pruner-test.ts
  app/test/unit/repositories-store-test.ts
Labels: ready-for-review

#7594 Dial down on the explicit fetching of pull requests
  app/src/lib/stores/app-store.ts
Labels: ready-for-review

#7505 Enable create PR suggestion for production
  app/src/lib/feature-flag.ts
Labels: ready-for-review

#7474 Refactors the stashing flow a bit to reduce unnecessary work
  app/src/lib/git-error-context.ts
  app/src/lib/git/checkout.ts
  app/src/lib/git/stash.ts
  app/src/lib/stores/app-store.ts
  app/src/models/stash-entry.ts
  app/src/models/uncommitted-changes-strategy.ts
  app/src/ui/create-branch/create-branch-dialog.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/dispatcher/error-handlers.ts
  app/src/ui/stash-changes/overwrite-stashed-changes-dialog.tsx
  app/src/ui/stash-changes/stash-and-switch-branch-dialog.tsx
Labels: epic:stashing, performance, ready-for-review

#7618 1.7.0-beta9
  app/package.json
  changelog.json
Labels: ready-for-review

#7611 explanation for text file with manual conflict diff
  app/src/models/status.ts
  app/src/ui/diff/index.tsx
Labels: ready-for-review

#7630 enable new repository grouping for production
  app/src/lib/feature-flag.ts
Labels: ready-for-review

#7623 Rearrange Repository List's Indicators
  app/src/ui/repositories-list/repositories-list.tsx
  app/src/ui/repositories-list/repository-list-item.tsx
  app/styles/ui/_repository-list.scss
Labels: ready-for-review

#7556 Fix Tab Bar focus ring outlines clipping into other elements
  app/styles/ui/_tab-bar.scss
Labels: ready-for-review

#7628 enable stashing for all users
  app/src/lib/feature-flag.ts
Labels: ready-for-review

#7635 Suggested changes metrics
  app/src/lib/stats/stats-database.ts
  app/src/lib/stats/stats-store.ts
  app/src/ui/app.tsx
  app/src/ui/changes/blankslate-action.tsx
  app/src/ui/changes/menu-backed-blankslate-action.tsx
  app/src/ui/changes/no-changes.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/lib/button.tsx
  app/src/ui/repository.tsx
Labels: ready-for-review

#7595 record metrics for protected branch scenarios due for 1.7
  app/src/lib/feature-flag.ts
  app/src/lib/stats/stats-database.ts
  app/src/lib/stats/stats-store.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/helpers/find-branch-name.ts
  app/src/lib/stores/repositories-store.ts
  docs/process/metrics.md
Labels: ready-for-review

#7438 Baseline stashing metrics
  app/src/lib/git/stash.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/git-store.ts
  app/test/unit/git/stash-test.ts
Labels: epic:stashing, ready-for-review

#7257 [Stashing] Metrics
  app/src/lib/stats/stats-database.ts
  app/src/lib/stats/stats-store.ts
  app/src/lib/stores/app-store.ts
  app/src/ui/changes/changes-list.tsx
  app/src/ui/changes/no-changes.tsx
  app/src/ui/dispatcher/dispatcher.ts
Labels: epic:stashing, ready-for-review

#7646 1.7.1-beta1
  app/package.json
  changelog.json
Labels: ready-for-review

#7648 Changed the casing of the enums and their references
  app/src/lib/stores/app-store.ts
  app/src/models/uncommitted-changes-strategy.ts
  app/src/ui/stash-changes/stash-and-switch-branch-dialog.tsx
Labels: ready-for-review

#7653 enable branch protection metrics for production
  app/src/lib/feature-flag.ts
Labels: ready-for-review

#7499 added a test helper to generate strings for test data
  app/test/helpers/random-data.ts
  app/test/unit/git/stash-test.ts
  app/test/unit/git/status-test.ts
Labels: infrastructure, ready-for-review, tech-debt

#7420 tidy up tests to avoid needing to exclaim ourselves
  app/test/unit/accounts-store-test.ts
  app/test/unit/app-store-test.ts
  app/test/unit/app-test.tsx
  app/test/unit/git-store-cache-test.ts
  app/test/unit/git-store-test.ts
  app/test/unit/git/commit-test.ts
  app/test/unit/git/config-test.ts
  app/test/unit/git/core-test.ts
  app/test/unit/git/diff-test.ts
  app/test/unit/git/for-each-ref-test.ts
  app/test/unit/git/log-test.ts
  app/test/unit/git/reflog-test.ts
  app/test/unit/git/reset-test.ts
  app/test/unit/git/rev-parse-test.ts
  app/test/unit/git/status-test.ts
  app/test/unit/patch-formatter-test.ts
  app/test/unit/repositories-store-test.ts
  app/test/unit/repository-state-cache-test.ts
  app/test/unit/text-token-parser-test.ts
Labels: ready-for-review, tech-debt
