Repository desktop/desktop, pull requests merged in 2020-05, with the labels that each got.

#9682 Enable tags feature flag in beta
  app/src/lib/feature-flag.ts
Labels: epic:tags

#9706 Catch invalid credential errors
  app/src/lib/git/tag.ts
Labels: epic:tags

#9709 mock remote.nativeTheme for tests
  app/test/__mocks__/electron.ts
Labels: infrastructure

#9772 move moment plugin setup
  app/src/ui/index.tsx
  app/src/ui/relative-time.tsx
Labels: tech-debt

#9832 Adds additional information in windows setup documentation
  docs/contributing/setup-windows.md
Labels: docs

#9805 add storage for fork repo workflow settings
  app/src/lib/databases/repositories-database.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/repositories-store.ts
  app/src/models/repository.ts
  app/src/models/workflow-preferences.ts
Labels: epic:fork

#8318 Reworked Ctrl+Tab to work without RepositoryView focus
  app/src/ui/app.tsx
  app/src/ui/repository.tsx
Labels: ready-for-review

#9828 Avoid performing network operations to calculate unpushed tags
  app/package.json
  app/src/lib/git/push.ts
  app/src/lib/local-storage.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/git-store.ts
  app/src/lib/stores/helpers/fetch-tags-to-push-memoized.ts
  app/src/lib/stores/helpers/tags-to-push-storage.ts
  app/src/lib/stores/repositories-store.ts
  app/test/unit/git/tag-test.ts
  app/yarn.lock
  package.json
  yarn.lock
Labels: epic:tags, time-sensitive

#9848 Use canonical stash references to avoid ambiguous references
  app/src/lib/git/stash.ts
  app/src/models/stash-entry.ts
  app/test/unit/git/stash-test.ts
Labels: priority-3

#9796 Add delete tags functionality
  app/src/lib/git/tag.ts
  app/src/lib/menu-item.ts
  app/src/lib/stats/stats-database.ts
  app/src/lib/stats/stats-store.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/git-store.ts
  app/src/main-process/main.ts
  app/src/main-process/menu/build-context-menu.ts
  app/src/models/popup.ts
  app/src/ui/app.tsx
  app/src/ui/delete-tag/delete-tag-dialog.tsx
  app/src/ui/delete-tag/index.ts
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/history/commit-list-item.tsx
  app/src/ui/history/commit-list.tsx
  app/src/ui/history/compare.tsx
  app/src/ui/main-process-proxy.ts
  app/test/unit/git/tag-test.ts
Labels: epic:tags

#9806 use fork workflow preferences if possible
  app/src/lib/branch.ts
  app/src/lib/stores/helpers/infer-comparison-branch.ts
  app/src/models/repository.ts
  app/src/ui/app.tsx
Labels: epic:fork

#9862 Support deleting tags from outside desktop
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/git-store.ts
Labels: epic:tags

#9640 Windows: make it safer to Open in Command Prompt (in cmd.exe)
  app/src/lib/is-git-on-path.ts
  app/src/lib/shells/found-shell.ts
  app/src/lib/shells/win32.ts
Labels: integrations, windows

#9842 Add tab for fork settings in repository settings
  app/src/lib/feature-flag.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/repositories-store.ts
  app/src/models/github-repository.ts
  app/src/models/repository.ts
  app/src/ui/app.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/repository-settings/fork-settings.tsx
  app/src/ui/repository-settings/remote.tsx
  app/src/ui/repository-settings/repository-settings.tsx
  app/src/ui/tab-bar.tsx
  app/styles/ui/dialogs/_repository-settings.scss
Labels: epic:fork

#9869 Show popup for fork settings when cloning a fork
  app/src/models/popup.ts
  app/src/ui/app.tsx
  app/src/ui/choose-fork-settings/choose-fork-settings-dialog.tsx
  app/src/ui/choose-fork-settings/index.ts
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/forks/create-fork-dialog.tsx
  app/src/ui/lib/vertical-segmented-control/segmented-item.tsx
  app/src/ui/lib/vertical-segmented-control/vertical-segmented-control.tsx
  app/src/ui/repository-settings/fork-contribution-target-description.tsx
  app/src/ui/repository-settings/fork-settings.tsx
  app/styles/ui/_dialog.scss
  app/styles/ui/_vertical-segmented-control.scss
  app/styles/ui/dialogs/_fork-settings.scss
Labels: epic:fork
