Repository desktop/desktop, pull requests merged in 2020-02, with the labels that each got.

#9014 Account for peeps who maybe shouldn't create fork
  app/src/ui/forks/create-fork-dialog.tsx
Labels: ready-for-review

#8836 Atomic remote branch delete and resilience
  app/src/lib/git/branch.ts
  app/src/lib/git/update-ref.ts
  app/test/helpers/repositories.ts
  app/test/unit/git/branch-test.ts
Labels: priority-3

#9058 Update roadmap with latest ships
  docs/process/roadmap.md
Labels: docs

#9039 Only log tutorial step when it changes
  app/src/lib/stores/app-store.ts
Labels: tech-debt

#9021 Add release notes formatting yarn task
  package.json
  script/changelog/index.ts
  script/changelog/run.ts
Labels: infrastructure

#9051 Cleanup and document existing draft notes task
  script/draft-release/run.ts
Labels: infrastructure, tech-debt

#9071 Update dugite to fix macOS notarization
  app/package.json
  app/src/lib/git/core.ts
  app/yarn.lock
Labels: dependencies

#9069 Update known-issues.md with some new debugging steps
  docs/known-issues.md
Labels: docs

#9045 added forking, branch protection, some edits
  docs/process/testing.md
Labels: docs, ready-for-review

#9079 Fix Dark Mode Multiple Files Selected Graphic
  app/static/common/multiple-files-selected.svg
Labels: bug, ready-for-review, themes

#9092 clean up fork conversion git logic
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/git-store.ts
Labels: epic:fork, tech-debt

#9101 Guard against unexpected push control API response
  app/src/lib/helpers/push-control.ts
  app/src/lib/stores/app-store.ts
Labels: priority-2

#9127 Parse Proxy Auto-Configuration strings
  app/src/lib/parse-pac-string.ts
  app/test/unit/parse-pac-string-test.ts
Labels: epic:proxy

#9085 Scroll diffs with keyboard without moving the invisible cursor
  app/src/ui/diff/text-diff.tsx
Labels: priority-3

#9126 Proxy (p)refactor of create tutorial repository dialog
  app/src/lib/friendly-endpoint-name.ts
  app/src/lib/stats/stats-store.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/helpers/create-tutorial-repository.ts
  app/src/models/popup.ts
  app/src/ui/app.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/no-repositories/create-tutorial-repository-dialog.tsx
Labels: epic:proxy

#9139 Determine remote endpoint for Git network operations
  app/src/lib/git/branch.ts
  app/src/lib/git/checkout.ts
  app/src/lib/git/clone.ts
  app/src/lib/git/environment.ts
  app/src/lib/git/fetch.ts
  app/src/lib/git/pull.ts
  app/src/lib/git/push.ts
  app/src/lib/git/remote.ts
  app/src/lib/git/revert.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/git-store.ts
  app/src/lib/stores/helpers/create-tutorial-repository.ts
  app/test/unit/git/pull/ahead-and-behind-test.ts
  app/test/unit/git/pull/only-ahead-test.ts
  app/test/unit/git/pull/only-behind-test.ts
Labels: epic:proxy

#9186 Never schedule more than one animation frame on resize
  app/src/ui/diff/code-mirror-host.tsx
  app/src/ui/lib/author-input.tsx
Labels: priority-3
