Repository desktop/desktop, pull requests merged in 2020-04, with the labels that each got.

#9423 Simplify branch tip object
  app/src/lib/git/for-each-ref.ts
  app/src/lib/stores/git-store.ts
  app/src/lib/stores/helpers/tutorial-assessor.ts
  app/src/models/branch.ts
  app/test/unit/git/branch-test.ts
  app/test/unit/git/checkout-test.ts
  app/test/unit/git/for-each-ref-test.ts
  app/test/unit/git/rebase/detect-conflict-test.ts
  app/test/unit/group-branches-test.ts
  app/test/unit/infer-comparison-branch-test.ts
Labels: epic:tags, tech-debt

#9401 Added support for PyCharm as external editor on macOS
  app/src/lib/editors/darwin.ts
  docs/technical/editor-integration.md
Labels: integrations, macOS

#9387 Add support for JetBrains Rider on Windows
  app/src/lib/editors/win32.ts
  docs/technical/editor-integration.md
Labels: integrations, ready-for-review, windows

#9368 Add support to Rider on Mac
  app/src/lib/editors/darwin.ts
  docs/technical/editor-integration.md
Labels: integrations, macOS, ready-for-review

#9340 Display PRs from upstream repository in forks
  app/src/lib/stores/pull-request-coordinator.ts
  app/src/models/repository.ts
  app/src/ui/branches/branches-container.tsx
  app/src/ui/branches/no-pull-requests.tsx
  app/src/ui/branches/pull-request-list.tsx
  app/styles/ui/_branches.scss
Labels: epic:fork

#9430 Resolved Accelerator Conflict
  app/src/main-process/menu/build-default-menu.ts
Labels: epic:issues

#9432 Add createTag() method to git library wrapper
  app/src/lib/git/index.ts
  app/src/lib/git/tag.ts
  app/test/unit/git/tag-test.ts
Labels: epic:tags

#8587 Origin/features/show progress in taskbar for push or pull
  app/src/lib/feature-flag.ts
  app/src/lib/stores/app-store.ts
Labels: electron, windows

#9383 Retreive and store git tags on the commit model
  app/src/lib/feature-flag.ts
  app/src/lib/git/index.ts
  app/src/lib/git/log.ts
  app/src/lib/git/tag.ts
  app/src/models/commit.ts
  app/src/ui/history/commit-summary.tsx
  app/src/ui/lib/configure-git-user.tsx
  app/styles/ui/history/_commit-summary.scss
  app/test/fixtures/test-repo-with-tags/README.md
  app/test/fixtures/test-repo-with-tags/_git/COMMIT_EDITMSG
  app/test/fixtures/test-repo-with-tags/_git/HEAD
  app/test/fixtures/test-repo-with-tags/_git/ORIG_HEAD
  app/test/fixtures/test-repo-with-tags/_git/config
  app/test/fixtures/test-repo-with-tags/_git/index
  app/test/fixtures/test-repo-with-tags/_git/info/exclude
  app/test/fixtures/test-repo-with-tags/_git/logs/HEAD
  app/test/fixtures/test-repo-with-tags/_git/logs/refs/heads/master
  app/test/fixtures/test-repo-with-tags/_git/objects/00/d11a7f57fefe1955c2ebbb9bac35b201051978
  app/test/fixtures/test-repo-with-tags/_git/objects/04/c7629c588c74659f03dda5e5fb3dd8d6862dfa
  app/test/fixtures/test-repo-with-tags/_git/objects/0c/a9c5742bb924b9f32e91415b8d4093101b824c
  app/test/fixtures/test-repo-with-tags/_git/objects/17/6a458f94e0ea5272ce67c36bf30b6be9caf623
  app/test/fixtures/test-repo-with-tags/_git/objects/20/3168a1d10f7878ff66fa02fe0c434440ad218c
  app/test/fixtures/test-repo-with-tags/_git/objects/55/6f8c827b8e4a02ad5cab77dca2bcb3e226b0b3
  app/test/fixtures/test-repo-with-tags/_git/objects/70/36e9874e23623229ec636e5623fd176390b4af
  app/test/fixtures/test-repo-with-tags/_git/objects/7c/d6640e5b6ca8dbfd0b33d0281ebe702127079c
  app/test/fixtures/test-repo-with-tags/_git/objects/83/a54da49d2f0e85da2797a5fc7c47d0d608abce
  app/test/fixtures/test-repo-with-tags/_git/objects/8a/4ecd8dcfe0bde537f57d9392794ee669c82618
  app/test/fixtures/test-repo-with-tags/_git/objects/e0/5aaa29ed7c4f240dc5dc945169e3fbf7055585
  app/test/fixtures/test-repo-with-tags/_git/objects/e6/9de29bb2d1d6434b8b29ae775ad8c2e48c5391
  app/test/fixtures/test-repo-with-tags/_git/objects/f9/3e3a1a1525fb5b91020da86e44810c87a2d7bc
  app/test/fixtures/test-repo-with-tags/_git/refs/heads/master
  app/test/fixtures/test-repo-with-tags/_git/refs/tags/important
  app/test/fixtures/test-repo-with-tags/_git/refs/tags/less-important
  app/test/fixtures/test-repo-with-tags/_git/refs/tags/tentative
  app/test/unit/create-branch-test.ts
  app/test/unit/git/log-test.ts
  app/test/unit/git/tag-test.ts
Labels: epic:tags

#9431 Use the non-fork repository on the commit message TokenParser
  app/src/lib/text-token-parser.ts
Labels: epic:fork

#9462 enable win32 progress bars for beta
  app/src/lib/feature-flag.ts
Labels: windows

#9461 upgrade dugite to 1.88.3
  app/package.json
  app/src/lib/git/core.ts
  app/yarn.lock
Labels: dependencies, epic:tags

#9474 Use flex-shrink on the author selector modal
  app/styles/ui/_autocompletion.scss
Labels: electron

#9481 Push tags when pushing changes to repository
  app/src/lib/git/push.ts
Labels: epic:tags

#9514 Disable undoing commits that have tags associated
  app/src/ui/changes/sidebar.tsx
Labels: epic:tags

#9513 Tweaks to displayed tags on commit view
  app/src/ui/history/commit-summary.tsx
  app/styles/ui/history/_commit-summary.scss
Labels: epic:tags

#9440 Add create tag dialog
  app/src/lib/feature-flag.ts
  app/src/lib/git/core.ts
  app/src/lib/git/push.ts
  app/src/lib/parse-app-url.ts
  app/src/lib/sanitize-ref-name.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/git-store.ts
  app/src/models/popup.ts
  app/src/ui/app.tsx
  app/src/ui/create-branch/create-branch-dialog.tsx
  app/src/ui/create-tag/create-tag-dialog.tsx
  app/src/ui/create-tag/index.ts
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/history/commit-list-item.tsx
  app/src/ui/history/commit-list.tsx
  app/src/ui/history/compare.tsx
  app/src/ui/rename-branch/rename-branch-dialog.tsx
  app/styles/ui/_dialog.scss
  app/test/unit/sanitize-ref-name-test.ts
Labels: epic:tags

#9525 build: update node-sass to 4.13.1 to allow build on node 13
  package.json
  yarn.lock
Labels: dependencies

#9537 Display tags in commit list
  app/src/ui/history/commit-list-item.tsx
  app/styles/ui/_avatar-stack.scss
  app/styles/ui/history/_commit-list.scss
Labels: epic:tags

#9578 Refresh commit list after tagging
  app/src/lib/stores/git-store.ts
  app/src/ui/history/commit-list.tsx
Labels: epic:tags

#9492 Add fetchTagsToPush() git method
  app/src/lib/git/tag.ts
  app/test/unit/git/tag-test.ts
Labels: epic:tags

#9576 Use the `fetchTagsToPush()` output to display the push/pull information
  app/package.json
  app/src/lib/app-state.ts
  app/src/lib/git/tag.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/git-store.ts
  app/src/lib/stores/helpers/fetch-tags-to-push-memoized.ts
  app/src/lib/stores/repository-state-cache.ts
  app/src/models/popup.ts
  app/src/ui/app.tsx
  app/src/ui/changes/no-changes.tsx
  app/src/ui/create-tag/create-tag-dialog.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/history/compare.tsx
  app/src/ui/index.tsx
  app/src/ui/repository.tsx
  app/src/ui/toolbar/push-pull-button.tsx
  app/test/unit/git/tag-test.ts
  app/yarn.lock
  package.json
  yarn.lock
Labels: epic:tags

#9637 Measure number of tags created from GitHub Desktop
  app/src/lib/stats/stats-database.ts
  app/src/lib/stats/stats-store.ts
  app/src/lib/stores/app-store.ts
Labels: epic:tags

#9638 Measure number of created tags outside of Desktop
  app/src/lib/stats/stats-database.ts
  app/src/lib/stats/stats-store.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/git-store-cache.ts
  app/src/lib/stores/git-store.ts
  app/test/helpers/repository-builder-branch-pruner.ts
  app/test/unit/branch-pruner-test.ts
  app/test/unit/git-store-cache-test.ts
  app/test/unit/git-store-test.ts
  app/test/unit/git/branch-test.ts
  app/test/unit/git/checkout-test.ts
  app/test/unit/stores/updates/update-remote-url-test.ts
Labels: epic:tags

#7050 Upgrade to React 16.8.4
  app/package.json
  app/src/ui/changes/permissions-commit-warning.tsx
  app/src/ui/lib/conflicts/unmerged-file.tsx
  app/src/ui/lib/highlight-text.tsx
  app/src/ui/repositories-list/repository-list-item.tsx
  app/src/ui/suggested-actions/suggested-action-group.tsx
  app/src/ui/tutorial/tutorial-panel.tsx
  app/test/unit/app-test.tsx
  app/yarn.lock
  package.json
  yarn.lock
Labels: dependencies, ready-for-review

#7080 Add option to retry cloning upon thrown clone errors
  app/src/models/popup.ts
  app/src/ui/app.tsx
  app/src/ui/clone-repository/retry-clone-dialog.tsx
  app/src/ui/dispatcher/error-handlers.ts
  app/src/ui/index.tsx
Labels: ready-for-review

#7054 feat: add context menu for highlighted text in diff view
  app/src/ui/diff/code-mirror-host.tsx
  app/src/ui/diff/text-diff.tsx
Labels: accessibility, enhancement, ready-for-review

#9667 Show unpushed indicator on commits that have unpushed tags
  app/src/ui/history/commit-list-item.tsx
  app/src/ui/history/commit-list.tsx
  app/src/ui/history/compare.tsx
  app/src/ui/repository.tsx
Labels: epic:tags
