Repository desktop/desktop, pull requests merged in 2020-03, with the labels that each got.

#8656 Added support with the PhpStorm editor and updated for WebStorm
  app/src/lib/editors/win32.ts
Labels: integrations, ready-for-review

#8399 Add suport to IntelliJ Idea on Mac
  app/src/lib/editors/darwin.ts
  docs/technical/editor-integration.md
Labels: integrations

#9154 Automatically set Git proxy environment variables from system configuration
  app/src/lib/feature-flag.ts
  app/src/lib/git/environment.ts
  app/src/lib/resolve-git-proxy.ts
  app/test/unit/git/environment-test.ts
Labels: epic:proxy

#9047 add Windows Terminal as a shell option
  app/src/lib/shells/win32.ts
Labels: integrations, windows

#9188 Support disabling certificate revocation checks on Windows
  app/src/lib/feature-flag.ts
  app/src/lib/git/config.ts
  app/src/models/popup.ts
  app/src/ui/app.tsx
  app/src/ui/dialog/dialog.tsx
  app/src/ui/dispatcher/error-handlers.ts
  app/src/ui/index.tsx
  app/src/ui/preferences/advanced.tsx
  app/src/ui/preferences/preferences.tsx
  app/src/ui/schannel-no-revocation-check/schannel-no-revocation-check.tsx
  app/test/unit/git/config-test.ts
Labels: epic:proxy

#9016 Add Support for Windows Automatic Dark Mode
  app/package.json
  app/src/lib/get-os.ts
  app/src/ui/lib/dark-theme.ts
  app/src/ui/lib/theme-change-monitor.ts
  app/yarn.lock
Labels: ready-for-review, themes, windows

#9248 Updated shell integration docs to reflect code
  docs/technical/shell-integration.md
Labels: docs, ready-for-review

#9268 Offer branching from upstream default branch in forks
  app/src/lib/branch.ts
  app/src/lib/create-branch.ts
  app/src/lib/feature-flag.ts
  app/src/lib/git/branch.ts
  app/src/models/branch.ts
  app/src/ui/app.tsx
  app/src/ui/create-branch/create-branch-dialog.tsx
  app/test/unit/create-branch-test.ts
Labels: epic:fork

#9301 Set min-height of FilterList to make it scrollable under any situation
  app/styles/ui/_filter-list.scss
Labels: epic:onboarding

#9314 Add issue creation metric
  app/src/lib/stats/stats-database.ts
  app/src/lib/stats/stats-store.ts
  app/src/models/repository.ts
  app/src/ui/app.tsx
  app/src/ui/dispatcher/dispatcher.ts
Labels: metrics

#9316 Redirect to upstream repo when clicking on "View on GitHub"
  app/src/ui/app.tsx
Labels: epic:fork

#9321 add instrumentation for schannel revocation check error encountered
  app/src/ui/dispatcher/error-handlers.ts
Labels: epic:proxy

#9322 add noTrack option for createBranch
  app/src/lib/git/branch.ts
  app/src/lib/stores/app-store.ts
  app/src/ui/create-branch/create-branch-dialog.tsx
  app/src/ui/dispatcher/dispatcher.ts
Labels: epic:fork

#9344 Allow shrinking for resizable lists with a footer
  app/styles/ui/_branches.scss
  app/styles/ui/history/_commit-list.scss
  app/styles/ui/history/_history.scss
Labels: electron

#9052 Revamp draft release task
  package.json
  script/draft-release/run.ts
  yarn.lock
Labels: infrastructure

#9332 Add support for Android Studio on macOS
  app/src/lib/editors/darwin.ts
  docs/technical/editor-integration.md
Labels: integrations

#9283 Update windows docs
  docs/contributing/setup-windows.md
Labels: docs, ready-for-review

#9238 Add Support for Notepad++
  app/src/lib/editors/win32.ts
  docs/technical/editor-integration.md
Labels: integrations, ready-for-review, windows
