Repository desktop/desktop, pull requests merged in 2020-08, with the labels that each got.

#10195 Add backslash when trying to open folders in Windows
  app/src/main-process/shell.ts
Labels: windows

#10260 Create <RadioButton/> component
  app/src/ui/lib/radio-button.tsx
  app/src/ui/preferences/advanced.tsx
  app/src/ui/repository-settings/fork-settings.tsx
  app/styles/_ui.scss
  app/styles/ui/_preferences.scss
  app/styles/ui/_radio-button.scss
  app/styles/ui/dialogs/_repository-settings.scss
Labels: tech-debt

#10239 Make sure that `onPopupDismissed` only dismisses the relevant popup
  app/src/ui/app.tsx
  app/src/ui/changes/oversized-files-warning.tsx
  app/src/ui/delete-branch/delete-branch-dialog.tsx
  app/src/ui/delete-branch/delete-pull-request-dialog.tsx
  app/src/ui/generic-git-auth/generic-git-auth.tsx
  app/src/ui/lfs/attribute-mismatch.tsx
  app/src/ui/lfs/initialize-lfs.tsx
  app/src/ui/merge-branch/merge.tsx
  app/src/ui/rebase/rebase-flow.tsx
  app/src/ui/sign-in/sign-in.tsx
  app/src/ui/tutorial/confirm-exit-tutorial.tsx
  app/src/ui/untrusted-certificate/untrusted-certificate.tsx
  app/src/ui/usage-stats-change/usage-stats-change.tsx
Labels: tech-debt

#9737 use only custom rules in tslint
  .eslintignore
  .eslintrc.yml
  app/src/crash/crash-app.tsx
  app/src/lib/api.ts
  app/src/lib/diff-parser.ts
  app/src/lib/feature-flag.ts
  app/src/lib/git/core.ts
  app/src/lib/git/diff-check.ts
  app/src/lib/git/diff.ts
  app/src/lib/globals.d.ts
  app/src/lib/helpers/regex.ts
  app/src/lib/stores/commit-status-store.ts
  app/src/lib/stores/git-store.ts
  app/src/lib/stores/github-user-store.ts
  app/src/lib/stores/helpers/background-fetcher.ts
  app/src/models/status.ts
  app/src/ui/autocompletion/autocompleting-text-input.tsx
  app/src/ui/changes/changes-list.tsx
  app/src/ui/changes/sidebar.tsx
  app/src/ui/dialog/error.tsx
  app/src/ui/diff/code-mirror-host.tsx
  app/src/ui/diff/seamless-diff-switcher.tsx
  app/src/ui/history/commit-summary.tsx
  app/src/ui/history/selected-commit.tsx
  app/src/ui/lib/configure-git-user.tsx
  app/src/ui/lib/conflicts/unmerged-file.tsx
  app/src/ui/lib/ui-activity-monitor.ts
  app/src/ui/preferences/preferences.tsx
  app/src/ui/rebase/rebase-flow.tsx
  app/src/ui/repository.tsx
  app/src/ui/ui-view.tsx
  app/test/helpers/github-repo-builder.ts
  package.json
  script/build.ts
  tslint.json
  yarn.lock
Labels: infrastructure

#10261 Create <RefNameTextBox/> component
  app/src/ui/create-branch/create-branch-dialog.tsx
  app/src/ui/create-tag/create-tag-dialog.tsx
  app/src/ui/lib/branch-name-warnings.tsx
  app/src/ui/lib/fancy-text-box.tsx
  app/src/ui/lib/ref-name-text-box.tsx
  app/src/ui/lib/text-box.tsx
  app/src/ui/rename-branch/rename-branch-dialog.tsx
  app/styles/_ui.scss
  app/styles/ui/_ref-name-text-box.scss
Labels: tech-debt

#10319 Upgrade react-transition-group npm package
  app/package.json
  app/src/ui/app-error.tsx
  app/src/ui/app.tsx
  app/src/ui/changes/sidebar.tsx
  app/src/ui/history/compare.tsx
  app/src/ui/window/full-screen-info.tsx
  app/src/ui/window/zoom-info.tsx
  app/styles/ui/_banners.scss
  app/styles/ui/_dialog.scss
  app/styles/ui/_notification-banner.scss
  app/styles/ui/changes/_changes-list.scss
  app/styles/ui/window/_toast-notification.scss
  app/styles/ui/window/_zoom-info.scss
  app/webpack.common.ts
  app/yarn.lock
  package.json
  yarn.lock
Labels: tech-debt

#8218 Enable discarding submodule changes
  app/src/lib/git/submodule.ts
  app/test/unit/git/submodule-test.ts
Labels: ready-for-review

#9864 Use check runs API for PR status
  app/src/lib/api.ts
  app/src/lib/stores/commit-status-store.ts
  app/src/models/pull-request.ts
  app/src/ui/branches/ci-status.tsx
  app/src/ui/branches/pull-request-list-item.tsx
  app/src/ui/branches/pull-request-status.ts
  app/src/ui/dispatcher/dispatcher.ts
  app/styles/ui/_branches.scss
  app/styles/ui/_ci-status.scss
  app/test/unit/pull-request-status-test.ts
Labels: community

#10410 Add AspNet and Diff/Patch Syntax Highlights
  app/src/highlighter/index.ts
  docs/technical/syntax-highlighting.md
Labels: community, ready-for-review
