Repository desktop/desktop, pull requests merged in 2020-01, with the labels that each got.

#8843 Support GoLand as external editor on Mac
  app/src/lib/editors/darwin.ts
  docs/technical/editor-integration.md
Labels: ready-for-review

#8845 Refactor RepositoriesStore to use TypedBaseStore
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/repositories-store.ts
Labels: epic:fork

#8756 Yellow Icon for Dev Build
  app/static/logos/icon-logo-yellow.icns
  app/static/logos/icon-logo-yellow.ico
  script/build.ts
  script/dist-info.ts
  script/package.ts
Labels: infrastructure

#8825 [Fork] Initial PullRequestCoordinator (P)refactor
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/index.ts
  app/src/lib/stores/pull-request-coordinator.ts
  app/src/models/repository.ts
  app/src/ui/index.tsx
  app/test/unit/app-store-test.ts
  app/test/unit/app-test.tsx
Labels: epic:fork

#8881 make setRemoteURL return a boolean
  app/src/lib/git/remote.ts
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/git-store.ts
  app/test/unit/git/remote-test.ts
Labels: epic:fork, tech-debt

#8858 [Fork] Propogate updates from PullRequestStore to all related repos
  app/src/lib/stores/pull-request-coordinator.ts
  app/src/ui/branches/branches-container.tsx
Labels: epic:fork

#8868 [Fork] PullRequestUpdater handles local forks
  app/src/lib/stores/helpers/pull-request-updater.ts
  app/src/lib/stores/pull-request-coordinator.ts
Labels: epic:fork

#8920 Bump dugite to 1.88.0
  app/package.json
  app/src/lib/git/core.ts
  app/yarn.lock
Labels: dependencies

#8917 [Fork] De-duplicate pull request loading events
  app/src/lib/stores/pull-request-coordinator.ts
  app/src/lib/stores/pull-request-store.ts
Labels: epic:fork

#8889 [Fork] "Do you want to fork this repository?" Dialog
  app/src/lib/api.ts
  app/src/lib/feature-flag.ts
  app/src/lib/stores/app-store.ts
  app/src/models/popup.ts
  app/src/ui/app.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/dispatcher/error-handlers.ts
  app/src/ui/forks/create-fork-dialog.tsx
  app/src/ui/index.tsx
  app/styles/ui/_dialog.scss
  app/styles/ui/dialogs/_create-fork.scss
Labels: epic:fork, time-sensitive

#8929 [Fork] Open PR from fork in browser
  app/src/lib/stores/app-store.ts
Labels: epic:fork

#8939 [Fork] Add create fork flow entry point to commit warning
  app/src/ui/changes/commit-message.tsx
Labels: epic:fork

#8965 [Fork] PR list call to action
  app/src/ui/branches/no-pull-requests.tsx
  app/src/ui/branches/pull-request-list.tsx
  app/styles/ui/_branches.scss
Labels: epic:fork

#8972 [Forks] Enable for all
  app/src/lib/feature-flag.ts
Labels: epic:fork

#8979 [Forks] Metrics, Part 1
  app/src/lib/stats/stats-database.ts
  app/src/lib/stats/stats-store.ts
  app/src/lib/stores/app-store.ts
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/forks/create-fork-dialog.tsx
Labels: epic:fork

#8978 Add Number Array Helpers for Local Storage
  app/src/lib/local-storage.ts
  app/src/lib/stores/app-store.ts
Labels: epic:fork, tech-debt

#8980 [Forks] Metrics, Part 2
  app/src/lib/stats/stats-store.ts
  app/src/lib/stores/app-store.ts
Labels: epic:fork

#8990 Clean up remnants of button group order TSLint rule.
  app/src/ui/merge-conflicts/commit-conflicts-warning.tsx
  tslint.json
Labels: tech-debt

#8969 Release Notes Writing Guide
  docs/process/releasing-updates.md
  docs/process/writing-release-notes.md
  script/draft-release/run.ts
Labels: docs, meta
