Repository desktop/desktop, pull requests merged in 2020-06, with the labels that each got.

#9865 Perform refreshTags operation inside refreshRepository()
  app/src/lib/stores/app-store.ts
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/index.tsx
Labels: epic:tags

#9498 Change deprecated getZoomFactor() with zoomFactor property
  app/src/lib/stores/app-store.ts
  app/src/main-process/menu/build-default-menu.ts
  app/test/__mocks__/electron.ts
Labels: ready-for-review

#9857 Fix Ctrl+W shortcut not working in dialogs
  app/src/ui/dialog/dialog.tsx
Labels: ready-for-review, windows

#9984 Promise helper cleanup
  app/src/lib/promise.ts
  app/test/unit/promise-with-timeout-test.ts
Labels: priority-3

#10005 Hide horizontal scroll in AppError dialog
  app/styles/ui/_dialog.scss
Labels: priority-3, windows

#9870 Refactor VerticalSegmentedControl to use unique values instead of indices
  app/src/ui/choose-fork-settings/choose-fork-settings-dialog.tsx
  app/src/ui/create-branch/create-branch-dialog.tsx
  app/src/ui/lib/vertical-segmented-control/segmented-item.tsx
  app/src/ui/lib/vertical-segmented-control/vertical-segmented-control.tsx
  app/src/ui/preferences/appearance.tsx
  app/src/ui/stash-changes/stash-and-switch-branch-dialog.tsx
Labels: tech-debt
