Repository desktop/desktop, pull requests merged in 2020-09, with the labels that each got.

#9382 Unify logic to checkout a pull request
  app/src/lib/stores/app-store.ts
  app/src/ui/dispatcher/dispatcher.ts
Labels: tech-debt

#10581 Remove schannel check revoke setting and alert dialog
  app/src/lib/feature-flag.ts
  app/src/models/popup.ts
  app/src/ui/app.tsx
  app/src/ui/dispatcher/error-handlers.ts
  app/src/ui/index.tsx
  app/src/ui/preferences/advanced.tsx
  app/src/ui/preferences/preferences.tsx
  app/src/ui/schannel-no-revocation-check/schannel-no-revocation-check.tsx
Labels: proxy, windows

#10519 Fix keyboard submit in merge and rebase dialog
  app/src/ui/branches/branch-list.tsx
  app/src/ui/merge-branch/merge.tsx
  app/src/ui/rebase/choose-branch.tsx
Labels: accessibility

#10561 Only show full screen toast notification when making the app window full-screen
  app/src/ui/window/full-screen-info.tsx
Labels: macOS

#8333 After failing to move a repository to Trash, show error and keep the repository listed in Desktop
  app/src/lib/stores/app-store.ts
  app/src/ui/app.tsx
  app/src/ui/dispatcher/dispatcher.ts
  app/src/ui/missing-repository.tsx
Labels: ready-for-review

#10601 Electron 9.3.1
  app/.npmrc
Labels: ready-for-review

#7634 Replace auth error with not found error for non-existent GitHub repos
  app/src/lib/api.ts
  app/src/lib/remote-parsing.ts
  app/src/ui/clone-repository/clone-repository.tsx
Labels: community

#10214 Added email validation on welcome and preferences screen
  app/src/ui/lib/configure-git-user.tsx
  app/src/ui/lib/text-box.tsx
  app/src/ui/preferences/git.tsx
  app/styles/ui/_text-box.scss
Labels: community

#10602 Typo fixes and some minor readability tweaks
  app/src/lib/stores/app-store.ts
  app/src/lib/stores/updates/changes-state.ts
  app/src/ui/diff/text-diff.tsx
  app/src/ui/dispatcher/dispatcher.ts
Labels: ready-for-review
