Repository desktop/desktop, pull requests merged in 2025-03, with the labels that each got.

#20121 Windsurf integration to External Editors
  app/src/lib/editors/darwin.ts
  app/src/lib/editors/win32.ts
  docs/technical/editor-integration.md
Labels: more-info-needed, triage, external

#20126 Use Dev protocol when using Dev secrets
  app/app-info.ts
  app/src/lib/globals.d.ts
  app/src/main-process/main.ts
Labels: triage, external

#20052 Vertical segmented control uses radio group component
  app/src/ui/lib/radio-button.tsx
  app/src/ui/lib/radio-group.tsx
  app/src/ui/lib/vertical-segmented-control/segmented-item.tsx
  app/src/ui/lib/vertical-segmented-control/vertical-segmented-control.tsx
  app/styles/ui/_vertical-segmented-control.scss
Labels: accessibility

#20162 Improve default README formatting
  app/src/ui/add-repository/write-default-readme.ts
  app/test/unit/write-default-readme-test.ts
Labels: triage, external
